/* file generated by oo2c -- do not edit */
#ifndef _MODULE_AlgebraicTransformation_
#define _MODULE_AlgebraicTransformation_

#include "Data.h"
extern Data__Const AlgebraicTransformation__GetZero(Data__Struct type);
extern Data__Const AlgebraicTransformation__GetOne(Data__Struct type);
extern void AlgebraicTransformation__Transform(Data__Region reg);
extern void AlgebraicTransformation_init(void);

#endif
