/* file generated by oo2c -- do not edit */
#ifndef _MODULE_AliasAnalysis_
#define _MODULE_AliasAnalysis_

#define AliasAnalysis__noAlias -1
#define AliasAnalysis__mayAlias 0
#define AliasAnalysis__doAlias 1
#define AliasAnalysis__accessOrUpdate 0
#define AliasAnalysis__onlyAccess 1
#define AliasAnalysis__onlyUpdate 2
extern unsigned char AliasAnalysis__enabled;
#include "Data.h"
extern signed char AliasAnalysis__Aliasing(Data__Instruction i0_, signed char m0, Data__Instruction i1_, signed char m1);
extern unsigned char AliasAnalysis__TransitiveStoreAlias(Data__Instruction a, Data__Instruction b);
extern void AliasAnalysis__Analyse(Data__Region greg);
extern unsigned char AliasAnalysis__NeedLocalCopy(Data__GlobalRegion greg, Data__Object fpar);
extern struct _TD AliasAnalysis__Aliasing_Selector_td;
extern void AliasAnalysis_init(void);

#endif
