/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "Attributes.d"

static _ModId _mid;

void Attributes__InitItem(Attributes__Item *x, _Type x__tag, int pos) {
  register int i0;
  i0 = (int)x + 4;
  *(int*)(int)x = pos;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 8;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 12;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 28;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 16;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 20;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 24;
  *(int*)i0 = -1;
  i0 = (int)x + 32;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 36;
  *(void**)i0 = (void*)0;
  i0 = (int)x + 40;
  *(unsigned char*)i0 = 0;
  i0 = (int)x + 41;
  *(unsigned char*)i0 = 1;
  i0 = (int)x + 42;
  *(short int*)i0 = 0;
  i0 = (int)x + 44;
  *(int*)i0 = -1;
}

void Attributes__CreateItem(Attributes__Item *x, _Type x__tag, Data__Usable u, int pos) {
  register int i0, i1;
  i0 = *(int*)((int)u-4);
  i1 = _type_test(i0, &Data__ConstDesc_td.td, 3);
  Attributes__InitItem((Attributes__Item *)(int)x, x__tag, (int)pos);
  if (i1) goto l1;
  i1 = _type_test(i0, &Data__ResultDesc_td.td, 3);
  if (i1) goto l0;
  i0 = _type_test(i0, &Data__StructDesc_td.td, 4);
  if (!(i0)) goto l2;
  i0 = (int)x + 8;
  *(void**)i0 = (void*)(int)u;
  goto l2;
l0:
  i0 = (int)u + 24;
  i1 = (int)*(void**)i0;
  i0 = (int)x + 8;
  *(void**)i0 = (void*)i1;
  i0 = (int)x + 16;
  *(void**)i0 = (void*)(int)u;
  goto l2;
l1:
  i0 = (int)u + 16;
  i0 = (int)*(void**)i0;
  i1 = (int)x + 8;
  *(void**)i1 = (void*)i0;
  i0 = (int)x + 12;
  *(void**)i0 = (void*)(int)u;
  i0 = (int)x + 16;
  *(void**)i0 = (void*)(int)u;
l2:
  ;
}

void Attributes__SetOpndPos(Data__Instruction instr, int pos) {
  register int i0, i1;
  i0 = (int)Data__InstructionDesc_LastOperand((Data__Instruction)(int)instr);
  i1 = i0 + 20;
  *(int*)i1 = pos;
}

void Attributes__Operand(Data__Instruction instr, Attributes__Item *x, _Type x__tag) {
  register int i0;
  i0 = (int)x + 16;
  i0 = (int)*(void**)i0;
  Data__InstructionDesc_Operand((Data__Instruction)(int)instr, (Data__Usable)i0);
  i0 = *(int*)(int)x;
  Attributes__SetOpndPos((Data__Instruction)(int)instr, (int)i0);
}

Data__Instruction Attributes__DyadicOp(Data__Region region, short int opcode, Data__Struct type, Attributes__Item *opnd1, _Type opnd1__tag, Attributes__Item *opnd2, _Type opnd2__tag, int pos) {
  register int i0;
  i0 = (int)Data__RegionDesc_CreateInstruction((Data__Region)(int)region, (short int)opcode, (Data__Struct)(int)type, (int)pos);
  Attributes__Operand((Data__Instruction)i0, (Attributes__Item *)(int)opnd1, opnd1__tag);
  Attributes__Operand((Data__Instruction)i0, (Attributes__Item *)(int)opnd2, opnd2__tag);
  return (void*)i0;
}

void Attributes__InitExitInfo(Attributes__ExitInfo *i, _Type i__tag) {
  register int i0;
  i0 = (int)i + 4;
  *(void**)(int)i = (void*)0;
  *(void**)i0 = (void*)0;
  i0 = (int)i + 8;
  *(unsigned char*)i0 = 0;
  i0 = (int)i + 12;
  *(void**)i0 = (void*)0;
  i0 = (int)i + 16;
  *(unsigned char*)i0 = 0;
  i0 = (int)i + 20;
  *(void**)i0 = (void*)0;
  i0 = (int)i + 24;
  *(unsigned char*)i0 = 0;
}

void Attributes__ExitInfoOr(Attributes__ExitInfo *exitInfo, _Type exitInfo__tag, Attributes__ExitInfo *nestedInfo, _Type nestedInfo__tag) {
  register int i0, i1, i2;
  i2 = (int)exitInfo + 8;
  i0 = *(unsigned char*)i2;
  if (i0) goto l0;
  i0 = (int)nestedInfo + 8;
  i0 = *(unsigned char*)i0;
  if (i0) goto l0;
  i0 = 0;
  goto l1;
l0:
  i0 = 1;
l1:
  i1 = (int)exitInfo + 16;
  *(unsigned char*)i2 = i0;
  i0 = *(unsigned char*)i1;
  if (i0) goto l2;
  i0 = (int)nestedInfo + 16;
  i0 = *(unsigned char*)i0;
  if (i0) goto l2;
  i0 = 0;
  goto l3;
l2:
  i0 = 1;
l3:
  i2 = (int)exitInfo + 24;
  *(unsigned char*)i1 = i0;
  i0 = *(unsigned char*)i2;
  if (i0) goto l4;
  i0 = (int)nestedInfo + 24;
  i0 = *(unsigned char*)i0;
  if (i0) goto l4;
  i0 = 0;
  goto l5;
l4:
  i0 = 1;
l5:
  *(unsigned char*)i2 = i0;
}

Data__Guard Attributes__CreateGuard(Attributes__Item *cond, _Type cond__tag, short int opcode, int pos) {
  register int i0, i1, i2, i3;
  i0 = (int)cond + 16;
  i0 = (int)*(void**)i0;
  i0 = (int)Data__CreateGuard((Data__Usable)i0, (short int)opcode, (int)pos);
  i1 = i0 + 28;
  i3 = (int)*(void**)i1;
  i1 = i3 + 20;
  i2 = *(int*)(int)cond;
  *(int*)i1 = i2;
  return (void*)i0;
}

Data__GlobalRegion Attributes__CreateGreg(Data__Object bodyOf) {
  register int i0, i1, i2, i3;
  {
    char *_mem, *_var;
    _mem = GC_malloc(_not_zero(92)+8);
    if (!_mem) _new_failed(_P(6666));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Data__GlobalRegionDesc_td.td;
    i0 = (int)_var;
  }
  i3 = i0 + 80;
  i1 = (int)SymbolTable__constTrue;
  i2 = Scanner__currSymPos;
  Data__InitGuard((Data__Guard)i0, (Data__Usable)i1, (short int)66, (int)i2);
  *(void**)i3 = (void*)(int)bodyOf;
  i1 = i0 + 84;
  i2 = Scanner__currSymPos;
  i2 = (int)Data__RegionDesc_CreateInstruction((Data__Region)i0, (short int)1, (Data__Struct)0, (int)i2);
  *(void**)i1 = (void*)i2;
  i1 = i0 + 88;
  i2 = Scanner__currSymPos;
  i2 = (int)Data__RegionDesc_CreateInstruction((Data__Region)i0, (short int)2, (Data__Struct)0, (int)i2);
  *(void**)i1 = (void*)i2;
  return (void*)i0;
}

void Attributes__InitGreg_Parameter(Data__Object obj, Data__GlobalRegion *Attributes__InitGreg_greg) {
  register int i0, i1, i2, i3, i4, i5, i6, i7;
  i5 = (int)*Attributes__InitGreg_greg;
  i6 = i5 + 84;
  i4 = (int)obj + 24;
  i0 = (int)*(void**)i6;
  i1 = (int)Data__CreateSymLocation((Data__Addressable)(int)obj, (short int)-3);
  i2 = (int)*(void**)i4;
  i0 = (int)Data__InstructionDesc_AppendResult((Data__Instruction)i0, (Data__Location)i1, (Data__Struct)i2);
  i1 = (int)obj + 12;
  *(void**)i1 = (void*)i0;
  i0 = StdTypes__PassPerReference((Data__Object)(int)obj, (unsigned char)1);
  if (!(i0)) goto l0;
  i1 = (int)*(void**)i6;
  i0 = (int)Data__CreateSymLocation((Data__Addressable)(int)obj, (short int)-2);
  i2 = (int)Data__struct + 24;
  i2 = (int)*(void**)i2;
  i1 = (int)Data__InstructionDesc_AppendResult((Data__Instruction)i1, (Data__Location)i0, (Data__Struct)i2);
l0:
  i0 = (int)obj + 28;
  i0 = *(signed char*)i0;
  i0 = i0 != 4;
  if (i0) goto l1;
  i0 = (int)*(void**)i4;
  i0 += 20;
  i0 = *(signed char*)i0;
  i0 = i0 == 31;
  if (i0) goto l3;
l1:
  i3 = (int)obj + 64;
  i3 = *(unsigned int*)i3;
  i3 = (i3 & ((unsigned int)1 << 5)) != 0;
  if (i3) goto l4;
  i4 = (int)*(void**)i4;
  i2 = Data__StructDesc_OpenDimensions((Data__Struct)i4);
  i4 = i2 < 1;
  if (i4) goto l4;
  i4 = (int)Data__struct + 24;
  i3 = 1;
l2:
  i0 = (int)*(void**)i6;
  i1 = i3 - 1;
  i1 = (int)Data__CreateSymLocation((Data__Addressable)(int)obj, (short int)i1);
  i3++;
  i7 = (int)*(void**)i4;
  i0 = (int)Data__InstructionDesc_AppendResult((Data__Instruction)i0, (Data__Location)i1, (Data__Struct)i7);
  i0 = i2 >= i3;
  if (i0) goto l2;
  goto l4;
l3:
  i0 = (int)obj + 64;
  i0 = *(unsigned int*)i0;
  i0 = (i0 & ((unsigned int)1 << 6)) != 0;
  if (i0) goto l4;
  i0 = (int)*(void**)i6;
  i1 = (int)Data__CreateSymLocation((Data__Addressable)(int)obj, (short int)-1);
  i0 = (int)Data__InstructionDesc_AppendResult((Data__Instruction)i0, (Data__Location)i1, (Data__Struct)0);
l4:
  ;
}

Data__Instruction Attributes__InitGreg_CreateFalse(Data__GlobalRegion *Attributes__InitGreg_greg) {
  register int i0, i1;
  i0 = (int)Data__struct + 4;
  i0 = (int)*(void**)i0;
  i1 = (int)*Attributes__InitGreg_greg;
  i1 = (int)Data__RegionDesc_CreateInstruction((Data__Region)i1, (short int)18, (Data__Struct)i0, (int)-1);
  i0 = (int)SymbolTable__constFalse;
  Data__InstructionDesc_Operand((Data__Instruction)i1, (Data__Usable)i0);
  return (void*)i1;
}

Data__GlobalRegion Attributes__InitGreg(Data__GlobalRegion greg, Attributes__ExitInfo *i, _Type i__tag) {
  register int i0, i1, i2, i3, i4, i5, i6;
  i0 = (int)greg + 80;
  i1 = (int)*(void**)i0;
  Attributes__InitExitInfo((Attributes__ExitInfo *)(int)i, i__tag);
  i0 = (int)SymbolTable__store;
  i2 = (int)*(void**)(int)Data__struct;
  i3 = (int)Data__RegionDesc_CreateInstruction((Data__Region)(int)greg, (short int)6, (Data__Struct)i2, (int)-1);
  i2 = (int)SymbolTable__store;
  i4 = i0 + 12;
  *(void**)i4 = (void*)i3;
  i0 = i2 + 12;
  i3 = (int)*(void**)i0;
  i4 = i3 + 48;
  i0 = i1 + 72;
  i6 = *(unsigned int*)i4;
  i5 = i2 + 40;
  i6 = i6 | ((unsigned int)1 << 1);
  *(void**)i5 = (void*)i1;
  *(unsigned int*)i4 = i6;
  i2 = *(int*)i0;
  i2 = (int)SymbolTable__NewObject((const unsigned char*)(int)_c0, 8, (signed char)3, (int)i2);
  i3 = (int)i + 4;
  *(void**)i3 = (void*)i2;
  i2 = (int)*(void**)i3;
  i3 = (int)Data__struct + 4;
  i5 = i2 + 24;
  i4 = (int)*(void**)i3;
  *(void**)i5 = (void*)i4;
  i4 = i2 + 40;
  *(void**)i4 = (void*)i1;
  i4 = (int)Attributes__InitGreg_CreateFalse((Data__GlobalRegion *)&greg);
  i5 = i2 + 12;
  *(void**)i5 = (void*)i4;
  i2 = *(int*)i0;
  i2 = (int)SymbolTable__NewObject((const unsigned char*)(int)_c1, 6, (signed char)3, (int)i2);
  i4 = (int)i + 20;
  *(void**)i4 = (void*)i2;
  i2 = (int)*(void**)i4;
  i3 = (int)*(void**)i3;
  i4 = i2 + 24;
  *(void**)i4 = (void*)i3;
  i3 = i2 + 40;
  *(void**)i3 = (void*)i1;
  i4 = (int)Attributes__InitGreg_CreateFalse((Data__GlobalRegion *)&greg);
  i3 = i1 + 28;
  i5 = i2 + 12;
  *(void**)i5 = (void*)i4;
  i2 = *(signed char*)i3;
  i2 = i2 == 7;
  if (i2) goto l0;
  i4 = (int)greg;
  goto l1;
l0:
  i2 = i1 + 52;
  i2 = (int)*(void**)i2;
  Attributes__InitGreg_Parameter((Data__Object)i2, (Data__GlobalRegion *)&greg);
  i4 = (int)greg;
l1:
  i2 = *(signed char*)i3;
  i2 = i2 != 8;
  if (i2) goto l2;
  i5 = i4;
  goto l7;
l2:
  i3 = i1 + 24;
  i5 = (int)*(void**)i3;
  i5 += 24;
  i5 = (int)*(void**)i5;
  i5 += 20;
  i5 = *(signed char*)i5;
  i5 = i5 == 21;
  if (i5) goto l3;
  i0 = *(int*)i0;
  i0 = (int)SymbolTable__NewObject((const unsigned char*)(int)_c2, 8, (signed char)3, (int)i0);
  i2 = (int)*(void**)i3;
  *(void**)(int)i = (void*)i0;
  i0 = (int)*(void**)(int)i;
  i5 = i2 + 24;
  i2 = i0 + 24;
  i5 = (int)*(void**)i5;
  *(void**)i2 = (void*)i5;
  i2 = i4 + 88;
  i5 = i0 + 40;
  *(void**)i5 = (void*)i1;
  i5 = (int)*(void**)i2;
  Data__InstructionDesc_Operand((Data__Instruction)i5, (Data__Usable)i0);
  i0 = (int)*(void**)i2;
  i0 += 28;
  i0 = (int)*(void**)i0;
  i2 = (int)*(void**)(int)i;
  i5 = (int)Data__CreateSymLocation((Data__Addressable)i2, (short int)-3);
  i2 = i0 + 16;
  *(void**)i2 = (void*)i5;
l3:
  i5 = (int)*(void**)i3;
  i5 += 28;
  i5 = (int)*(void**)i5;
  i3 = i5 != 0;
  if (i3) goto l4;
  i5 = i4;
  goto l7;
l4:
  i3 = i4;
l5:
  greg = (void*)i3;
  greg = (void*)i3;
  Attributes__InitGreg_Parameter((Data__Object)i5, (Data__GlobalRegion *)&greg);
  i3 = i5 + 36;
  i5 = (int)*(void**)i3;
  i3 = i5 == 0;
  if (i3) goto l6;
  i3 = (int)greg;
  goto l5;
l6:
  i5 = (int)greg;
l7:
  return (void*)i5;
}

unsigned char Attributes__TracesToEmptyStore_ModifiedVarParam(Data__Object var, Data__Instruction call) {
  register int i0, i1, i2, i3;
  i0 = (int)call + 28;
  i2 = (int)*(void**)i0;
  i0 = i2 != 0;
  if (i0) goto l0;
  i3 = 0;
  goto l9;
l0:
l1:
  i0 = i2 + 16;
  i1 = (int)*(void**)i0;
  i0 = i1 == 0;
  if (i0) goto l2;
  i1 = (int)*(void**)i1;
  i3 = *(int*)(i1-4);
  i3 = _type_test(i3, &Data__ObjectDesc_td.td, 4);
  if (i3) goto l3;
l2:
  i3 = 0;
  goto l7;
l3:
  i1 += 28;
  i1 = *(signed char*)i1;
  i1 = i1 != 4;
  if (i1) goto l5;
  i1 = (int)*(void**)i2;
  i3 = *(int*)(i1-4);
  i3 = _type_test(i3, &Data__InstructionDesc_td.td, 4);
  if (!(i3)) goto l5;
  i0 = i1 + 44;
  i3 = *(short int*)i0;
  i0 = i3 == 35;
  if (i0) goto l4;
  i3 = i3 != 36;
  if (i3) goto l5;
l4:
  i1 += 28;
  i1 = (int)*(void**)i1;
  i1 = (int)*(void**)i1;
  i1 = (int)var == i1;
  if (i1) goto l6;
l5:
  i3 = 0;
  goto l7;
l6:
  i3 = 1;
l7:
  if (i3) goto l8;
  i0 = i2 + 8;
  i0 = (int)*(void**)i0;
  i2 = i0;
l8:
  if (i3) goto l9;
  i0 = i2 != 0;
  if (i0) goto l1;
l9:
  return (unsigned char)i3;
}

unsigned char Attributes__TracesToEmptyStore(Data__Object var, Data__Usable store) {
  register int i0, i1, i2, i3, i4, i5;
  i0 = *(int*)((int)store-4);
  i0 = _type_test(i0, &Data__ResultDesc_td.td, 3);
  if (i0) goto l0;
  i5 = 0;
  goto l14;
l0:
  i4 = (int)store + 16;
  i0 = (int)*(void**)i4;
  i4 = i0 + 44;
  i1 = *(short int*)i4;
  i4 = i1 == 6;
  if (i4) goto l13;
  i2 = i1 == 3;
  if (i2) goto l11;
  i4 = i0 + 28;
  i2 = (int)*(void**)i4;
  i4 = (int)*(void**)i2;
  i4 = (int)var != i4;
  if (i4) goto l2;
  i4 = (int)var + 28;
  i4 = *(signed char*)i4;
  i3 = i4 != 4;
  if (i3) goto l1;
  i3 = i1 == 52;
  if (i3) goto l10;
l1:
  i4 = i4 != 4;
  if (!(i4)) goto l2;
  i4 = i1 == 51;
  if (i4) goto l10;
l2:
  i3 = i1 == 19;
  if (!(i3)) goto l3;
  i5 = i0 + 32;
  i5 = (int)*(void**)i5;
  i5 += 44;
  i5 = *(short int*)i5;
  i5 = i5 == 82;
  if (i5) goto l9;
l3:
  i4 = i1 == 50;
  if (i4) goto l8;
  i4 = i1 == 51;
  if (i4) goto l8;
  i4 = i1 == 52;
  if (i4) goto l8;
  if (i3) goto l4;
  i5 = 0;
  goto l14;
l4:
  i1 = i2 + 8;
  i3 = (int)*(void**)i1;
  i1 = i3 != 0;
  if (i1) goto l5;
  i5 = 0;
  goto l14;
l5:
l6:
  i1 = (int)*(void**)i3;
  i5 = Attributes__TracesToEmptyStore((Data__Object)(int)var, (Data__Usable)i1);
  if (i5) goto l7;
  i1 = i3 + 8;
  i1 = (int)*(void**)i1;
  i3 = i1;
l7:
  if (i5) goto l14;
  i1 = i3 != 0;
  if (i1) goto l6;
  goto l14;
l8:
  i5 = i2 + 8;
  i5 = (int)*(void**)i5;
  i5 += 8;
  i5 = (int)*(void**)i5;
  i5 = (int)*(void**)i5;
  i5 = Attributes__TracesToEmptyStore((Data__Object)(int)var, (Data__Usable)i5);
  goto l14;
l9:
  i5 = i2 + 8;
  i5 = (int)*(void**)i5;
  i5 = (int)*(void**)i5;
  i5 = Attributes__TracesToEmptyStore((Data__Object)(int)var, (Data__Usable)i5);
  goto l14;
l10:
  i5 = 0;
  goto l14;
l11:
  i2 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i0, (Data__Addressable)(int)var, (short int)-3);
  i2 = i2 != 0;
  if (i2) goto l12;
  i2 = Attributes__TracesToEmptyStore_ModifiedVarParam((Data__Object)(int)var, (Data__Instruction)i0);
  if (i2) goto l12;
  i5 = (int)SymbolTable__store;
  i0 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i0, (Data__Addressable)i5, (short int)-3);
  i0 = (int)*(void**)i0;
  i5 = Attributes__TracesToEmptyStore((Data__Object)(int)var, (Data__Usable)i0);
  goto l14;
l12:
  i5 = 0;
  goto l14;
l13:
  i5 = 1;
l14:
  return (unsigned char)i5;
}

void Attributes__GuardExit(Data__GlobalRegion greg, Attributes__ExitInfo *exitInfo, _Type exitInfo__tag) {
  register int i0, i1, i2, i3;
  i0 = (int)exitInfo + 20;
  i0 = (int)*(void**)i0;
  i0 += 12;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = _type_test(i1, &Data__InstructionDesc_td.td, 4);
  if (!(i1)) goto l0;
  i1 = i0 + 44;
  i1 = *(short int*)i1;
  i1 = i1 != 18;
  if (i1) goto l0;
  i1 = i0 + 28;
  i1 = (int)*(void**)i1;
  i1 = (int)*(void**)i1;
  i2 = (int)SymbolTable__constFalse;
  i1 = i1 != i2;
  if (i1) goto l0;
  i2 = (int)greg;
  goto l1;
l0:
  i2 = Scanner__currSymPos;
  i2 = (int)Data__CreateGuard((Data__Usable)i0, (short int)64, (int)i2);
  Data__RegionDesc_Insert((Data__Region)(int)greg, (Data__Instruction)i2);
  i0 = (int)greg + 88;
  i0 = (int)*(void**)i0;
  Data__RegionDesc_MoveInstruction((Data__Region)i2, (Data__Instruction)i0);
l1:
  i0 = (int)*(void**)(int)exitInfo;
  i0 = i0 == 0;
  if (i0) goto l3;
  i1 = (int)exitInfo + 4;
  i0 = (int)*(void**)i1;
  i0 += 12;
  i0 = (int)*(void**)i0;
  i3 = Scanner__currSymPos;
  i3 = (int)Data__CreateGuard((Data__Usable)i0, (short int)65, (int)i3);
  Data__RegionDesc_Insert((Data__Region)i2, (Data__Instruction)i3);
  i0 = (int)greg + 88;
  i0 = (int)*(void**)i0;
  Data__RegionDesc_MoveInstruction((Data__Region)i3, (Data__Instruction)i0);
  i1 = (int)*(void**)i1;
  i1 += 12;
  i1 = (int)*(void**)i1;
  i0 = Scanner__currSymPos;
  i1 = (int)Data__CreateGuard((Data__Usable)i1, (short int)64, (int)i0);
  Data__RegionDesc_Insert((Data__Region)i2, (Data__Instruction)i1);
  i0 = Scanner__currSymPos;
  i0 = (int)Data__RegionDesc_CreateInstruction((Data__Region)i1, (short int)96, (Data__Struct)0, (int)i0);
  i1 = i0 + 48;
  i2 = (int)StdPragmas__functResult;
  i2 += 8;
  i2 = *(unsigned char*)i2;
  if (i2) goto l2;
  i2 = *(unsigned int*)i1;
  i2 = i2 | ((unsigned int)1 << 1);
  *(unsigned int*)i1 = i2;
l2:
  i2 = *(unsigned int*)i1;
  i2 = i2 | ((unsigned int)1 << 0);
  *(unsigned int*)i1 = i2;
l3:
  ;
}

void Attributes__UnguardExit(Data__GlobalRegion greg, Attributes__ExitInfo *exitInfo, _Type exitInfo__tag) {
  register int i0, i1;
  i0 = (int)greg + 88;
  i0 = (int)*(void**)i0;
  i1 = i0 + 32;
  i1 = (int)*(void**)i1;
  i1 = (int)greg == i1;
  if (i1) goto l0;
  Data__RegionDesc_MoveInstruction((Data__Region)(int)greg, (Data__Instruction)i0);
l0:
  ;
}

Data__Result Attributes__FindAddEnterResult(Data__Region region, Data__Addressable var, short int attrib, Data__Struct type) {
  register int i0, i1, i2;
  i0 = (int)Data__RegionDesc_EnterInstr((Data__Region)(int)region);
  i2 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i0, (Data__Addressable)(int)var, (short int)attrib);
  i1 = i2 != 0;
  if (i1) goto l0;
  i2 = (int)Data__CreateSymLocation((Data__Addressable)(int)var, (short int)attrib);
  i2 = (int)Data__InstructionDesc_AppendResult((Data__Instruction)i0, (Data__Location)i2, (Data__Struct)(int)type);
l0:
  return (void*)i2;
}

Data__Result Attributes__Address(Data__Region region, Data__Addressable var, int pos) {
  register int i0, i1;
  i0 = *(int*)((int)var-4);
  i0 = _type_test(i0, &Data__ObjectDesc_td.td, 4);
  if (!(i0)) goto l0;
  i1 = (int)var + 28;
  i1 = *(signed char*)i1;
  i0 = i1 == 4;
  if (i0) goto l1;
  i1 = i1 != 3;
  if (i1) goto l0;
  i0 = (int)var + 40;
  i1 = (int)*(void**)i0;
  i0 = (int)SymbolTable__currScope;
  i0 = i1 != i0;
  if (i0) goto l1;
l0:
  i1 = (int)Data__RegionDesc_CreateAdrInstr((Data__Region)(int)region, (Data__Usable)(int)var, (int)pos);
  goto l2;
l1:
  i1 = (int)Data__struct + 24;
  i1 = (int)*(void**)i1;
  i1 = (int)Attributes__FindAddEnterResult((Data__Region)(int)region, (Data__Addressable)(int)var, (short int)-2, (Data__Struct)i1);
l2:
  return (void*)i1;
}

Data__Usable Attributes__TBProcAdr(Data__Region region, Data__Usable typeTag, Data__Struct staticType, Data__Object tbProc, int pos, unsigned char staticCall) {
  register int i0;
  if (staticCall) goto l0;
  i0 = (int)Data__struct + 24;
  i0 = (int)*(void**)i0;
  i0 = (int)Data__RegionDesc_CreateInstruction((Data__Region)(int)region, (short int)11, (Data__Struct)i0, (int)pos);
  Data__InstructionDesc_Operand((Data__Instruction)i0, (Data__Usable)(int)typeTag);
  Data__InstructionDesc_Operand((Data__Instruction)i0, (Data__Usable)(int)staticType);
  Data__InstructionDesc_Operand((Data__Instruction)i0, (Data__Usable)(int)tbProc);
  goto l1;
l0:
  i0 = (int)Data__RegionDesc_CreateAdrInstr((Data__Region)(int)region, (Data__Usable)(int)tbProc, (int)pos);
l1:
  return (void*)i0;
}

Data__Usable Attributes__Adr(Data__Region region, Attributes__Item *x, _Type x__tag) {
  register int i0, i1, i2, i3;
  i2 = (int)x + 28;
  i0 = (int)*(void**)i2;
  i0 = i0 != 0;
  if (i0) goto l1;
  i0 = (int)x + 12;
  i1 = (int)*(void**)i0;
  i1 = i1 == 0;
  if (i1) goto l0;
  i1 = (int)x + 8;
  i1 = (int)*(void**)i1;
  i1 = SymbolTable__TypeInGroup((Data__Struct)i1, (signed char)40);
  if (!(i1)) goto l0;
  i3 = (int)*(void**)i0;
  i0 = *(int*)(int)x;
  i0 = (int)Data__RegionDesc_CreateAdrInstr((Data__Region)(int)region, (Data__Usable)i3, (int)i0);
  *(void**)i2 = (void*)i0;
  goto l1;
l0:
  i0 = (int)x + 4;
  i0 = (int)*(void**)i0;
  i1 = i0 == 0;
  if (i1) goto l1;
  i1 = i0 + 28;
  i1 = *(signed char*)i1;
  i1 = (0x18U & ((unsigned int)1 << i1)) != 0;
  if (!(i1)) goto l1;
  i1 = *(int*)(int)x;
  i0 = (int)Attributes__Address((Data__Region)(int)region, (Data__Addressable)i0, (int)i1);
  *(void**)i2 = (void*)i0;
l1:
  i1 = (int)*(void**)i2;
  i0 = i1 != 0;
  if (i0) goto l2;
  i1 = (int)Data__constUndef;
l2:
  return (void*)i1;
}

Data__Usable Attributes__TypeTag_TypeDescrAdr(Data__Struct type, Attributes__Item *Attributes__TypeTag_x, Data__Region *Attributes__TypeTag_region) {
  register int i0, i1;
  i0 = (int)type + 40;
  i0 = *(unsigned int*)i0;
  i0 = (i0 & ((unsigned int)1 << 3)) != 0;
  if (!(i0)) goto l0;
  i0 = *(int*)(int)Attributes__TypeTag_x;
  Error__Err((int)i0, (short int)281);
l0:
  i0 = (int)*Attributes__TypeTag_region;
  i1 = *(int*)(int)Attributes__TypeTag_x;
  i0 = (int)Data__RegionDesc_CreateAdrInstr((Data__Region)i0, (Data__Usable)(int)type, (int)i1);
  return (void*)i0;
}

Data__Usable Attributes__TypeTag(Data__Region region, Attributes__Item *x, _Type x__tag, short int base) {
  register int i0, i1, i2, i3, i4;
  i0 = (int)region;
  i3 = (int)x + 32;
  i2 = (int)*(void**)i3;
  i1 = i2 == 0;
  if (i1) goto l0;
  i1 = base < 0;
  if (i1) goto l4;
l0:
  i2 = (int)x + 8;
  i1 = (int)*(void**)i2;
  i2 = i1 + 20;
  i2 = *(signed char*)i2;
  i2 = i2 == 27;
  if (i2) goto l1;
  i2 = i1;
  goto l2;
l1:
  i2 = i1 + 24;
  i2 = (int)*(void**)i2;
l2:
  i1 = base <= 0;
  if (i1) goto l3;
  i3 = i2 + 24;
  i3 = (int)*(void**)i3;
  i1 = i3 == 0;
  if (i1) goto l3;
  region = (void*)i0;
  region = (void*)i0;
  i4 = (int)Attributes__TypeTag_TypeDescrAdr((Data__Struct)i3, &*x, (Data__Region *)&region);
  goto l9;
l3:
  region = (void*)i0;
  region = (void*)i0;
  i4 = (int)Attributes__TypeTag_TypeDescrAdr((Data__Struct)i2, &*x, (Data__Region *)&region);
  goto l9;
l4:
  i1 = *(int*)(i2-4);
  i1 = _type_test(i1, &Data__ObjectDesc_td.td, 4);
  if (!(i1)) goto l5;
  i4 = i2 + 28;
  i4 = *(signed char*)i4;
  i4 = i4 == 4;
  if (i4) goto l8;
l5:
  i1 = (int)x + 8;
  i1 = (int)*(void**)i1;
  i2 = i1 + 40;
  i2 = *(unsigned int*)i2;
  i2 = (i2 & ((unsigned int)1 << 5)) != 0;
  if (i2) goto l7;
  i2 = *(int*)(int)x;
  i4 = (int)Data__RegionDesc_CreateInstruction((Data__Region)i0, (short int)10, (Data__Struct)0, (int)i2);
  i2 = (int)StdPragmas__derefCheck;
  i2 += 8;
  i2 = *(unsigned char*)i2;
  if (!(i2)) goto l6;
  i2 = i4 + 48;
  i1 = *(unsigned int*)i2;
  i1 = i1 | ((unsigned int)1 << 3);
  *(unsigned int*)i2 = i1;
l6:
  i2 = (int)*(void**)i3;
  Data__InstructionDesc_Operand((Data__Instruction)i4, (Data__Usable)i2);
  i2 = *(int*)(int)x;
  Attributes__SetOpndPos((Data__Instruction)i4, (int)i2);
  goto l9;
l7:
  i1 += 24;
  i1 = (int)*(void**)i1;
  region = (void*)i0;
  region = (void*)i0;
  i4 = (int)Attributes__TypeTag_TypeDescrAdr((Data__Struct)i1, &*x, (Data__Region *)&region);
  goto l9;
l8:
  i4 = (int)Attributes__FindAddEnterResult((Data__Region)i0, (Data__Addressable)i2, (short int)-1, (Data__Struct)0);
l9:
  return (void*)i4;
}

unsigned char Attributes__HasLengthInfo(Attributes__Item *array, _Type array__tag, short int dim) {
  register int i0, i1, i2, i3, i4;
  i0 = (int)array + 8;
  i3 = (int)*(void**)i0;
  i0 = SymbolTable__TypeInGroup((Data__Struct)i3, (signed char)40);
  if (i0) goto l7;
  i2 = (int)array + 42;
  i2 = *(short int*)i2;
  i2 = dim + i2;
  i2 = i2 != 0;
  if (i2) goto l0;
  i2 = (int)array + 4;
  i2 = (int)*(void**)i2;
  i1 = i2 == 0;
  if (i1) goto l0;
  i2 += 64;
  i1 = *(unsigned int*)i2;
  i2 = (i1 & ((unsigned int)1 << 26)) != 0;
  if (!(i2)) goto l0;
  i1 = (i1 & ((unsigned int)1 << 5)) != 0;
  if (i1) goto l6;
l0:
  i4 = dim != 0;
  if (!(i4)) goto l2;
  i4 = SymbolTable__TypeInGroup((Data__Struct)i3, (signed char)42);
  if (!(i4)) goto l2;
  i2 = i3;
  i1 = dim;
l1:
  i1--;
  i0 = i1 == 0;
  i2 += 24;
  i2 = (int)*(void**)i2;
  if (i0) goto l3;
  i0 = SymbolTable__TypeInGroup((Data__Struct)i2, (signed char)42);
  if (i0) goto l1;
  goto l3;
l2:
  i2 = i3;
l3:
  i4 = i2 + 20;
  i4 = *(signed char*)i4;
  i4 = i4 != 30;
  if (i4) goto l4;
  i2 += 40;
  i2 = *(unsigned int*)i2;
  i2 = (i2 & ((unsigned int)1 << 4)) != 0;
  if (i2) goto l5;
l4:
  i4 = 0;
  goto l8;
l5:
  i4 = 1;
  goto l8;
l6:
  i4 = 1;
  goto l8;
l7:
  i4 = 0;
l8:
  if (i4) goto l9;
  i0 = 1;
  goto l10;
l9:
  i0 = 0;
l10:
  return (unsigned char)i0;
}

Data__Const Attributes__ArrayLength_GetConst(int value, unsigned char *Attributes__ArrayLength_adaptType) {
  register int i0;
  i0 = *Attributes__ArrayLength_adaptType;
  if (i0) goto l0;
  i0 = (int)Data__struct + 24;
  i0 = (int)*(void**)i0;
  i0 = (int)Data__GetIntConst((int)value, (Data__Struct)i0);
  goto l1;
l0:
  i0 = (int)StdTypes__IntType((int)value);
  i0 = (int)Data__GetIntConst((int)value, (Data__Struct)i0);
l1:
  return (void*)i0;
}

void Attributes__ArrayLength(Data__Region region, Attributes__Item *array, _Type array__tag, short int dim, int pos, unsigned char adaptType, Attributes__Item *result, _Type result__tag) {
  register int i0, i1, i2, i3, i4;
  i0 = Attributes__HasLengthInfo((Attributes__Item *)(int)array, array__tag, (short int)dim);
  if (i0) goto l0;
  i4 = *(int*)(int)array;
  Error__Err((int)i4, (short int)280);
  i4 = (int)Attributes__ArrayLength_GetConst((int)1, &adaptType);
  goto l8;
l0:
  i3 = (int)array + 8;
  i0 = (int)*(void**)i3;
  i3 = SymbolTable__TypeInGroup((Data__Struct)i0, (signed char)40);
  if (i3) goto l7;
  i1 = dim == 0;
  if (i1) goto l2;
  i1 = SymbolTable__TypeInGroup((Data__Struct)i0, (signed char)42);
  if (!(i1)) goto l2;
  i3 = i0;
  i2 = dim;
l1:
  i2--;
  i4 = i2 == 0;
  i3 += 24;
  i3 = (int)*(void**)i3;
  if (i4) goto l3;
  i4 = SymbolTable__TypeInGroup((Data__Struct)i3, (signed char)42);
  if (i4) goto l1;
  goto l3;
l2:
  i3 = i0;
l3:
  i1 = SymbolTable__TypeInGroup((Data__Struct)i3, (signed char)42);
  if (i1) goto l4;
  i4 = (int)Attributes__ArrayLength_GetConst((int)1, &adaptType);
  goto l8;
l4:
  i2 = i3 + 20;
  i2 = *(signed char*)i2;
  i2 = i2 == 29;
  if (i2) goto l6;
  i1 = (int)array + 36;
  i2 = (int)*(void**)i1;
  i1 = *(int*)(i2-4);
  i1 = _type_test(i1, &Data__ObjectDesc_td.td, 4);
  if (i1) goto l5;
  i3 = (int)array + 42;
  i3 = *(short int*)i3;
  i3 = dim + i3;
  i2 = (int)Data__struct + 24;
  i1 = (int)array + 32;
  i4 = (int)Data__struct + 20;
  i2 = (int)*(void**)i2;
  i1 = (int)*(void**)i1;
  i4 = (int)*(void**)i4;
  i3 = (int)Data__GetIntConst((int)i3, (Data__Struct)i4);
  i4 = (int)Data__RegionDesc_CreateDyadicOp((Data__Region)(int)region, (short int)9, (Data__Struct)i2, (Data__Usable)i1, (Data__Usable)i3, (int)pos);
  i3 = (int)StdPragmas__derefCheck;
  i3 += 8;
  i3 = *(unsigned char*)i3;
  if (!(i3)) goto l8;
  i3 = i4 + 48;
  i2 = *(unsigned int*)i3;
  i2 = i2 | ((unsigned int)1 << 3);
  *(unsigned int*)i3 = i2;
  goto l8;
l5:
  i4 = (int)array + 42;
  i2 = *(short int*)i4;
  i1 = (int)array + 32;
  i4 = (int)Data__struct + 24;
  i2 = dim + i2;
  i1 = (int)*(void**)i1;
  i4 = (int)*(void**)i4;
  i4 = (int)Attributes__FindAddEnterResult((Data__Region)(int)region, (Data__Addressable)i1, (short int)i2, (Data__Struct)i4);
  goto l8;
l6:
  i4 = i3 + 32;
  i4 = *(int*)i4;
  i4 = (int)Attributes__ArrayLength_GetConst((int)i4, &adaptType);
  goto l8;
l7:
  i4 = (int)array + 12;
  i4 = (int)*(void**)i4;
  i4 += 24;
  i4 = *(int*)i4;
  i4++;
  i4 = (int)Attributes__ArrayLength_GetConst((int)i4, &adaptType);
l8:
  Attributes__CreateItem((Attributes__Item *)(int)result, result__tag, (Data__Usable)i4, (int)pos);
}

Data__Usable Attributes__SizeOfItem_Mult(Data__Usable opnd0, Data__Usable opnd1, Data__Region *Attributes__SizeOfItem_region, int *Attributes__SizeOfItem_pos) {
  register int i0, i1, i2;
  i0 = (int)Data__struct + 24;
  i2 = (int)*(void**)i0;
  i0 = (int)*Attributes__SizeOfItem_region;
  i1 = *Attributes__SizeOfItem_pos;
  i0 = (int)Data__RegionDesc_CreateDyadicOp((Data__Region)i0, (short int)164, (Data__Struct)i2, (Data__Usable)(int)opnd0, (Data__Usable)(int)opnd1, (int)i1);
  return (void*)i0;
}

void Attributes__SizeOfItem(Data__Region region, Attributes__Item *x, _Type x__tag, short int dim, int pos, Attributes__Item *size, _Type size__tag) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  i0 = (int)x + 8;
  i1 = (int)*(void**)i0;
  i0 = dim != 0;
  if (i0) goto l0;
  i7 = i1;
  goto l2;
l0:
  i7 = i1;
  i2 = 0;
l1:
  i2++;
  i7 += 24;
  i7 = (int)*(void**)i7;
  i0 = dim != i2;
  if (i0) goto l1;
l2:
  i0 = i7 + 48;
  i0 = *(int*)i0;
  i1 = i0 >= 0;
  if (i1) goto l9;
  i6 = i7 + 20;
  i0 = *(signed char*)i6;
  i6 = i0 == 18;
  if (i6) goto l8;
  i0 = i0 == 19;
  if (i0) goto l7;
  i8 = i7 + 24;
  Attributes__ArrayLength((Data__Region)(int)region, (Attributes__Item *)(int)x, x__tag, (short int)dim, (int)pos, (unsigned char)0, (Attributes__Item *)(int)size, size__tag);
  i3 = (int)*(void**)i8;
  i7 = i3 + 20;
  i4 = (int)size + 16;
  i7 = *(signed char*)i7;
  i2 = (int)*(void**)i4;
  i7 = i7 == 30;
  i5 = dim + 1;
  if (i7) goto l3;
  i8 = pos;
  i7 = (int)region;
  i0 = i2;
  i1 = i3;
  goto l6;
l3:
  i1 = i3;
  i0 = i2;
  i8 = (int)region;
  i7 = pos;
l4:
  Attributes__ArrayLength((Data__Region)i8, (Attributes__Item *)(int)x, x__tag, (short int)i5, (int)i7, (unsigned char)0, (Attributes__Item *)(int)size, size__tag);
  i6 = (int)*(void**)i4;
  region = (void*)i8;
  pos = (int)i7;
  pos = (int)i7;
  region = (void*)i8;
  i0 = (int)Attributes__SizeOfItem_Mult((Data__Usable)i0, (Data__Usable)i6, (Data__Region *)&region, &pos);
  i7 = i1 + 24;
  i1 = (int)*(void**)i7;
  i7 = i1 + 20;
  i7 = *(signed char*)i7;
  i7 = i7 != 30;
  i5++;
  if (i7) goto l5;
  i8 = (int)region;
  i7 = pos;
  goto l4;
l5:
  i8 = pos;
  i7 = (int)region;
l6:
  i6 = (int)Data__struct + 24;
  i5 = i1 + 48;
  i6 = (int)*(void**)i6;
  i5 = *(int*)i5;
  i6 = (int)Data__GetIntConst((int)i5, (Data__Struct)i6);
  region = (void*)i7;
  pos = (int)i8;
  pos = (int)i8;
  region = (void*)i7;
  i8 = (int)Attributes__SizeOfItem_Mult((Data__Usable)i0, (Data__Usable)i6, (Data__Region *)&region, &pos);
  goto l10;
l7:
  i8 = (int)x + 12;
  i0 = (int)*(void**)i8;
  i8 = (int)Data__struct + 12;
  i8 = (int)*(void**)i8;
  i0 += 24;
  i8 += 48;
  i0 = *(int*)i0;
  i8 = *(int*)i8;
  i0++;
  i0 = i8 * i0;
  i8 = (int)Data__struct + 24;
  i8 = (int)*(void**)i8;
  i8 = (int)Data__GetIntConst((int)i0, (Data__Struct)i8);
  goto l10;
l8:
  i8 = (int)x + 12;
  i8 = (int)*(void**)i8;
  i8 += 24;
  i8 = *(int*)i8;
  i6 = (int)Data__struct + 24;
  i8++;
  i6 = (int)*(void**)i6;
  i8 = (int)Data__GetIntConst((int)i8, (Data__Struct)i6);
  goto l10;
l9:
  i8 = (int)Data__struct + 24;
  i8 = (int)*(void**)i8;
  i8 = (int)Data__GetIntConst((int)i0, (Data__Struct)i8);
l10:
  i0 = *(int*)(int)x;
  Attributes__CreateItem((Attributes__Item *)(int)size, size__tag, (Data__Usable)i8, (int)i0);
}

short int Attributes__GetNonParamOpnd_OpndCount(Data__Object formal) {
  register int i0, i1, i2;
  i0 = StdTypes__PassPerReference((Data__Object)(int)formal, (unsigned char)1);
  if (i0) goto l0;
  i0 = 1;
  goto l1;
l0:
  i0 = 2;
l1:
  i1 = (int)formal + 28;
  i1 = *(signed char*)i1;
  i1 = i1 != 4;
  if (i1) goto l2;
  i2 = (int)formal + 24;
  i2 = (int)*(void**)i2;
  i2 += 20;
  i2 = *(signed char*)i2;
  i2 = i2 == 31;
  if (i2) goto l7;
l2:
  i1 = (int)formal + 24;
  i1 = (int)*(void**)i1;
  i2 = i1 + 20;
  i2 = *(signed char*)i2;
  i2 = i2 != 30;
  if (i2) goto l3;
  i2 = i1 + 24;
  i2 = (int)*(void**)i2;
  i2 += 20;
  i2 = *(signed char*)i2;
  i2 = i2 == 16;
  if (i2) goto l5;
l3:
  i2 = (int)formal + 64;
  i2 = *(unsigned int*)i2;
  i2 = (i2 & ((unsigned int)1 << 5)) != 0;
  if (i2) goto l4;
  i1 = Data__StructDesc_OpenDimensions((Data__Struct)i1);
  i2 = i1 + i0;
  goto l9;
l4:
  i2 = i0;
  goto l9;
l5:
  i2 = (int)formal + 64;
  i2 = *(unsigned int*)i2;
  i2 = (i2 & ((unsigned int)1 << 5)) != 0;
  if (i2) goto l6;
  i2 = i0 + 1;
  goto l9;
l6:
  i2 = i0;
  goto l9;
l7:
  i2 = (int)formal + 64;
  i2 = *(unsigned int*)i2;
  i2 = (i2 & ((unsigned int)1 << 6)) != 0;
  if (i2) goto l8;
  i2 = i0 + 1;
  goto l9;
l8:
  i2 = i0;
l9:
  return (short int)i2;
}

Data__Opnd Attributes__GetNonParamOpnd_SkipOpnds(short int n, Data__Opnd opndList) {
  register int i0, i1, i2;
  i0 = n != 0;
  if (i0) goto l0;
  i2 = (int)opndList;
  goto l2;
l0:
  i0 = n;
  i2 = (int)opndList;
l1:
  i0--;
  i2 += 8;
  i2 = (int)*(void**)i2;
  i1 = i0 != 0;
  if (i1) goto l1;
l2:
  return (void*)i2;
}

Data__Opnd Attributes__GetNonParamOpnd(Data__Instruction call) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  i1 = (int)Data__InstructionDesc_NthOperand((Data__Instruction)(int)call, (short int)3);
  i0 = (int)Data__InstructionDesc_GetReceiver((Data__Instruction)(int)call);
  i2 = i0 != 0;
  if (i2) goto l0;
  i7 = i1;
  goto l1;
l0:
  i0 = Attributes__GetNonParamOpnd_OpndCount((Data__Object)i0);
  i7 = (int)Attributes__GetNonParamOpnd_SkipOpnds((short int)i0, (Data__Opnd)i1);
l1:
  i0 = (int)call + 28;
  i0 = (int)*(void**)i0;
  i0 += 8;
  i0 = (int)*(void**)i0;
  i0 = (int)*(void**)i0;
  i0 += 28;
  i6 = (int)*(void**)i0;
  i0 = i6 != 0;
  if (i0) goto l2;
  i8 = i7;
  goto l9;
l2:
  i8 = i7;
l3:
  i0 = i6 + 28;
  i0 = *(signed char*)i0;
  i0 = i0 == 9;
  if (i0) goto l4;
  i0 = Attributes__GetNonParamOpnd_OpndCount((Data__Object)i6);
  i0 = (int)Attributes__GetNonParamOpnd_SkipOpnds((short int)i0, (Data__Opnd)i8);
  i8 = i0;
  goto l8;
l4:
  i4 = i8 != 0;
  if (!(i4)) goto l6;
  i4 = (int)SymbolTable__store;
  i3 = (int)*(void**)i8;
  i0 = i3 == i4;
  if (i0) goto l6;
  i2 = (int)SymbolTable__mem;
  i1 = i3 == i2;
  if (i1) goto l6;
  i5 = i8;
l5:
  i0 = i5 + 8;
  i5 = (int)*(void**)i0;
  i0 = i5 == 0;
  if (i0) goto l7;
  i3 = (int)*(void**)i5;
  i0 = i3 == i4;
  if (i0) goto l7;
  i3 = i3 != i2;
  if (i3) goto l5;
  goto l7;
l6:
  i5 = i8;
l7:
  i8 = i5;
l8:
  i0 = i6 + 36;
  i6 = (int)*(void**)i0;
  i0 = i6 != 0;
  if (i0) goto l3;
l9:
  return (void*)i8;
}

unsigned char Attributes__PartOfStore(Data__Object proc, Data__Location loc) {
  register int i0, i1, i2, i3;
  i0 = (int)loc == 0;
  if (i0) goto l2;
  i2 = (int)loc + 4;
  i2 = *(short int*)i2;
  i1 = i2 != -3;
  if (i1) goto l2;
  i0 = (int)*(void**)(int)loc;
  i3 = (int)SymbolTable__store;
  i3 = i0 == i3;
  if (i3) goto l0;
  i3 = (int)SymbolTable__mem;
  i3 = i0 == i3;
  if (i3) goto l0;
  i3 = *(int*)(i0-4);
  i2 = _type_test(i3, &Data__StructDesc_td.td, 4);
  if (i2) goto l1;
  i3 = _type_test(i3, &Data__ObjectDesc_td.td, 4);
  if (!(i3)) goto l0;
  i0 += 40;
  i0 = (int)*(void**)i0;
  i0 = (int)proc != i0;
  if (i0) goto l1;
l0:
  i3 = 0;
  goto l3;
l1:
  i3 = 1;
  goto l3;
l2:
  i3 = 0;
l3:
  return (unsigned char)i3;
}

void Attributes__ContainsRuntimeCheck(Data__Region region) {
  register int i0, i1, i2;
  i0 = (int)region + 32;
  i0 = (int)*(void**)i0;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)region;
  goto l2;
l0:
  i1 = (int)region;
l1:
  i1 += 32;
  i1 = (int)*(void**)i1;
  i0 = i1 + 32;
  i0 = (int)*(void**)i0;
  i0 = i0 != 0;
  if (i0) goto l1;
l2:
  i0 = *(int*)(i1-4);
  i0 = _type_test(i0, &Data__GlobalRegionDesc_td.td, 7);
  if (!(i0)) goto l3;
  i1 += 84;
  i2 = (int)*(void**)i1;
  i1 = i2 == 0;
  if (i1) goto l3;
  i0 = i2 + 48;
  i1 = *(unsigned int*)i0;
  i1 = i1 | ((unsigned int)1 << 0);
  *(unsigned int*)i0 = i1;
l3:
  ;
}

void Attributes__CleanupGreg_ScanUpdates(Data__Object obj) {
  register int i0, i1, i2;
  i0 = (int)obj == 0;
  if (i0) goto l1;
  i1 = (int)obj + 32;
  i1 = (int)*(void**)i1;
  Attributes__CleanupGreg_ScanUpdates((Data__Object)i1);
  i1 = (int)obj + 36;
  i1 = (int)*(void**)i1;
  Attributes__CleanupGreg_ScanUpdates((Data__Object)i1);
  i1 = (int)obj + 64;
  i1 = *(unsigned int*)i1;
  i1 = (i1 & ((unsigned int)1 << 26)) != 0;
  if (!(i1)) goto l1;
  i0 = (int)obj + 52;
  i1 = (int)*(void**)i0;
  i0 = i1 + 12;
  i0 = (int)*(void**)i0;
  i2 = i1 == i0;
  if (i2) goto l1;
  i2 = *(int*)(i0-4);
  i2 = _type_test(i2, &Data__ResultDesc_td.td, 3);
  if (!(i2)) goto l0;
  i0 += 16;
  i0 = (int)*(void**)i0;
  i0 += 44;
  i0 = *(short int*)i0;
  i0 = i0 == 1;
  if (i0) goto l1;
l0:
  i2 = i1 + 64;
  i0 = *(unsigned int*)i2;
  i0 = i0 | ((unsigned int)1 << 19);
  *(unsigned int*)i2 = i0;
l1:
  ;
}

void Attributes__CleanupGreg_RemoveNoopGateHints(Data__Region r) {
  register int i0, i1, i2;
  i0 = (int)r + 56;
  i1 = (int)*(void**)i0;
  i0 = i1 == 0;
  if (i0) goto l3;
l0:
  i0 = i1 + 36;
  i0 = (int)*(void**)i0;
  i2 = *(int*)(i1-4);
  i2 = _type_test(i2, &Data__RegionDesc_td.td, 5);
  if (i2) goto l1;
  i2 = i1 + 44;
  i2 = *(short int*)i2;
  i2 = i2 != 593;
  if (i2) goto l2;
  Data__InstructionDesc_Delete((Data__Instruction)i1);
  goto l2;
l1:
  Attributes__CleanupGreg_RemoveNoopGateHints((Data__Region)i1);
l2:
  i1 = i0 != 0;
  if (!(i1)) goto l3;
  i1 = i0;
  goto l0;
l3:
  ;
}

void Attributes__CleanupGreg(Data__GlobalRegion greg) {
  register int i0, i1, i2, i3, i4, i5, i6;
  Attributes__CleanupGreg_RemoveNoopGateHints((Data__Region)(int)greg);
  i0 = (int)Data__RegionDesc_CreateInstruction((Data__Region)(int)greg, (short int)7, (Data__Struct)0, (int)-1);
  i1 = i0 + 48;
  i3 = (int)SymbolTable__store;
  i2 = *(unsigned int*)i1;
  i3 += 12;
  i2 = i2 | ((unsigned int)1 << 0);
  *(unsigned int*)i1 = i2;
  i1 = (int)*(void**)i3;
  Data__InstructionDesc_Operand((Data__Instruction)i0, (Data__Usable)i1);
  i5 = (int)Data__RegionDesc_ExitInstr((Data__Region)(int)greg);
  i3 = i5 + 28;
  i4 = (int)*(void**)i3;
  i0 = i4 == 0;
  if (i0) goto l4;
  i0 = i5 + 52;
l0:
  i1 = (int)*(void**)i4;
  i6 = *(int*)(i1-4);
  i6 = _type_test(i6, &Data__ObjectDesc_td.td, 4);
  if (!(i6)) goto l3;
  i2 = i1 + 20;
  i2 = (int)*(void**)i2;
  i2 = strcmp((const char*) i2, (const char*) (int)_c2) == 0;
  if (i2) goto l3;
  i6 = i1 + 28;
  i6 = *(signed char*)i6;
  i6 = i6 == 4;
  if (i6) goto l1;
  i6 = i1 + 24;
  i2 = *(int*)i0;
  i6 = (int)*(void**)i6;
  i2 = (int)Data__RegionDesc_CreateInstruction((Data__Region)(int)greg, (short int)35, (Data__Struct)i6, (int)i2);
  goto l2;
l1:
  i6 = i1 + 24;
  i2 = *(int*)i0;
  i6 = (int)*(void**)i6;
  i2 = (int)Data__RegionDesc_CreateInstruction((Data__Region)(int)greg, (short int)36, (Data__Struct)i6, (int)i2);
l2:
  Data__InstructionDesc_Operand((Data__Instruction)i2, (Data__Usable)i1);
  i6 = *(int*)i0;
  i1 = (int)Attributes__Address((Data__Region)(int)greg, (Data__Addressable)i1, (int)i6);
  Data__InstructionDesc_Operand((Data__Instruction)i2, (Data__Usable)i1);
  i1 = (int)SymbolTable__store;
  i1 += 12;
  i1 = (int)*(void**)i1;
  Data__InstructionDesc_Operand((Data__Instruction)i2, (Data__Usable)i1);
  Data__OpndDesc_ReplaceOperand((Data__Opnd)i4, (Data__Usable)i2);
l3:
  i6 = i4 + 8;
  i4 = (int)*(void**)i6;
  i6 = i4 != 0;
  if (i6) goto l0;
l4:
  i0 = (int)SymbolTable__mem;
  i1 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i5, (Data__Addressable)i0, (short int)-3);
  i0 = i1 == 0;
  if (i0) goto l5;
  Data__OpndDesc_MoveOperandToEnd((Data__Opnd)i1);
l5:
  i0 = (int)greg + 80;
  i2 = (int)*(void**)i0;
  i1 = i2 == 0;
  if (i1) goto l6;
  i2 += 44;
  i2 = (int)*(void**)i2;
  Attributes__CleanupGreg_ScanUpdates((Data__Object)i2);
l6:
  i2 = (int)*(void**)i3;
  i1 = i2 == 0;
  if (i1) goto l10;
l7:
  i1 = i2 + 16;
  i1 = (int)*(void**)i1;
  i3 = (int)*(void**)i1;
  i1 = *(int*)(i3-4);
  i1 = _type_test(i1, &Data__ObjectDesc_td.td, 4);
  if (!(i1)) goto l8;
  i1 = i3 + 20;
  i1 = (int)*(void**)i1;
  i1 = strcmp((const char*) i1, (const char*) (int)_c2) == 0;
  if (i1) goto l9;
l8:
  i1 = i3 + 12;
  *(void**)i1 = (void*)i3;
l9:
  i1 = i2 + 8;
  i2 = (int)*(void**)i1;
  i1 = i2 != 0;
  if (i1) goto l7;
l10:
  i3 = (int)Data__RegionDesc_EnterInstr((Data__Region)(int)greg);
  i1 = i3 + 12;
  i4 = (int)*(void**)i1;
  i1 = i4 == 0;
  if (i1) goto l14;
l11:
  i5 = i4 + 20;
  i2 = (int)*(void**)i5;
  i5 = i2 + 4;
  i5 = *(short int*)i5;
  i5 = i5 != -3;
  if (i5) goto l13;
  i1 = (int)*(void**)i2;
  i2 = *(int*)(i1-4);
  i2 = _type_test(i2, &Data__ObjectDesc_td.td, 4);
  if (!(i2)) goto l12;
  i5 = i1 + 40;
  i2 = (int)*(void**)i0;
  i5 = (int)*(void**)i5;
  i2 = i5 == i2;
  if (i2) goto l13;
l12:
  i2 = i1 + 12;
  *(void**)i2 = (void*)i1;
l13:
  i5 = i4 + 12;
  i4 = (int)*(void**)i5;
  i5 = i4 != 0;
  if (i5) goto l11;
l14:
  i0 = (int)SymbolTable__mem;
  i1 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i3, (Data__Addressable)i0, (short int)-3);
  i0 = i1 == 0;
  if (i0) goto l15;
  Data__ResultDesc_MoveResultToEnd((Data__Result)i1);
l15:
  i0 = (int)Data__RegionDesc_ExitInstr((Data__Region)(int)greg);
  i2 = i0 + 52;
  i1 = Scanner__currSymPos;
  *(int*)i2 = i1;
}

void Attributes_init(void) {
  _mid = _register_module(&Attributes_md.md, &Attributes__ExitInfo_td.td);
}
