/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "BinaryRider.d"

static _ModId _mid;

Msg__Msg BinaryRider__GetError(int code) {
  register int i0;
  i0 = (int)BinaryRider__errorContext;
  i0 = (int)Msg__New((Msg__Context)i0, (int)code);
  return (void*)i0;
}

int BinaryRider__ReaderDesc_Pos(BinaryRider__Reader r) {
  register int i0, i1;
  i0 = (int)r + 8;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[0];
  i0 = ((_TBP_Channel__ReaderDesc_Pos)i1)((Channel__Reader)i0);
  return (int)i0;
}

void BinaryRider__ReaderDesc_SetPos(BinaryRider__Reader r, int newPos) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)r + 8;
  i2 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((_TBP_Channel__ReaderDesc_SetPos)i0)((Channel__Reader)i2, (int)newPos);
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)r = (void*)i1;
l0:
  ;
}

void BinaryRider__ReaderDesc_ClearError(BinaryRider__Reader r) {
  register int i0, i1;
  i0 = (int)r + 8;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[5];
  ((_TBP_Channel__ReaderDesc_ClearError)i1)((Channel__Reader)i0);
  *(void**)(int)r = (void*)0;
}

int BinaryRider__ReaderDesc_Available(BinaryRider__Reader r) {
  register int i0, i1;
  i0 = (int)r + 8;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[1];
  i0 = ((_TBP_Channel__ReaderDesc_Available)i1)((Channel__Reader)i0);
  return (int)i0;
}

void BinaryRider__ReaderDesc_ReadBytes(BinaryRider__Reader r, unsigned char* x, int x_0d, int start, int n) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)r + 8;
  i2 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_Channel__ReaderDesc_ReadBytes)i0)((Channel__Reader)i2, (unsigned char*)(int)x, x_0d, (int)start, (int)n);
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)r = (void*)i1;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadBytesOrdered(BinaryRider__Reader r, unsigned char* x, int x_0d) {
  register int i0, i1, i2, i3, i4, i5, i6;
  i0 = (int)r + 4;
  i5 = *(signed char*)i0;
  i0 = i5 == 0;
  if (i0) goto l1;
  i4 = BinaryRider__systemByteOrder;
  i1 = i5 == i4;
  if (i1) goto l1;
  i0 = x_0d - 1;
  i2 = i0 < 0;
  if (i2) goto l2;
  i4 = (int)r + 8;
l0:
  i2 = (int)*(void**)i4;
  i6 = (int)x + i0;
  i3 = *(int*)(i2-4);
  i5 = i0 + -1;
  i0 = *(unsigned char*)i6;
  i3 = (int)((_Type)i3)->tbprocs[3];
  ((_TBP_Channel__ReaderDesc_ReadByte)i3)((Channel__Reader)i2, (unsigned char *)i6);
  i2 = i5 < 0;
  if (i2) goto l2;
  i0 = i5;
  goto l0;
l1:
  i1 = (int)r + 8;
  i1 = (int)*(void**)i1;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_Channel__ReaderDesc_ReadBytes)i0)((Channel__Reader)i1, (unsigned char*)(int)x, x_0d, (int)0, (int)x_0d);
l2:
  ;
}

void BinaryRider__ReaderDesc_ReadBool(BinaryRider__Reader r, unsigned char *bool_) {
  register int i0, i1, i2;
  signed char byte;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l3;
  i1 = (int)r + 8;
  i2 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[3];
  ((_TBP_Channel__ReaderDesc_ReadByte)i0)((Channel__Reader)i2, (unsigned char *)(int)&byte);
  i1 = (int)*(void**)i1;
  i1 += 4;
  i2 = (int)*(void**)i1;
  i1 = byte != 0;
  i0 = i2 != 0;
  if (i0) goto l0;
  if (!(i1)) goto l0;
  i0 = byte != 1;
  if (i0) goto l1;
l0:
  *(void**)(int)r = (void*)i2;
  goto l2;
l1:
  i0 = (int)BinaryRider__GetError((int)8);
  *(void**)(int)r = (void*)i0;
l2:
  *bool_ = i1;
l3:
  ;
}

void BinaryRider__ReaderDesc_ReadChar(BinaryRider__Reader r, unsigned char *ch) {
  register int i0, i1, i2, i3;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i2 = (int)r + 8;
  i1 = (int)*(void**)i2;
  i3 = *(int*)(i1-4);
  i0 = (int)((_Type)i3)->tbprocs[3];
  i3 = *ch;
  ((_TBP_Channel__ReaderDesc_ReadByte)i0)((Channel__Reader)i1, (unsigned char *)(int)ch);
  i2 = (int)*(void**)i2;
  i2 += 4;
  i2 = (int)*(void**)i2;
  *(void**)(int)r = (void*)i2;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadLChar(BinaryRider__Reader r, unsigned short int *ch) {
  register int i0, i1;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = *(int*)((int)r-4);
  i0 = (int)((_Type)i1)->tbprocs[5];
  i1 = *ch;
  ((_TBP_BinaryRider__ReaderDesc_ReadBytesOrdered)i0)((BinaryRider__Reader)(int)r, (unsigned char*)(int)ch, 2);
  i1 = (int)r + 8;
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)r = (void*)i1;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadString(BinaryRider__Reader r, unsigned char* s, int s_0d) {
  register int i0, i1, i2, i3, i4, i5;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l4;
  i0 = s_0d - 1;
  i5 = (int)r + 8;
  i4 = *(int*)((int)r-4);
  i1 = (int)((_Type)i4)->tbprocs[7];
  i3 = -1;
l0:
  i3++;
  i4 = (int)s + i3;
  i2 = *(unsigned char*)i4;
  ((_TBP_BinaryRider__ReaderDesc_ReadChar)i1)((BinaryRider__Reader)(int)r, (unsigned char *)i4);
  i2 = *(unsigned char*)i4;
  i2 = i2 == 0;
  if (i2) goto l1;
  i2 = (int)*(void**)i5;
  i2 += 4;
  i2 = (int)*(void**)i2;
  i2 = i2 != 0;
  if (i2) goto l1;
  i2 = i0 != i3;
  if (i2) goto l0;
l1:
  i1 = (int)*(void**)i5;
  i2 = i1 + 4;
  i5 = (int)*(void**)i2;
  i4 = i5 != 0;
  if (i4) goto l2;
  i0 = (int)s + i3;
  i4 = *(unsigned char*)i0;
  i4 = i4 != 0;
  if (i4) goto l3;
l2:
  *(void**)(int)r = (void*)i5;
  goto l4;
l3:
  i4 = (int)BinaryRider__GetError((int)8);
  *(unsigned char*)i0 = 0;
  *(void**)i2 = (void*)i4;
l4:
  ;
}

void BinaryRider__ReaderDesc_ReadLString(BinaryRider__Reader r, unsigned short int* s, int s_0d) {
  register int i0, i1, i2, i3, i4, i5;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l4;
  i0 = s_0d - 1;
  i5 = (int)r + 8;
  i4 = *(int*)((int)r-4);
  i1 = (int)((_Type)i4)->tbprocs[8];
  i3 = -1;
l0:
  i3++;
  i2 = (int)_ashl(i3, 1, (unsigned int));
  i4 = (int)s + i2;
  i2 = *(unsigned short int*)i4;
  ((_TBP_BinaryRider__ReaderDesc_ReadLChar)i1)((BinaryRider__Reader)(int)r, (unsigned short int *)i4);
  i2 = *(unsigned short int*)i4;
  i2 = i2 == 0;
  if (i2) goto l1;
  i2 = (int)*(void**)i5;
  i2 += 4;
  i2 = (int)*(void**)i2;
  i2 = i2 != 0;
  if (i2) goto l1;
  i2 = i0 != i3;
  if (i2) goto l0;
l1:
  i1 = (int)*(void**)i5;
  i2 = i1 + 4;
  i5 = (int)*(void**)i2;
  i4 = i5 != 0;
  if (i4) goto l2;
  i0 = (int)_ashl(i3, 1, (unsigned int));
  i0 = (int)s + i0;
  i4 = *(unsigned short int*)i0;
  i4 = i4 != 0;
  if (i4) goto l3;
l2:
  *(void**)(int)r = (void*)i5;
  goto l4;
l3:
  i4 = (int)BinaryRider__GetError((int)8);
  *(unsigned short int*)i0 = 0;
  *(void**)i2 = (void*)i4;
l4:
  ;
}

void BinaryRider__ReaderDesc_ReadSInt(BinaryRider__Reader r, signed char *sint) {
  register int i0, i1, i2, i3;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i2 = (int)r + 8;
  i1 = (int)*(void**)i2;
  i3 = *(int*)(i1-4);
  i0 = (int)((_Type)i3)->tbprocs[3];
  i3 = *sint;
  ((_TBP_Channel__ReaderDesc_ReadByte)i0)((Channel__Reader)i1, (unsigned char *)(int)sint);
  i2 = (int)*(void**)i2;
  i2 += 4;
  i2 = (int)*(void**)i2;
  *(void**)(int)r = (void*)i2;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadInt(BinaryRider__Reader r, short int *int_) {
  register int i0, i1;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = *(int*)((int)r-4);
  i0 = (int)((_Type)i1)->tbprocs[5];
  i1 = *int_;
  ((_TBP_BinaryRider__ReaderDesc_ReadBytesOrdered)i0)((BinaryRider__Reader)(int)r, (unsigned char*)(int)int_, 2);
  i1 = (int)r + 8;
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)r = (void*)i1;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadLInt(BinaryRider__Reader r, int *lint) {
  register int i0, i1;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = *(int*)((int)r-4);
  i0 = (int)((_Type)i1)->tbprocs[5];
  i1 = *lint;
  ((_TBP_BinaryRider__ReaderDesc_ReadBytesOrdered)i0)((BinaryRider__Reader)(int)r, (unsigned char*)(int)lint, 4);
  i1 = (int)r + 8;
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)r = (void*)i1;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadNum(BinaryRider__Reader r, int *num) {
  register int i0, i1, i2, i3, i4, i5;
  unsigned char x;
  i0 = *(int*)((int)r-4);
  i3 = (int)((_Type)i0)->tbprocs[7];
  ((_TBP_BinaryRider__ReaderDesc_ReadChar)i3)((BinaryRider__Reader)(int)r, (unsigned char *)(int)&x);
  i0 = (int)x >= 128;
  if (i0) goto l0;
  i5 = 0;
  i4 = 0;
  i0 = (int)x;
  goto l3;
l0:
  i1 = (int)x;
  i0 = 0;
  i5 = 0;
l1:
  i4 = i0 + 7;
  i2 = i1 - 128;
  i0 = (int)_ash(i2, i0, (unsigned int));
  i5 += i0;
  x = (unsigned char)i1;
  x = (unsigned char)i1;
  ((_TBP_BinaryRider__ReaderDesc_ReadChar)i3)((BinaryRider__Reader)(int)r, (unsigned char *)(int)&x);
  i0 = i4 >= 28;
  if (i0) goto l2;
  i0 = (int)x < 128;
  if (i0) goto l2;
  i1 = (int)x;
  i0 = i4;
  goto l1;
l2:
  i0 = (int)x;
l3:
  i1 = i0 >= 128;
  if (i1) goto l5;
  i1 = i4 != 28;
  if (i1) goto l4;
  i1 = i0 < 8;
  if (i1) goto l4;
  i1 = i0 >= 120;
  if (i1) goto l4;
  i1 = (int)r + 8;
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  i1 = i1 == 0;
  if (i1) goto l5;
l4:
  i0 = (int)_lshl(i0, 25, (unsigned int));
  i4 -= 25;
  i0 = (int)_ash(i0, i4, (unsigned int));
  i4 = (int)r + 8;
  i4 = (int)*(void**)i4;
  i0 = i5 + i0;
  *num = i0;
  i0 = i4 + 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)r = (void*)i0;
  goto l6;
l5:
  i0 = (int)BinaryRider__GetError((int)8);
  *(void**)(int)r = (void*)i0;
l6:
  ;
}

void BinaryRider__ReaderDesc_ReadReal(BinaryRider__Reader r, float *real) {
  register int i0;
  register float f0;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)r-4);
  i0 = (int)((_Type)i0)->tbprocs[5];
  f0 = *real;
  ((_TBP_BinaryRider__ReaderDesc_ReadBytesOrdered)i0)((BinaryRider__Reader)(int)r, (unsigned char*)(int)real, 4);
  i0 = (int)r + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)r = (void*)i0;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadLReal(BinaryRider__Reader r, double *lreal) {
  register int i0;
  register double d0;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)r-4);
  i0 = (int)((_Type)i0)->tbprocs[5];
  d0 = *lreal;
  ((_TBP_BinaryRider__ReaderDesc_ReadBytesOrdered)i0)((BinaryRider__Reader)(int)r, (unsigned char*)(int)lreal, 8);
  i0 = (int)r + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)r = (void*)i0;
l0:
  ;
}

void BinaryRider__ReaderDesc_ReadSet(BinaryRider__Reader r, unsigned int *s) {
  register int i0, i1;
  i0 = (int)*(void**)(int)r;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = *(int*)((int)r-4);
  i0 = (int)((_Type)i1)->tbprocs[5];
  i1 = *s;
  ((_TBP_BinaryRider__ReaderDesc_ReadBytesOrdered)i0)((BinaryRider__Reader)(int)r, (unsigned char*)(int)s, 4);
  i1 = (int)r + 8;
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)r = (void*)i1;
l0:
  ;
}

void BinaryRider__ReaderDesc_SetByteOrder(BinaryRider__Reader r, signed char order) {
  register int i0;
  i0 = (int)r + 4;
  *(signed char*)i0 = order;
}

int BinaryRider__WriterDesc_Pos(BinaryRider__Writer w) {
  register int i0, i1;
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[0];
  i0 = ((_TBP_Channel__WriterDesc_Pos)i1)((Channel__Writer)i0);
  return (int)i0;
}

void BinaryRider__WriterDesc_SetPos(BinaryRider__Writer w, int newPos) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)w + 8;
  i2 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[1];
  ((_TBP_Channel__WriterDesc_SetPos)i0)((Channel__Writer)i2, (int)newPos);
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)w = (void*)i1;
l0:
  ;
}

void BinaryRider__WriterDesc_ClearError(BinaryRider__Writer w) {
  register int i0, i1;
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[4];
  ((_TBP_Channel__WriterDesc_ClearError)i1)((Channel__Writer)i0);
  *(void**)(int)w = (void*)0;
}

void BinaryRider__WriterDesc_WriteBytes(BinaryRider__Writer w, unsigned char* x, int x_0d, int start, int n) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)w + 8;
  i2 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[3];
  ((_TBP_Channel__WriterDesc_WriteBytes)i0)((Channel__Writer)i2, (unsigned char*)(int)x, x_0d, (int)start, (int)n);
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)w = (void*)i1;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteBytesOrdered(BinaryRider__Writer w, unsigned char* x, int x_0d) {
  register int i0, i1, i2, i3, i4, i5, i6;
  i0 = (int)w + 4;
  i5 = *(signed char*)i0;
  i0 = i5 == 0;
  if (i0) goto l1;
  i4 = BinaryRider__systemByteOrder;
  i1 = i5 == i4;
  if (i1) goto l1;
  i0 = x_0d - 1;
  i2 = i0 < 0;
  if (i2) goto l2;
  i4 = (int)w + 8;
l0:
  i2 = (int)*(void**)i4;
  i5 = *(int*)(i2-4);
  i6 = (int)x + i0;
  i3 = i0 + -1;
  i5 = (int)((_Type)i5)->tbprocs[2];
  i0 = *(unsigned char*)i6;
  ((_TBP_Channel__WriterDesc_WriteByte)i5)((Channel__Writer)i2, (unsigned char)i0);
  i0 = i3 < 0;
  if (i0) goto l2;
  i0 = i3;
  goto l0;
l1:
  i1 = (int)w + 8;
  i1 = (int)*(void**)i1;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[3];
  ((_TBP_Channel__WriterDesc_WriteBytes)i0)((Channel__Writer)i1, (unsigned char*)(int)x, x_0d, (int)0, (int)x_0d);
l2:
  ;
}

void BinaryRider__WriterDesc_WriteBool(BinaryRider__Writer w, unsigned char bool_) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l2;
  i2 = (int)w + 8;
  if (bool_) goto l0;
  i1 = (int)*(void**)i2;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((_TBP_Channel__WriterDesc_WriteByte)i0)((Channel__Writer)i1, (unsigned char)0);
  goto l1;
l0:
  i1 = (int)*(void**)i2;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((_TBP_Channel__WriterDesc_WriteByte)i0)((Channel__Writer)i1, (unsigned char)1);
l1:
  i1 = (int)*(void**)i2;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)w = (void*)i1;
l2:
  ;
}

void BinaryRider__WriterDesc_WriteChar(BinaryRider__Writer w, unsigned char ch) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)w + 8;
  i2 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((_TBP_Channel__WriterDesc_WriteByte)i0)((Channel__Writer)i2, (unsigned char)(int)ch);
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)w = (void*)i1;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteLChar(BinaryRider__Writer w, unsigned short int ch) {
  register int i0;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)w-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_BinaryRider__WriterDesc_WriteBytesOrdered)i0)((BinaryRider__Writer)(int)w, (unsigned char*)(int)&ch, 2);
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)w = (void*)i0;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteString(BinaryRider__Writer w, const unsigned char* s, int s_0d) {
  register int i0, i1, i2, i3;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i2 = (int)w + 8;
  i1 = (int)*(void**)i2;
  i0 = Strings__Length((const unsigned char*)(int)s, s_0d);
  i3 = *(int*)(i1-4);
  i0++;
  i3 = (int)((_Type)i3)->tbprocs[3];
  ((_TBP_Channel__WriterDesc_WriteBytes)i3)((Channel__Writer)i1, (unsigned char*)(int)s, s_0d, (int)0, (int)i0);
  i2 = (int)*(void**)i2;
  i2 += 4;
  i2 = (int)*(void**)i2;
  *(void**)(int)w = (void*)i2;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteLString(BinaryRider__Writer w, const unsigned char* s, int s_0d) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l1;
  i1 = *(int*)((int)w-4);
  i2 = (int)((_Type)i1)->tbprocs[7];
  i1 = -1;
l0:
  i1++;
  i0 = (int)s + i1;
  i0 = *(unsigned char*)i0;
  ((_TBP_BinaryRider__WriterDesc_WriteLChar)i2)((BinaryRider__Writer)(int)w, (unsigned short int)i0);
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)w + 8;
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)w = (void*)i1;
l1:
  ;
}

void BinaryRider__WriterDesc_WriteSInt(BinaryRider__Writer w, signed char sint) {
  register int i0, i1, i2;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = (int)w + 8;
  i2 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((_TBP_Channel__WriterDesc_WriteByte)i0)((Channel__Writer)i2, (unsigned char)sint);
  i1 = (int)*(void**)i1;
  i1 += 4;
  i1 = (int)*(void**)i1;
  *(void**)(int)w = (void*)i1;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteInt(BinaryRider__Writer w, short int int_) {
  register int i0;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)w-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_BinaryRider__WriterDesc_WriteBytesOrdered)i0)((BinaryRider__Writer)(int)w, (unsigned char*)(int)&int_, 2);
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)w = (void*)i0;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteLInt(BinaryRider__Writer w, int lint) {
  register int i0;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)w-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_BinaryRider__WriterDesc_WriteBytesOrdered)i0)((BinaryRider__Writer)(int)w, (unsigned char*)(int)&lint, 4);
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)w = (void*)i0;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteNum(BinaryRider__Writer w, int lint) {
  register int i0, i1, i2, i3;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l4;
  i2 = lint < -64;
  i1 = *(int*)((int)w-4);
  i3 = (int)((_Type)i1)->tbprocs[6];
  if (i2) goto l0;
  i2 = lint > 63;
  if (i2) goto l0;
  i0 = lint;
  goto l3;
l0:
  i1 = lint;
l1:
  i0 = (int)_ashr(i1, 7, (unsigned int));
  i2 = i0 < -64;
  i1 &= 0x7FU;
  i1 += 128;
  ((_TBP_BinaryRider__WriterDesc_WriteChar)i3)((BinaryRider__Writer)(int)w, (unsigned char)i1);
  if (i2) goto l2;
  i2 = i0 <= 63;
  if (i2) goto l3;
l2:
  i1 = i0;
  goto l1;
l3:
  i2 = i0 & 0x7FU;
  ((_TBP_BinaryRider__WriterDesc_WriteChar)i3)((BinaryRider__Writer)(int)w, (unsigned char)i2);
  i2 = (int)w + 8;
  i2 = (int)*(void**)i2;
  i2 += 4;
  i2 = (int)*(void**)i2;
  *(void**)(int)w = (void*)i2;
l4:
  ;
}

void BinaryRider__WriterDesc_WriteReal(BinaryRider__Writer w, float real) {
  register int i0;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)w-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_BinaryRider__WriterDesc_WriteBytesOrdered)i0)((BinaryRider__Writer)(int)w, (unsigned char*)(int)&real, 4);
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)w = (void*)i0;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteLReal(BinaryRider__Writer w, double lreal) {
  register int i0;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)w-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_BinaryRider__WriterDesc_WriteBytesOrdered)i0)((BinaryRider__Writer)(int)w, (unsigned char*)(int)&lreal, 8);
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)w = (void*)i0;
l0:
  ;
}

void BinaryRider__WriterDesc_WriteSet(BinaryRider__Writer w, unsigned int s) {
  register int i0;
  i0 = (int)*(void**)(int)w;
  i0 = i0 != 0;
  if (i0) goto l0;
  i0 = *(int*)((int)w-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  ((_TBP_BinaryRider__WriterDesc_WriteBytesOrdered)i0)((BinaryRider__Writer)(int)w, (unsigned char*)(int)&s, 4);
  i0 = (int)w + 8;
  i0 = (int)*(void**)i0;
  i0 += 4;
  i0 = (int)*(void**)i0;
  *(void**)(int)w = (void*)i0;
l0:
  ;
}

void BinaryRider__WriterDesc_SetByteOrder(BinaryRider__Writer w, signed char order) {
  register int i0;
  i0 = (int)w + 4;
  *(signed char*)i0 = order;
}

void BinaryRider__InitReader(BinaryRider__Reader r, Channel__Channel ch, signed char byteOrder) {
  register int i0, i1;
  i0 = *(int*)((int)ch-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  *(void**)(int)r = (void*)0;
  i1 = (int)((_TBP_Channel__ChannelDesc_NewReader)i0)((Channel__Channel)(int)ch);
  i0 = (int)r + 8;
  *(void**)i0 = (void*)i1;
  i0 = (int)r + 4;
  *(signed char*)i0 = byteOrder;
  i0 = (int)r + 12;
  *(void**)i0 = (void*)(int)ch;
}

BinaryRider__Reader BinaryRider__ConnectReader(Channel__Channel ch) {
  register int i0, i1;
  {
    char *_mem, *_var;
    _mem = GC_malloc(_not_zero(16)+8);
    if (!_mem) _new_failed(_P(12916));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &BinaryRider__ReaderDesc_td.td;
    i1 = (int)_var;
  }
  i0 = i1 + 8;
  BinaryRider__InitReader((BinaryRider__Reader)i1, (Channel__Channel)(int)ch, (signed char)1);
  i0 = (int)*(void**)i0;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = 0;
l0:
  return (void*)i1;
}

void BinaryRider__InitWriter(BinaryRider__Writer w, Channel__Channel ch, signed char byteOrder) {
  register int i0, i1;
  i0 = *(int*)((int)ch-4);
  i0 = (int)((_Type)i0)->tbprocs[3];
  *(void**)(int)w = (void*)0;
  i1 = (int)((_TBP_Channel__ChannelDesc_NewWriter)i0)((Channel__Channel)(int)ch);
  i0 = (int)w + 8;
  *(void**)i0 = (void*)i1;
  i0 = (int)w + 4;
  *(signed char*)i0 = byteOrder;
  i0 = (int)w + 12;
  *(void**)i0 = (void*)(int)ch;
}

BinaryRider__Writer BinaryRider__ConnectWriter(Channel__Channel ch) {
  register int i0, i1;
  {
    char *_mem, *_var;
    _mem = GC_malloc(_not_zero(16)+8);
    if (!_mem) _new_failed(_P(13734));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &BinaryRider__WriterDesc_td.td;
    i1 = (int)_var;
  }
  i0 = i1 + 8;
  BinaryRider__InitWriter((BinaryRider__Writer)i1, (Channel__Channel)(int)ch, (signed char)1);
  i0 = (int)*(void**)i0;
  i0 = i0 != 0;
  if (i0) goto l0;
  i1 = 0;
l0:
  return (void*)i1;
}

void BinaryRider__SetDefaultByteOrder(unsigned char* x, int x_0d) {
  register int i0;
  i0 = *(unsigned char*)(int)x;
  i0 = i0 == 1;
  if (i0) goto l0;
  BinaryRider__systemByteOrder = 2;
  goto l1;
l0:
  BinaryRider__systemByteOrder = 1;
l1:
  ;
}

void BinaryRider__Init(void) {
  short int i;
  i = (short int)1;
  BinaryRider__SetDefaultByteOrder((unsigned char*)(int)&i, 2);
}

void BinaryRider_init(void) {
  register int i0;
  _mid = _register_module(&BinaryRider_md.md, &BinaryRider__ErrorContextDesc_td.td);
  {
    char *_mem, *_var;
    _mem = GC_malloc(_not_zero(4)+8);
    if (!_mem) _new_failed(_P(14204));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &BinaryRider__ErrorContextDesc_td.td;
    i0 = (int)_var;
  }
  BinaryRider__errorContext = (void*)i0;
  i0 = (int)BinaryRider__errorContext;
  Msg__InitContext((Msg__Context)i0, (const Msg__String)(int)_c0, 21);
  BinaryRider__Init();
}
