/* file generated by oo2c -- do not edit */
#include "Channel.h"
#include "Strings.h"

/* local definitions */
static Channel__ErrorContext Channel__errorContext;

/* function prototypes */
Msg__Msg Channel__GetError(int code);

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const void* list[1];
} _p0 = {0, NULL, {NULL
}};
static const struct {
  int length;
  void* pad;
  const void* list[1];
} _p1 = {0, NULL, {NULL
}};
static const struct {
  int length;
  void* pad;
  const char name[8];
} _n0 = {8, NULL, {"Channel"}};
static struct _MD Channel_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL,
    _p0.list,
    _p1.list,
    -319172408
  }
};

static const struct {
  int length;
  void* pad;
  const char name[12];
} _n1 = {12, NULL, {"ChannelDesc"}};
static const struct {
  int length;
  void* pad;
  _Type btypes[1];
} Channel__ChannelDesc_tdb = {
  1, 
  NULL, 
  {
    &Channel__ChannelDesc_td.td
  }
};
static const struct {
  int length;
  void* pad;
  const void* tbprocs[7];
} _tb0 = {7, NULL, {
  (void*)Channel__ChannelDesc_Length, 
  (void*)Channel__ChannelDesc_GetModTime, 
  (void*)Channel__ChannelDesc_NewReader, 
  (void*)Channel__ChannelDesc_NewWriter, 
  (void*)Channel__ChannelDesc_Flush, 
  (void*)Channel__ChannelDesc_Close, 
  (void*)Channel__ChannelDesc_ClearError
}};
struct _TD Channel__ChannelDesc_td = {
  NULL,
  &Types__TypeDesc_td.td,
  {
    Channel__ChannelDesc_tdb.btypes,
    _tb0.tbprocs,
    (const unsigned char*)_n1.name,
    &Channel_md.md,
    0, 
    '0', '1',
    sizeof(Channel__ChannelDesc),
    NULL
  }
};

static const struct {
  int length;
  void* pad;
  const char name[11];
} _n2 = {11, NULL, {"ReaderDesc"}};
static const struct {
  int length;
  void* pad;
  _Type btypes[1];
} Channel__ReaderDesc_tdb = {
  1, 
  NULL, 
  {
    &Channel__ReaderDesc_td.td
  }
};
static const struct {
  int length;
  void* pad;
  const void* tbprocs[6];
} _tb1 = {6, NULL, {
  (void*)Channel__ReaderDesc_Pos, 
  (void*)Channel__ReaderDesc_Available, 
  (void*)Channel__ReaderDesc_SetPos, 
  (void*)Channel__ReaderDesc_ReadByte, 
  (void*)Channel__ReaderDesc_ReadBytes, 
  (void*)Channel__ReaderDesc_ClearError
}};
struct _TD Channel__ReaderDesc_td = {
  NULL,
  &Types__TypeDesc_td.td,
  {
    Channel__ReaderDesc_tdb.btypes,
    _tb1.tbprocs,
    (const unsigned char*)_n2.name,
    &Channel_md.md,
    0, 
    '0', '1',
    sizeof(Channel__ReaderDesc),
    &Channel__ChannelDesc_td.td
  }
};

static const struct {
  int length;
  void* pad;
  const char name[11];
} _n3 = {11, NULL, {"WriterDesc"}};
static const struct {
  int length;
  void* pad;
  _Type btypes[1];
} Channel__WriterDesc_tdb = {
  1, 
  NULL, 
  {
    &Channel__WriterDesc_td.td
  }
};
static const struct {
  int length;
  void* pad;
  const void* tbprocs[5];
} _tb2 = {5, NULL, {
  (void*)Channel__WriterDesc_Pos, 
  (void*)Channel__WriterDesc_SetPos, 
  (void*)Channel__WriterDesc_WriteByte, 
  (void*)Channel__WriterDesc_WriteBytes, 
  (void*)Channel__WriterDesc_ClearError
}};
struct _TD Channel__WriterDesc_td = {
  NULL,
  &Types__TypeDesc_td.td,
  {
    Channel__WriterDesc_tdb.btypes,
    _tb2.tbprocs,
    (const unsigned char*)_n3.name,
    &Channel_md.md,
    0, 
    '0', '1',
    sizeof(Channel__WriterDesc),
    &Channel__ReaderDesc_td.td
  }
};

static const struct {
  int length;
  void* pad;
  const char name[17];
} _n4 = {17, NULL, {"ErrorContextDesc"}};
static const struct {
  int length;
  void* pad;
  _Type btypes[2];
} Channel__ErrorContextDesc_tdb = {
  2, 
  NULL, 
  {
    &Msg__ContextDesc_td.td, 
    &Channel__ErrorContextDesc_td.td
  }
};
static const struct {
  int length;
  void* pad;
  const void* tbprocs[1];
} _tb3 = {1, NULL, {
  (void*)Channel__ErrorContextDesc_GetTemplate
}};
struct _TD Channel__ErrorContextDesc_td = {
  NULL,
  &Types__TypeDesc_td.td,
  {
    Channel__ErrorContextDesc_tdb.btypes,
    _tb3.tbprocs,
    (const unsigned char*)_n4.name,
    &Channel_md.md,
    1, 
    '0', '1',
    sizeof(Channel__ErrorContextDesc),
    &Channel__WriterDesc_td.td
  }
};

/* local strings */
static const unsigned char _c14[] = "OOC:Core:Channel";
static const unsigned char _c13[] = "Failed to create unique name for temporary file";
static const unsigned char _c12[] = "No modification time available";
static const unsigned char _c11[] = "Error while closing the channel";
static const unsigned char _c10[] = "No write permission for channel";
static const unsigned char _c9[] = "No read permission for channel";
static const unsigned char _c8[] = "Invalid token type in input stream";
static const unsigned char _c7[] = "Read error";
static const unsigned char _c6[] = "Channel has been closed";
static const unsigned char _c5[] = "Trying to read past the end of the file";
static const unsigned char _c4[] = "Trying to set invalid position";
static const unsigned char _c3[] = "No space left on device";
static const unsigned char _c2[] = "Write error";
static const unsigned char _c1[] = "Invalid channel descriptor";
static const unsigned char _c0[] = "[unknown error code]";

