/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "CharClass.d"

static _ModId _mid;

unsigned char CharClass__IsNumeric(unsigned char ch) {
  register int i0;
  i0 = (int)ch < 48;
  if (i0) goto l0;
  i0 = (int)ch <= 57;
  if (i0) goto l1;
l0:
  i0 = 0;
  goto l2;
l1:
  i0 = 1;
l2:
  return (unsigned char)i0;
}

unsigned char CharClass__IsLetter(unsigned char ch) {
  register int i0;
  i0 = (int)ch < 97;
  if (i0) goto l0;
  i0 = (int)ch <= 122;
  if (i0) goto l2;
l0:
  i0 = (int)ch >= 65;
  if (!(i0)) goto l1;
  i0 = (int)ch <= 90;
  if (i0) goto l2;
l1:
  i0 = 0;
  goto l3;
l2:
  i0 = 1;
l3:
  return (unsigned char)i0;
}

unsigned char CharClass__IsUpper(unsigned char ch) {
  register int i0;
  i0 = (int)ch < 65;
  if (i0) goto l0;
  i0 = (int)ch <= 90;
  if (i0) goto l1;
l0:
  i0 = 0;
  goto l2;
l1:
  i0 = 1;
l2:
  return (unsigned char)i0;
}

unsigned char CharClass__IsLower(unsigned char ch) {
  register int i0;
  i0 = (int)ch < 97;
  if (i0) goto l0;
  i0 = (int)ch <= 122;
  if (i0) goto l1;
l0:
  i0 = 0;
  goto l2;
l1:
  i0 = 1;
l2:
  return (unsigned char)i0;
}

unsigned char CharClass__IsControl(unsigned char ch) {
  register int i0;
  i0 = (int)ch < 32;
  return (unsigned char)i0;
}

unsigned char CharClass__IsWhiteSpace(unsigned char ch) {
  register int i0;
  i0 = (int)ch == 32;
  if (i0) goto l0;
  i0 = (int)ch == 12;
  if (i0) goto l0;
  i0 = (int)ch == 10;
  if (i0) goto l0;
  i0 = (int)ch == 13;
  if (i0) goto l0;
  i0 = (int)ch == 9;
  if (i0) goto l0;
  i0 = (int)ch == 11;
  if (i0) goto l0;
  i0 = 0;
  goto l1;
l0:
  i0 = 1;
l1:
  return (unsigned char)i0;
}

unsigned char CharClass__IsEol(unsigned char ch) {
  register int i0;
  i0 = (int)ch == 10;
  return (unsigned char)i0;
}

void CharClass_init(void) {
  register int i0;
  _mid = _register_module(&CharClass_md.md, NULL);
  i0 = (int)CharClass__systemEol + 1;
  *(unsigned char*)(int)CharClass__systemEol = 10;
  *(unsigned char*)i0 = 0;
}
