/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "Check.d"

static _ModId _mid;

void Check__Error(unsigned char *ok, const unsigned char* msg__ref, int msg_0d) {
  unsigned char* msg;
  char* _old_top_vs = _top_vs;
  _push_value(int, msg, msg__ref, msg_0d);
  Out__String((const unsigned char*)(int)_c0, 15);
  Out__String((const unsigned char*)(int)msg, msg_0d);
  Out__Ln();
  Out__String((const unsigned char*)(int)_c1, 58);
  Out__Ln();
  *ok = 0;
  _top_vs = _old_top_vs;
}

void Check__WrType(void* o) {
}

unsigned char Check__GuardUses(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6;
  unsigned char ok;
  i0 = *(int*)((int)r-4);
  i0 = _type_test(i0, &Data__GuardDesc_td.td, 6);
  if (i0) goto l0;
  i5 = 1;
  goto l10;
l0:
  i0 = (int)*(void**)(int)r;
  i4 = i0 != 0;
  if (i4) goto l1;
  i5 = 1;
  goto l10;
l1:
  i4 = (int)r + 52;
  i2 = 0;
  i5 = 1;
l2:
  i3 = i0 + 12;
  i6 = (int)*(void**)i3;
  i6 = (int)r == i6;
  if (i6) goto l3;
  i6 = i5;
  goto l4;
l3:
  ok = (unsigned char)i5;
  ok = (unsigned char)i5;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c2, 28);
  *(int*)i4 = (-2147483647-1);
  i6 = ok;
l4:
  i5 = (int)*(void**)i3;
  i1 = *(int*)(i5-4);
  i5 = _type_test(i1, &Data__MergeDesc_td.td, 6);
  if (i5) goto l5;
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c3, 47);
  *(int*)i4 = (-2147483647-1);
  i6 = ok;
l5:
  i3 = (int)*(void**)i3;
  i5 = i3 + 44;
  i5 = *(short int*)i5;
  i5 = i5 != 82;
  if (i5) goto l6;
  i5 = i3 + 28;
  i5 = (int)*(void**)i5;
  i5 = (int)*(void**)i5;
  i5 = (int)r != i5;
  if (i5) goto l6;
  i3 += 32;
  i3 = (int)*(void**)i3;
  i3 = (int)r != i3;
  if (i3) goto l6;
  i5 = i6;
  goto l9;
l6:
  i3 = i2 + 1;
  i5 = i3 != 1;
  if (i5) goto l7;
  i5 = i6;
  goto l8;
l7:
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c4, 39);
  *(int*)i4 = (-2147483647-1);
  i5 = ok;
l8:
  i2 = i3;
l9:
  i3 = i0 + 4;
  i0 = (int)*(void**)i3;
  i3 = i0 != 0;
  if (i3) goto l2;
l10:
  i0 = (int)r + 64;
  i1 = (int)*(void**)i0;
  i0 = i1 != 0;
  if (i0) goto l11;
  i2 = i5;
  goto l15;
l11:
  i2 = i5;
l12:
  i0 = Check__GuardUses((Data__Region)i1);
  if (!(i0)) goto l13;
  if (!(i2)) goto l13;
  i2 = 1;
  goto l14;
l13:
  i2 = 0;
l14:
  i0 = i1 + 68;
  i1 = (int)*(void**)i0;
  i0 = i1 != 0;
  if (i0) goto l12;
l15:
  return (unsigned char)i2;
}

unsigned char Check__MergeUses(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  unsigned char ok;
  i0 = *(int*)((int)r-4);
  i0 = _type_test(i0, &Data__MergeDesc_td.td, 6);
  if (i0) goto l0;
  i7 = 1;
  goto l16;
l0:
  i0 = (int)*(void**)(int)r;
  i6 = i0 != 0;
  if (i6) goto l1;
  i7 = 1;
  goto l16;
l1:
  i5 = (int)r + 52;
  i6 = (int)r + 44;
  i1 = 0;
  i7 = 1;
l2:
  i4 = i0 + 12;
  i8 = (int)*(void**)i4;
  i8 = (int)r != i8;
  if (i8) goto l3;
  i8 = *(short int*)i6;
  i8 = i8 != 82;
  if (i8) goto l4;
  i8 = i0 + 8;
  i8 = (int)*(void**)i8;
  i8 = i8 != 0;
  if (i8) goto l4;
l3:
  i3 = i7;
  goto l5;
l4:
  ok = (unsigned char)i7;
  ok = (unsigned char)i7;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c5, 28);
  *(int*)i5 = (-2147483647-1);
  i3 = ok;
l5:
  i8 = (int)*(void**)i4;
  i8 += 44;
  i8 = *(short int*)i8;
  i2 = i8 != 19;
  if (i2) goto l6;
  i7 = i3;
  goto l15;
l6:
  i7 = *(short int*)i6;
  i7 = i7 != 82;
  if (i7) goto l7;
  i8 = i8 != 82;
  if (i8) goto l8;
l7:
  i8 = i3;
  goto l9;
l8:
  ok = (unsigned char)i3;
  ok = (unsigned char)i3;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c6, 59);
  *(int*)i5 = (-2147483647-1);
  i8 = ok;
l9:
  i4 = (int)*(void**)i4;
  i7 = *(int*)(i4-4);
  i7 = _type_test(i7, &Data__MergeDesc_td.td, 6);
  if (i7) goto l10;
  ok = (unsigned char)i8;
  ok = (unsigned char)i8;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c8, 55);
  *(int*)i5 = (-2147483647-1);
  i2 = i1;
  i7 = ok;
  goto l14;
l10:
  i2 = i4 + 44;
  i2 = *(short int*)i2;
  i2 = i2 != 82;
  if (i2) goto l11;
  i4 += 28;
  i4 = (int)*(void**)i4;
  i4 = (int)*(void**)i4;
  i4 = (int)r == i4;
  if (i4) goto l13;
l11:
  i2 = i1 + 1;
  i7 = i2 != 1;
  if (i7) goto l12;
  i7 = i8;
  goto l14;
l12:
  ok = (unsigned char)i8;
  ok = (unsigned char)i8;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c7, 39);
  *(int*)i5 = (-2147483647-1);
  i7 = ok;
  goto l14;
l13:
  i7 = i8;
  i2 = i1;
l14:
  i1 = i2;
l15:
  i4 = i0 + 4;
  i0 = (int)*(void**)i4;
  i4 = i0 != 0;
  if (i4) goto l2;
l16:
  i0 = (int)r + 64;
  i1 = (int)*(void**)i0;
  i0 = i1 != 0;
  if (i0) goto l17;
  i2 = i7;
  goto l21;
l17:
  i2 = i7;
l18:
  i0 = Check__MergeUses((Data__Region)i1);
  if (!(i0)) goto l19;
  if (!(i2)) goto l19;
  i2 = 1;
  goto l20;
l19:
  i2 = 0;
l20:
  i0 = i1 + 68;
  i1 = (int)*(void**)i0;
  i0 = i1 != 0;
  if (i0) goto l18;
l21:
  return (unsigned char)i2;
}

unsigned char Check__GateOpnds(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8, i9;
  unsigned char ok;
  i0 = (int)r + 56;
  i8 = (int)*(void**)i0;
  i0 = i8 != 0;
  if (i0) goto l0;
  i9 = 1;
  goto l21;
l0:
  i9 = 1;
l1:
  i0 = i8 + 44;
  i0 = *(short int*)i0;
  i0 = i0 == 19;
  if (i0) goto l5;
  i0 = *(int*)(i8-4);
  i0 = _type_test(i0, &Data__RegionDesc_td.td, 5);
  if (i0) goto l2;
  i0 = i9;
  goto l4;
l2:
  if (!(i9)) goto l3;
  i0 = Check__GateOpnds((Data__Region)i8);
  if (!(i0)) goto l3;
  i0 = 1;
  goto l4;
l3:
  i0 = 0;
l4:
  i9 = i0;
  goto l20;
l5:
  i6 = i8 + 28;
  i0 = (int)*(void**)i6;
  i6 = i0 == 0;
  if (i6) goto l18;
  i6 = (int)*(void**)i0;
  i1 = *(int*)(i6-4);
  i1 = _type_test(i1, &Data__MergeDesc_td.td, 6);
  if (i1) goto l6;
  ok = (unsigned char)i9;
  ok = (unsigned char)i9;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c14, 36);
  i1 = i8 + 52;
  *(int*)i1 = (-2147483647-1);
  i7 = ok;
  goto l19;
l6:
  i0 += 8;
  i2 = (int)*(void**)i0;
  i0 = i6 + 28;
  i3 = (int)*(void**)i0;
  i0 = i2 == 0;
  if (i0) goto l8;
  i1 = i3 == 0;
  if (i1) goto l8;
  i0 = 0;
  i4 = i3;
  i5 = i2;
l7:
  i5 += 8;
  i5 = (int)*(void**)i5;
  i4 += 8;
  i4 = (int)*(void**)i4;
  i0++;
  i7 = i5 == 0;
  if (i7) goto l9;
  i7 = i4 != 0;
  if (i7) goto l7;
  goto l9;
l8:
  i5 = i2;
  i4 = i3;
  i0 = 0;
l9:
  i7 = i5 == 0;
  if (!(i7)) goto l10;
  i7 = i4 != 0;
  if (i7) goto l17;
l10:
  i5 = i5 != 0;
  if (!(i5)) goto l11;
  i4 = i4 == 0;
  if (i4) goto l16;
l11:
  i7 = i6 + 44;
  i7 = *(short int*)i7;
  if (!(i7<=79 || i7>=84)) goto l12;
  ok = (unsigned char)i9;
  ok = (unsigned char)i9;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c13, 41);
  i0 = i8 + 52;
  *(int*)i0 = (-2147483647-1);
  i7 = ok;
  goto l19;
l12:
  if (!((i7>=80 && i7<=82))) goto l14;
  i7 = i0 != 2;
  if (i7) goto l13;
  i7 = i9;
  goto l19;
l13:
  ok = (unsigned char)i9;
  ok = (unsigned char)i9;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c9, 37);
  i7 = i6 + 52;
  *(int*)i7 = (-2147483647-1);
  i7 = ok;
  goto l19;
l14:
  if (!(i7==83)) goto l19;
  i0 = i0 < 1;
  if (i0) goto l15;
  i7 = i9;
  goto l19;
l15:
  ok = (unsigned char)i9;
  ok = (unsigned char)i9;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c9, 37);
  i0 = i6 + 52;
  *(int*)i0 = (-2147483647-1);
  i7 = ok;
  goto l19;
l16:
  ok = (unsigned char)i9;
  ok = (unsigned char)i9;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c12, 27);
  i4 = i8 + 52;
  *(int*)i4 = (-2147483647-1);
  i7 = ok;
  goto l19;
l17:
  ok = (unsigned char)i9;
  ok = (unsigned char)i9;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c11, 29);
  i7 = i8 + 52;
  *(int*)i7 = (-2147483647-1);
  i7 = ok;
  goto l19;
l18:
  ok = (unsigned char)i9;
  ok = (unsigned char)i9;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c10, 20);
  i9 = i8 + 52;
  *(int*)i9 = (-2147483647-1);
  i7 = ok;
l19:
  i9 = i7;
l20:
  i0 = i8 + 36;
  i8 = (int)*(void**)i0;
  i0 = i8 != 0;
  if (i0) goto l1;
l21:
  return (unsigned char)i9;
}

unsigned char Check__Opnds(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8, i9;
  unsigned char ok;
  i0 = *(int*)((int)r-4);
  i0 = (int)((_Type)i0)->tbprocs[0];
  i8 = (int)((_TBP_Data__NodeDesc_Greg)i0)((Data__Node)(int)r);
  i0 = (int)r + 56;
  i7 = (int)*(void**)i0;
  i0 = i7 != 0;
  if (i0) goto l0;
  i9 = 1;
  goto l26;
l0:
  i9 = 1;
l1:
  i0 = i7 + 28;
  i3 = (int)*(void**)i0;
  i0 = i3 != 0;
  if (i0) goto l2;
  i0 = i9;
  goto l10;
l2:
  i0 = i9;
l3:
  i4 = (int)*(void**)i3;
  i1 = *(int*)(i4-4);
  i1 = _type_test(i1, &Data__ResultDesc_td.td, 3);
  if (!(i1)) goto l9;
  i4 += 16;
  i2 = (int)*(void**)i4;
  i4 = i8 != i2;
  i2 += 32;
  i2 = (int)*(void**)i2;
  if (!(i4)) goto l4;
  i1 = i2 == 0;
  if (i1) goto l7;
l4:
  if (!(i4)) goto l5;
  i4 = *(int*)(i2-4);
  i4 = (int)((_Type)i4)->tbprocs[0];
  i2 = (int)((_TBP_Data__NodeDesc_Greg)i4)((Data__Node)i2);
  i2 = i2 != i8;
  if (i2) goto l6;
l5:
  i1 = i0;
  goto l8;
l6:
  ok = (unsigned char)i0;
  ok = (unsigned char)i0;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c16, 34);
  i2 = i3 + 20;
  *(int*)i2 = (-2147483647-1);
  i1 = ok;
  goto l8;
l7:
  ok = (unsigned char)i0;
  ok = (unsigned char)i0;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c15, 39);
  i1 = i3 + 20;
  *(int*)i1 = (-2147483647-1);
  i1 = ok;
l8:
  i0 = i1;
l9:
  i4 = i3 + 8;
  i3 = (int)*(void**)i4;
  i4 = i3 != 0;
  if (i4) goto l3;
l10:
  i9 = (int)SymbolTable__store;
  i3 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i7, (Data__Addressable)i9, (short int)-3);
  i9 = i3 != 0;
  if (i9) goto l11;
  i4 = i0;
  goto l15;
l11:
  i2 = i3 + 8;
  i9 = (int)*(void**)i2;
  i2 = i9 != 0;
  if (i2) goto l12;
  i4 = i0;
  goto l15;
l12:
  i2 = i3 + 20;
  i4 = i0;
l13:
  i1 = i9 + 16;
  i5 = (int)*(void**)i1;
  i1 = i5 == 0;
  if (i1) goto l14;
  i1 = *(int*)(i5-4);
  i1 = _type_test(i1, &Data__SymLocationDesc_td.td, 2);
  if (!(i1)) goto l14;
  i5 = (int)*(void**)i5;
  i1 = (int)SymbolTable__store;
  i5 = i5 != i1;
  if (i5) goto l14;
  ok = (unsigned char)i4;
  ok = (unsigned char)i4;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c17, 20);
  *(int*)i2 = (-2147483647-1);
  i4 = ok;
l14:
  i1 = i9 + 8;
  i9 = (int)*(void**)i1;
  i1 = i9 != 0;
  if (i1) goto l13;
l15:
  i0 = (int)SymbolTable__mem;
  i3 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i7, (Data__Addressable)i0, (short int)-3);
  i0 = i3 != 0;
  if (i0) goto l16;
  i5 = i4;
  goto l22;
l16:
  i2 = i3 + 8;
  i0 = (int)*(void**)i2;
  i1 = i0 != 0;
  if (i1) goto l17;
  i5 = i4;
  goto l20;
l17:
  i1 = i3 + 20;
  i5 = i4;
l18:
  i6 = i0 + 16;
  i9 = (int)*(void**)i6;
  i6 = i9 == 0;
  if (i6) goto l19;
  i6 = *(int*)(i9-4);
  i6 = _type_test(i6, &Data__SymLocationDesc_td.td, 2);
  if (!(i6)) goto l19;
  i9 = (int)*(void**)i9;
  i6 = (int)SymbolTable__mem;
  i9 = i9 != i6;
  if (i9) goto l19;
  ok = (unsigned char)i5;
  ok = (unsigned char)i5;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c18, 18);
  *(int*)i1 = (-2147483647-1);
  i5 = ok;
l19:
  i6 = i0 + 8;
  i0 = (int)*(void**)i6;
  i6 = i0 != 0;
  if (i6) goto l18;
l20:
  i1 = i7 + 44;
  i1 = *(short int*)i1;
  i1 = i1 == 2;
  if (i1) goto l22;
  i2 = (int)*(void**)i2;
  i1 = i2 == 0;
  if (i1) goto l21;
  i1 = (int)SymbolTable__store;
  i1 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i7, (Data__Addressable)i1, (short int)-3);
  i2 = i1 == i2;
  if (i2) goto l22;
l21:
  ok = (unsigned char)i5;
  ok = (unsigned char)i5;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c19, 34);
  i2 = i3 + 20;
  *(int*)i2 = (-2147483647-1);
  i5 = ok;
l22:
  i0 = *(int*)(i7-4);
  i0 = _type_test(i0, &Data__RegionDesc_td.td, 5);
  if (i0) goto l23;
  i9 = i5;
  goto l25;
l23:
  if (!(i5)) goto l24;
  i9 = Check__Opnds((Data__Region)i7);
  if (!(i9)) goto l24;
  i9 = 1;
  goto l25;
l24:
  i9 = 0;
l25:
  i7 += 36;
  i7 = (int)*(void**)i7;
  i0 = i7 != 0;
  if (i0) goto l1;
l26:
  return (unsigned char)i9;
}

unsigned char Check__Results(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  unsigned char ok;
  i0 = (int)r + 56;
  i7 = (int)*(void**)i0;
  i0 = i7 != 0;
  if (i0) goto l0;
  i8 = 1;
  goto l19;
l0:
  i8 = 1;
l1:
  i0 = (int)SymbolTable__store;
  i3 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i7, (Data__Addressable)i0, (short int)-3);
  i0 = i3 != 0;
  if (i0) goto l2;
  i0 = i8;
  goto l7;
l2:
  i3 += 12;
  i1 = (int)*(void**)i3;
  i3 = i1 != 0;
  if (i3) goto l3;
  i0 = i8;
  goto l6;
l3:
  i3 = i7 + 52;
  i0 = i8;
l4:
  i2 = i1 + 20;
  i4 = (int)*(void**)i2;
  i2 = i4 == 0;
  if (i2) goto l5;
  i2 = *(int*)(i4-4);
  i2 = _type_test(i2, &Data__SymLocationDesc_td.td, 2);
  if (!(i2)) goto l5;
  i4 = (int)*(void**)i4;
  i2 = (int)SymbolTable__store;
  i4 = i4 != i2;
  if (i4) goto l5;
  ok = (unsigned char)i0;
  ok = (unsigned char)i0;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c20, 19);
  *(int*)i3 = (-2147483647-1);
  i0 = ok;
l5:
  i2 = i1 + 12;
  i1 = (int)*(void**)i2;
  i2 = i1 != 0;
  if (i2) goto l4;
l6:
  i3 = (int)SymbolTable__store;
  i3 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i7, (Data__Addressable)i3, (short int)-3);
  i3 = i3 != 0;
  if (i3) goto l7;
  ok = (unsigned char)i0;
  ok = (unsigned char)i0;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c21, 49);
  i3 = i7 + 52;
  *(int*)i3 = (-2147483647-1);
  i0 = ok;
l7:
  i1 = (int)SymbolTable__mem;
  i5 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i7, (Data__Addressable)i1, (short int)-3);
  i1 = i5 != 0;
  if (i1) goto l8;
  i6 = i0;
  goto l15;
l8:
  i4 = i5 + 12;
  i1 = (int)*(void**)i4;
  i8 = i1 != 0;
  if (i8) goto l9;
  i6 = i0;
  goto l12;
l9:
  i8 = i7 + 52;
  i6 = i0;
l10:
  i3 = i1 + 20;
  i2 = (int)*(void**)i3;
  i3 = i2 == 0;
  if (i3) goto l11;
  i3 = *(int*)(i2-4);
  i3 = _type_test(i3, &Data__SymLocationDesc_td.td, 2);
  if (!(i3)) goto l11;
  i2 = (int)*(void**)i2;
  i3 = (int)SymbolTable__mem;
  i2 = i2 != i3;
  if (i2) goto l11;
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c22, 17);
  *(int*)i8 = (-2147483647-1);
  i6 = ok;
l11:
  i3 = i1 + 12;
  i1 = (int)*(void**)i3;
  i3 = i1 != 0;
  if (i3) goto l10;
l12:
  i8 = (int)SymbolTable__mem;
  i8 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i7, (Data__Addressable)i8, (short int)-3);
  i8 = i8 != 0;
  if (i8) goto l13;
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c23, 47);
  i8 = i7 + 52;
  *(int*)i8 = (-2147483647-1);
  i6 = ok;
l13:
  i8 = i7 + 44;
  i8 = *(short int*)i8;
  i8 = i8 == 1;
  if (i8) goto l15;
  i4 = (int)*(void**)i4;
  i5 = i4 == 0;
  if (i5) goto l14;
  i5 = (int)SymbolTable__store;
  i5 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i7, (Data__Addressable)i5, (short int)-3);
  i4 = i5 == i4;
  if (i4) goto l15;
l14:
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c24, 33);
  i4 = i7 + 52;
  *(int*)i4 = (-2147483647-1);
  i6 = ok;
l15:
  i0 = *(int*)(i7-4);
  i0 = _type_test(i0, &Data__RegionDesc_td.td, 5);
  if (i0) goto l16;
  i8 = i6;
  goto l18;
l16:
  if (!(i6)) goto l17;
  i8 = Check__Results((Data__Region)i7);
  if (!(i8)) goto l17;
  i8 = 1;
  goto l18;
l17:
  i8 = 0;
l18:
  i7 += 36;
  i7 = (int)*(void**)i7;
  i0 = i7 != 0;
  if (i0) goto l1;
l19:
  return (unsigned char)i8;
}

unsigned char Check__Enter(Data__Region greg) {
  register int i0, i1, i2;
  unsigned char ok;
  i1 = (int)Data__RegionDesc_EnterInstr((Data__Region)(int)greg);
  i0 = i1 == 0;
  if (i0) goto l3;
  i0 = (int)SymbolTable__mem;
  i0 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i1, (Data__Addressable)i0, (short int)-3);
  i2 = i0 == 0;
  if (i2) goto l0;
  i0 += 12;
  i0 = (int)*(void**)i0;
  i0 = i0 != 0;
  if (i0) goto l1;
l0:
  i2 = 1;
  goto l2;
l1:
  ok = (unsigned char)1;
  ok = (unsigned char)1;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c25, 46);
  i0 = (int)greg + 52;
  *(int*)i0 = (-2147483647-1);
  i2 = ok;
l2:
  i0 = (int)SymbolTable__store;
  i0 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i1, (Data__Addressable)i0, (short int)-3);
  i0 = i0 == 0;
  if (i0) goto l4;
  ok = (unsigned char)i2;
  ok = (unsigned char)i2;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c26, 24);
  i0 = (int)greg + 52;
  *(int*)i0 = (-2147483647-1);
  i2 = ok;
  goto l4;
l3:
  ok = (unsigned char)1;
  ok = (unsigned char)1;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c27, 26);
  i0 = (int)greg + 52;
  *(int*)i0 = (-2147483647-1);
  i2 = ok;
l4:
  return (unsigned char)i2;
}

unsigned char Check__Exit(Data__Region greg) {
  register int i0, i1, i2, i3;
  unsigned char ok;
  i2 = (int)Data__RegionDesc_ExitInstr((Data__Region)(int)greg);
  i0 = i2 != 0;
  if (i0) goto l0;
  i3 = 1;
  goto l5;
l0:
  i1 = (int)SymbolTable__mem;
  i0 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i2, (Data__Addressable)i1, (short int)-3);
  i1 = i0 != 0;
  if (i1) goto l1;
  i3 = 1;
  goto l4;
l1:
  i0 += 8;
  i0 = (int)*(void**)i0;
  i0 = i0 != 0;
  if (i0) goto l2;
  i3 = 1;
  goto l3;
l2:
  ok = (unsigned char)1;
  ok = (unsigned char)1;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c28, 46);
  i0 = (int)greg + 52;
  *(int*)i0 = (-2147483647-1);
  i3 = ok;
l3:
  i0 = (int)Data__RegionDesc_EnterInstr((Data__Region)(int)greg);
  i1 = (int)SymbolTable__mem;
  i0 = (int)Data__InstructionDesc_GetResult((Data__Instruction)i0, (Data__Addressable)i1, (short int)-3);
  i0 = i0 != 0;
  if (i0) goto l4;
  ok = (unsigned char)i3;
  ok = (unsigned char)i3;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c29, 32);
  i0 = i2 + 52;
  *(int*)i0 = (-2147483647-1);
  i3 = ok;
l4:
  i1 = (int)SymbolTable__store;
  i2 = (int)Data__InstructionDesc_GetOperand((Data__Instruction)i2, (Data__Addressable)i1, (short int)-3);
  i2 = i2 == 0;
  if (i2) goto l5;
  ok = (unsigned char)i3;
  ok = (unsigned char)i3;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c30, 24);
  i2 = (int)greg + 52;
  *(int*)i2 = (-2147483647-1);
  i3 = ok;
l5:
  return (unsigned char)i3;
}

unsigned char Check__LoopGates(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6, i7;
  unsigned char ok;
  i0 = (int)r + 56;
  i6 = (int)*(void**)i0;
  i0 = i6 != 0;
  if (i0) goto l0;
  i7 = 1;
  goto l15;
l0:
  i7 = 1;
l1:
  i0 = i6 + 44;
  i0 = *(short int*)i0;
  i0 = i0 != 19;
  if (i0) goto l2;
  i4 = i6 + 28;
  i1 = (int)*(void**)i4;
  i0 = (int)*(void**)i1;
  i4 = i0 + 44;
  i4 = *(short int*)i4;
  i4 = i4 == 82;
  if (i4) goto l3;
l2:
  i5 = i7;
  goto l11;
l3:
  i1 += 8;
  i4 = (int)*(void**)i1;
  i1 = i6 + 24;
  i2 = (int)*(void**)i1;
  i1 = i2 == 0;
  if (i1) goto l4;
  i2 = SymbolTable__TypeInGroup((Data__Struct)i2, (signed char)47);
  if (i2) goto l5;
l4:
  i2 = (int)*(void**)i4;
  i3 = *(int*)(i2-4);
  i3 = _type_test(i3, &Data__ResultDesc_td.td, 3);
  if (i3) goto l6;
l5:
  i5 = i7;
  goto l11;
l6:
  i5 = i2 + 16;
  i5 = (int)*(void**)i5;
  i5 += 32;
  i1 = (int)*(void**)i5;
  i5 = i1 == 0;
  if (i5) goto l8;
  i5 = i0 == i1;
  if (i5) goto l8;
  i3 = i1;
l7:
  i3 += 32;
  i3 = (int)*(void**)i3;
  i2 = i3 == 0;
  if (i2) goto l9;
  i2 = i0 != i3;
  if (i2) goto l7;
  goto l9;
l8:
  i3 = i1;
l9:
  i5 = i0 == i3;
  if (i5) goto l10;
  i5 = i7;
  goto l11;
l10:
  ok = (unsigned char)i7;
  ok = (unsigned char)i7;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c31, 52);
  i5 = i4 + 20;
  *(int*)i5 = (-2147483647-1);
  i5 = ok;
l11:
  i0 = *(int*)(i6-4);
  i0 = _type_test(i0, &Data__RegionDesc_td.td, 5);
  if (i0) goto l12;
  i7 = i5;
  goto l14;
l12:
  if (!(i5)) goto l13;
  i7 = Check__LoopGates((Data__Region)i6);
  if (!(i7)) goto l13;
  i7 = 1;
  goto l14;
l13:
  i7 = 0;
l14:
  i0 = i6 + 36;
  i6 = (int)*(void**)i0;
  i0 = i6 != 0;
  if (i0) goto l1;
l15:
  return (unsigned char)i7;
}

unsigned char Check__Update(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  unsigned char ok;
  i0 = (int)r + 56;
  i7 = (int)*(void**)i0;
  i0 = i7 != 0;
  if (i0) goto l0;
  i8 = 1;
  goto l20;
l0:
  i8 = 1;
l1:
  i5 = i7 + 44;
  i4 = *(short int*)i5;
  i0 = (short int)_ashr(i4, 4, (unsigned short int));
  i0 = i0 == 3;
  if (i0) goto l2;
  i6 = i8;
  goto l16;
l2:
  i4 = i4 == 53;
  if (i4) goto l3;
  i0 = (int)Data__InstructionDesc_LastOperand((Data__Instruction)i7);
  goto l4;
l3:
  i0 = (int)Data__InstructionDesc_NthOperand((Data__Instruction)i7, (short int)1);
l4:
  i4 = (int)Data__OpndDesc_OpndType((Data__Opnd)i0);
  i4 = SymbolTable__TypeInGroup((Data__Struct)i4, (signed char)47);
  if (i4) goto l5;
  i6 = i8;
  goto l16;
l5:
  i2 = (int)*(void**)i0;
  i3 = *(int*)(i2-4);
  i1 = _type_test(i3, &Data__InstructionDesc_td.td, 4);
  if (!(i1)) goto l6;
  i4 = i2 + 44;
  i6 = *(short int*)i4;
  i4 = i6 == 49;
  if (i4) goto l15;
  i6 = i6 == 48;
  if (i6) goto l15;
l6:
  if (!(i1)) goto l7;
  i6 = i2 + 44;
  i6 = *(short int*)i6;
  i1 = (short int)_ashr(i6, 4, (unsigned short int));
  i1 = i1 == 2;
  if (i1) goto l14;
  i1 = i6 == 23;
  if (i1) goto l14;
  i6 = i6 == 22;
  if (i6) goto l14;
l7:
  i5 = *(short int*)i5;
  i6 = i5 == 48;
  if (i6) goto l8;
  i6 = i5 != 49;
  if (i6) goto l9;
l8:
  i6 = _type_test(i3, &Data__ResultDesc_td.td, 3);
  if (!(i6)) goto l9;
  i6 = i2 + 16;
  i6 = (int)*(void**)i6;
  i6 += 44;
  i6 = *(short int*)i6;
  i6 = i6 == 3;
  if (i6) goto l13;
l9:
  i6 = i5 == 51;
  if (i6) goto l10;
  i6 = i5 == 52;
  if (i6) goto l10;
  i5 = i5 == 50;
  if (i5) goto l10;
  goto l11;
l10:
  i3 = _type_test(i3, &Data__ResultDesc_td.td, 3);
  if (!(i3)) goto l11;
  i2 += 16;
  i2 = (int)*(void**)i2;
  i2 += 44;
  i2 = *(short int*)i2;
  i2 = i2 == 3;
  if (i2) goto l12;
l11:
  ok = (unsigned char)i8;
  ok = (unsigned char)i8;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c32, 34);
  i5 = i0 + 20;
  *(int*)i5 = (-2147483647-1);
  i6 = ok;
  goto l16;
l12:
  i6 = i8;
  goto l16;
l13:
  i6 = i8;
  goto l16;
l14:
  i6 = i8;
  goto l16;
l15:
  i6 = i8;
l16:
  i0 = *(int*)(i7-4);
  i0 = _type_test(i0, &Data__RegionDesc_td.td, 5);
  if (i0) goto l17;
  i8 = i6;
  goto l19;
l17:
  if (!(i6)) goto l18;
  i8 = Check__Update((Data__Region)i7);
  if (!(i8)) goto l18;
  i8 = 1;
  goto l19;
l18:
  i8 = 0;
l19:
  i0 = i7 + 36;
  i7 = (int)*(void**)i0;
  i0 = i7 != 0;
  if (i0) goto l1;
l20:
  return (unsigned char)i8;
}

unsigned char Check__Structure_SameGreg(Data__Region r0, Data__Instruction i) {
  register int i0, i1, i2, i3;
  i0 = *(int*)((int)i-4);
  i0 = _type_test(i0, &Data__RegionDesc_td.td, 5);
  if (i0) goto l0;
  i0 = (int)i + 32;
  i0 = (int)*(void**)i0;
  goto l1;
l0:
  i0 = (int)i;
l1:
  i1 = (int)r0 + 32;
  i2 = i0 + 32;
  i1 = (int)*(void**)i1;
  i2 = (int)*(void**)i2;
  i1 = i1 != 0;
  i3 = i2 != 0;
  if (i1) goto l2;
  i2 = (int)r0;
  goto l4;
l2:
  i2 = (int)r0;
l3:
  i2 += 32;
  i2 = (int)*(void**)i2;
  i1 = i2 + 32;
  i1 = (int)*(void**)i1;
  i1 = i1 != 0;
  if (i1) goto l3;
l4:
  if (i3) goto l5;
  i3 = i0;
  goto l7;
l5:
  i3 = i0;
l6:
  i3 += 32;
  i3 = (int)*(void**)i3;
  i1 = i3 + 32;
  i1 = (int)*(void**)i1;
  i1 = i1 != 0;
  if (i1) goto l6;
l7:
  i0 = i2 == i3;
  return (unsigned char)i0;
}

unsigned char Check__Structure(Data__Region r) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  unsigned char ok;
  i0 = (int)r + 56;
  i7 = (int)*(void**)i0;
  i0 = i7 != 0;
  if (i0) goto l0;
  i8 = 1;
  goto l27;
l0:
  i8 = 1;
l1:
  i0 = i7 + 32;
  i0 = (int)*(void**)i0;
  i0 = (int)r == i0;
  if (i0) goto l2;
  ok = (unsigned char)i8;
  ok = (unsigned char)i8;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c33, 19);
  i0 = i7 + 52;
  *(int*)i0 = (-2147483647-1);
  i8 = ok;
l2:
  i0 = i7 != 0;
  if (i0) goto l3;
  i6 = i8;
  goto l14;
l3:
  i0 = i7 + 52;
  i4 = i7;
  i6 = i8;
l4:
  i1 = i4 + 16;
  i1 = (int)*(void**)i1;
  i1 = i7 != i1;
  if (i1) goto l5;
  i5 = i6;
  goto l6;
l5:
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c34, 19);
  *(int*)i0 = (-2147483647-1);
  i5 = ok;
l6:
  i3 = (int)*(void**)i4;
  i1 = i3 != 0;
  if (i1) goto l7;
  i6 = i5;
  goto l13;
l7:
  i6 = i5;
l8:
  i1 = i3 + 12;
  i2 = (int)*(void**)i1;
  i1 = i2 + 32;
  i1 = (int)*(void**)i1;
  i1 = i1 == 0;
  if (i1) goto l11;
  i1 = Check__Structure_SameGreg((Data__Region)(int)r, (Data__Instruction)i2);
  if (i1) goto l9;
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c36, 19);
  *(int*)i0 = (-2147483647-1);
  i1 = ok;
  goto l10;
l9:
  i1 = i6;
l10:
  i6 = i1;
  goto l12;
l11:
  ok = (unsigned char)i6;
  ok = (unsigned char)i6;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c35, 19);
  *(int*)i0 = (-2147483647-1);
  i6 = ok;
l12:
  i1 = i3 + 4;
  i3 = (int)*(void**)i1;
  i1 = i3 != 0;
  if (i1) goto l8;
l13:
  i1 = i4 + 12;
  i4 = (int)*(void**)i1;
  i1 = i4 != 0;
  if (i1) goto l4;
l14:
  i0 = i7 + 28;
  i4 = (int)*(void**)i0;
  i0 = i4 != 0;
  if (i0) goto l15;
  i0 = i6;
  goto l23;
l15:
  i0 = i6;
l16:
  i1 = i4 + 12;
  i1 = (int)*(void**)i1;
  i1 = i7 != i1;
  if (i1) goto l21;
  i2 = (int)*(void**)i4;
  i5 = *(int*)(i2-4);
  i5 = _type_test(i5, &Data__ResultDesc_td.td, 3);
  if (!(i5)) goto l17;
  i3 = i2 + 16;
  i3 = (int)*(void**)i3;
  i1 = i3 + 32;
  i1 = (int)*(void**)i1;
  i1 = i1 != 0;
  if (i1) goto l17;
  i3 += 44;
  i3 = *(short int*)i3;
  i3 = i3 != 66;
  if (i3) goto l19;
l17:
  if (!(i5)) goto l18;
  i2 += 16;
  i2 = (int)*(void**)i2;
  i2 = Check__Structure_SameGreg((Data__Region)(int)r, (Data__Instruction)i2);
  if (i2) goto l18;
  ok = (unsigned char)i0;
  ok = (unsigned char)i0;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c38, 19);
  i3 = i4 + 20;
  *(int*)i3 = (-2147483647-1);
  i3 = ok;
  goto l20;
l18:
  i3 = i0;
  goto l20;
l19:
  ok = (unsigned char)i0;
  ok = (unsigned char)i0;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c15, 39);
  i3 = i4 + 20;
  *(int*)i3 = (-2147483647-1);
  i3 = ok;
l20:
  i0 = i3;
  goto l22;
l21:
  ok = (unsigned char)i0;
  ok = (unsigned char)i0;
  Check__Error((unsigned char *)(int)&ok, (const unsigned char*)(int)_c37, 19);
  i0 = i4 + 20;
  *(int*)i0 = (-2147483647-1);
  i0 = ok;
l22:
  i1 = i4 + 8;
  i4 = (int)*(void**)i1;
  i1 = i4 != 0;
  if (i1) goto l16;
l23:
  i1 = *(int*)(i7-4);
  i1 = _type_test(i1, &Data__RegionDesc_td.td, 5);
  if (i1) goto l24;
  i8 = i0;
  goto l26;
l24:
  if (!(i0)) goto l25;
  i8 = Check__Structure((Data__Region)i7);
  if (!(i8)) goto l25;
  i8 = 1;
  goto l26;
l25:
  i8 = 0;
l26:
  i7 += 36;
  i7 = (int)*(void**)i7;
  i0 = i7 != 0;
  if (i0) goto l1;
l27:
  return (unsigned char)i8;
}

unsigned char Check__All(Data__GlobalRegion r) {
  register int i0;
  i0 = Check__Structure((Data__Region)(int)r);
  if (!(i0)) goto l0;
  i0 = Check__GuardUses((Data__Region)(int)r);
  if (!(i0)) goto l0;
  i0 = 1;
  goto l1;
l0:
  i0 = 0;
l1:
  if (!(i0)) goto l2;
  i0 = Check__MergeUses((Data__Region)(int)r);
  if (!(i0)) goto l2;
  i0 = 1;
  goto l3;
l2:
  i0 = 0;
l3:
  if (!(i0)) goto l4;
  i0 = Check__GateOpnds((Data__Region)(int)r);
  if (!(i0)) goto l4;
  i0 = 1;
  goto l5;
l4:
  i0 = 0;
l5:
  if (!(i0)) goto l6;
  i0 = Check__Opnds((Data__Region)(int)r);
  if (!(i0)) goto l6;
  i0 = 1;
  goto l7;
l6:
  i0 = 0;
l7:
  if (!(i0)) goto l8;
  i0 = Check__Enter((Data__Region)(int)r);
  if (!(i0)) goto l8;
  i0 = 1;
  goto l9;
l8:
  i0 = 0;
l9:
  if (!(i0)) goto l10;
  i0 = Check__Exit((Data__Region)(int)r);
  if (!(i0)) goto l10;
  i0 = 1;
  goto l11;
l10:
  i0 = 0;
l11:
  if (!(i0)) goto l12;
  i0 = Check__LoopGates((Data__Region)(int)r);
  if (!(i0)) goto l12;
  i0 = 1;
  goto l13;
l12:
  i0 = 0;
l13:
  if (!(i0)) goto l14;
  i0 = Check__Update((Data__Region)(int)r);
  if (!(i0)) goto l14;
  i0 = 1;
  goto l15;
l14:
  i0 = 0;
l15:
  if (i0) goto l16;
  WriteGSA__Body((Data__GlobalRegion)(int)r);
l16:
  return (unsigned char)i0;
}

void Check_init(void) {
  _mid = _register_module(&Check_md.md, NULL);
}
