/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "ConvTypes.d"

static _ModId _mid;

void ConvTypes_init(void) {
  _mid = _register_module(&ConvTypes_md.md, &ConvTypes__ScanDesc_td.td);
}
