/* file generated by oo2c -- do not edit */
#ifndef _MODULE_Data_
#define _MODULE_Data_

#define Data__undefPos -1
#include "Parameter.h"
typedef Parameter__String Data__String;
typedef struct Data__InfoDesc {
  char _dummy;
} Data__InfoDesc;
typedef struct Data__InfoDesc* Data__Info;
typedef struct Data__NodeDesc {
  char _dummy;
} Data__NodeDesc;
typedef struct Data__NodeDesc* Data__Node;
typedef struct Data__LocationDesc {
  char _dummy;
} Data__LocationDesc;
typedef struct Data__LocationDesc* Data__Location;
typedef struct Data__AddressableDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  struct Data__UsableDesc* currValue;
  Data__Info beInfo;
} Data__AddressableDesc;
typedef struct Data__AddressableDesc* Data__Addressable;
typedef struct Data__GuardDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  struct Data__ResultDesc* nextResult;
  struct Data__InstructionDesc* instr;
  Data__Location location;
  struct Data__StructDesc* type;
  struct Data__OpndDesc* opndList;
  struct Data__RegionDesc* region;
  struct Data__InstructionDesc* nextInstr;
  struct Data__InstructionDesc* prevInstr;
  short int opcode;
  char _46pad, _47pad;
  unsigned int flags;
  int pos;
  struct Data__InstructionDesc* instrList;
  struct Data__InstructionDesc* instrTail;
  struct Data__RegionDesc* regionList;
  struct Data__RegionDesc* nextRegion;
  struct Data__MergeDesc* merge;
  short int rangeL;
  short int rangeH;
} Data__GuardDesc;
typedef struct Data__GlobalRegionDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  struct Data__ResultDesc* nextResult;
  struct Data__InstructionDesc* instr;
  Data__Location location;
  struct Data__StructDesc* type;
  struct Data__OpndDesc* opndList;
  struct Data__RegionDesc* region;
  struct Data__InstructionDesc* nextInstr;
  struct Data__InstructionDesc* prevInstr;
  short int opcode;
  char _46pad, _47pad;
  unsigned int flags;
  int pos;
  struct Data__InstructionDesc* instrList;
  struct Data__InstructionDesc* instrTail;
  struct Data__RegionDesc* regionList;
  struct Data__RegionDesc* nextRegion;
  struct Data__MergeDesc* merge;
  short int rangeL;
  short int rangeH;
  struct Data__ObjectDesc* bodyOf;
  struct Data__InstructionDesc* enter;
  struct Data__InstructionDesc* exit;
} Data__GlobalRegionDesc;
typedef struct Data__GlobalRegionDesc* Data__GlobalRegion;
typedef struct Data__ObjectDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  struct Data__UsableDesc* currValue;
  Data__Info beInfo;
  Parameter__String name;
  struct Data__StructDesc* type;
  signed char mode;
  char _29pad, _30pad, _31pad;
  struct Data__ObjectDesc* leftObj;
  struct Data__ObjectDesc* rightObj;
  Data__Addressable localTo;
  struct Data__ObjectDesc* localDecl;
  short int moduleId;
  short int level;
  struct Data__UsableDesc* data;
  Data__GlobalRegion greg;
  int offset;
  unsigned int flags;
  unsigned int beFlags;
  int pos;
} Data__ObjectDesc;
typedef struct Data__ObjectDesc* Data__Object;
typedef struct Data__StructDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  struct Data__UsableDesc* currValue;
  Data__Info beInfo;
  signed char form;
  char _21pad, _22pad, _23pad;
  struct Data__StructDesc* base;
  Data__Object decl;
  int len;
  Data__Object obj;
  unsigned int flags;
  unsigned int beFlags;
  int size;
  short int align;
  char _54pad, _55pad;
  int pos;
} Data__StructDesc;
typedef struct Data__StructDesc* Data__Struct;
typedef struct Data__ResultDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  struct Data__ResultDesc* nextResult;
  struct Data__InstructionDesc* instr;
  Data__Location location;
  Data__Struct type;
} Data__ResultDesc;
typedef struct Data__ResultDesc* Data__Result;
typedef struct Data__MergeDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  Data__Result nextResult;
  struct Data__InstructionDesc* instr;
  Data__Location location;
  Data__Struct type;
  struct Data__OpndDesc* opndList;
  struct Data__RegionDesc* region;
  struct Data__InstructionDesc* nextInstr;
  struct Data__InstructionDesc* prevInstr;
  short int opcode;
  char _46pad, _47pad;
  unsigned int flags;
  int pos;
  struct Data__InstructionDesc* instrList;
  struct Data__InstructionDesc* instrTail;
  struct Data__RegionDesc* regionList;
  struct Data__RegionDesc* nextRegion;
  struct Data__MergeDesc* merge;
  short int rangeL;
  short int rangeH;
} Data__MergeDesc;
typedef struct Data__MergeDesc* Data__Merge;
typedef struct Data__RegionDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  Data__Result nextResult;
  struct Data__InstructionDesc* instr;
  Data__Location location;
  Data__Struct type;
  struct Data__OpndDesc* opndList;
  struct Data__RegionDesc* region;
  struct Data__InstructionDesc* nextInstr;
  struct Data__InstructionDesc* prevInstr;
  short int opcode;
  char _46pad, _47pad;
  unsigned int flags;
  int pos;
  struct Data__InstructionDesc* instrList;
  struct Data__InstructionDesc* instrTail;
  struct Data__RegionDesc* regionList;
  struct Data__RegionDesc* nextRegion;
  Data__Merge merge;
  short int rangeL;
  short int rangeH;
} Data__RegionDesc;
typedef struct Data__RegionDesc* Data__Region;
typedef struct Data__InstructionDesc {
  struct Data__OpndDesc* useList;
  Data__Info info;
  int marker;
  Data__Result nextResult;
  struct Data__InstructionDesc* instr;
  Data__Location location;
  Data__Struct type;
  struct Data__OpndDesc* opndList;
  Data__Region region;
  struct Data__InstructionDesc* nextInstr;
  struct Data__InstructionDesc* prevInstr;
  short int opcode;
  char _46pad, _47pad;
  unsigned int flags;
  int pos;
} Data__InstructionDesc;
typedef struct Data__InstructionDesc* Data__Instruction;
typedef struct Data__OpndDesc {
  struct Data__UsableDesc* arg;
  struct Data__OpndDesc* nextUse;
  struct Data__OpndDesc* nextOpnd;
  Data__Instruction instr;
  Data__Location location;
  int pos;
} Data__OpndDesc;
typedef struct Data__OpndDesc* Data__Opnd;
typedef struct Data__UsableDesc {
  Data__Opnd useList;
  Data__Info info;
  int marker;
} Data__UsableDesc;
typedef struct Data__UsableDesc* Data__Usable;
typedef struct Data__ConstDesc {
  Data__Opnd useList;
  Data__Info info;
  int marker;
  struct Data__ConstDesc* nextConst;
  Data__Struct type;
  Parameter__String string;
  int int_;
  int int2;
  unsigned int set;
  char _36pad, _37pad, _38pad, _39pad;
  double real;
  unsigned char preserve;
  char _49pad, _50pad, _51pad, _52pad, _53pad, _54pad, _55pad;
} Data__ConstDesc;
typedef struct Data__ConstDesc* Data__Const;
typedef struct Data__GateDesc {
  Data__Opnd useList;
  Data__Info info;
  int marker;
  Data__Result nextResult;
  Data__Instruction instr;
  Data__Location location;
  Data__Struct type;
  Data__Opnd opndList;
  Data__Region region;
  Data__Instruction nextInstr;
  Data__Instruction prevInstr;
  short int opcode;
  char _46pad, _47pad;
  unsigned int flags;
  int pos;
  Data__Object var;
  Data__Usable oldValue;
} Data__GateDesc;
typedef struct Data__GateDesc* Data__Gate;
typedef struct Data__GuardDesc* Data__Guard;
typedef struct Data__SymLocationDesc {
  Data__Addressable var;
  short int attrib;
  char _6pad, _7pad;
} Data__SymLocationDesc;
typedef struct Data__SymLocationDesc* Data__SymLocation;
#define Data__symLocObject -3
#define Data__symLocAddress -2
#define Data__symLocTypeTag -1
#define Data__symLocLength0 0
#define Data__objUndef 0
#define Data__objConst 1
#define Data__objType 2
#define Data__objVar 3
#define Data__objVarPar 4
#define Data__objField 5
#define Data__objProc 6
#define Data__objTBProc 7
#define Data__objModule 8
#define Data__objRestParam 9
#define Data__objIsUsed 31
#define Data__objIsForwardDecl 30
#define Data__objWasForwardDecl 29
#define Data__objContainsProc 28
#define Data__objInSymbolFile 27
#define Data__objIsParameter 26
#define Data__objIsReceiver 25
#define Data__objIsUsedNonlocal 24
#define Data__objHasBody 23
#define Data__objIsInitialized 22
#define Data__objIsTwisted 21
#define Data__objNotSideEffected 20
#define Data__objIsUpdated 19
#define Data__objAllowsSystemFlags 18
#define Data__objIsExported 0
#define Data__objIsExportedReadOnly 1
#define Data__objReadBeforeWrite 2
#define Data__objExportsBEInfo 3
#define Data__objAllowsUnderscore 4
#define Data__objNoLengthTag 5
#define Data__objNoTypeTag 6
#define Data__objNilCompat 7
#define Data__objIsSpecialCodeProc 8
#define Data__objAbstractTBProc 9
#define Data__objFinalTBProc 10
#define Data__objExportMask 0x7FFU
#define Data__strUndef 0
#define Data__strBoolean 1
#define Data__strChar8 2
#define Data__strChar16 3
#define Data__strShortInt 4
#define Data__strInteger 5
#define Data__strLongInt 6
#define Data__strHugeInt 7
#define Data__strReal 8
#define Data__strLongReal 9
#define Data__strComplex 10
#define Data__strLongComplex 11
#define Data__strSet8 12
#define Data__strSet16 13
#define Data__strSet32 14
#define Data__strSet64 15
#define Data__strByte 16
#define Data__strPtr 17
#define Data__strStringConst8 18
#define Data__strStringConst16 19
#define Data__strNil 20
#define Data__strNone 21
#define Data__strAddress 6
#define Data__strPointer 27
#define Data__strProc 28
#define Data__strArray 29
#define Data__strOpenArray 30
#define Data__strRecord 31
#define Data__grpInteger 32
#define Data__grpReal 33
#define Data__grpNumeric 34
#define Data__grpComplex 35
#define Data__grpChar 36
#define Data__grpSet 37
#define Data__grpString8 38
#define Data__grpString16 39
#define Data__grpStringConst 40
#define Data__grpAnyString 41
#define Data__grpArray 42
#define Data__grpCharArray 43
#define Data__grpPointer 44
#define Data__grpProc 45
#define Data__grpPtr 46
#define Data__grpStructured 47
#define Data__grpLong 48
#define Data__grpShort 49
#define Data__grpNilCompat 50
#define Data__grpShift 51
#define Data__grpGetPut 52
#define Data__grpAnyType 53
#define Data__grpOffset -32
#define Data__structInSymbolFile 31
#define Data__structEnableRestParam 30
#define Data__structIsExported 29
#define Data__maxStructFlag 28
#define Data__structExportsBEInfo 0
#define Data__structAllowsUnderscore 1
#define Data__structNotExtensible 2
#define Data__structNoDescriptor 3
#define Data__structNoLengthInfo 4
#define Data__structStaticPointer 5
#define Data__structDisableNew 6
#define Data__structUnion 7
#define Data__structCArrayAssign 8
#define Data__structAbstractType 9
#define Data__structVTableField 10
#define Data__structDisableStaticInstance 11
#define Data__structExportMask 0xFFFU
extern unsigned int Data__setMask[4];
#define Data__instrNotDead 0
#define Data__instrIsDisabled 1
#define Data__instrCheckOverflow 2
#define Data__instrCheckNil 3
#define Data__instrCheckDiv 4
#define Data__instrInitialize 5
#define Data__instrStackCheck 6
#define Data__instrUniqueResult 7
#define Data__instrGuardFor 8
#define Data__instrPoisonHeap 9
#define Data__minInstrFlag 10
#define Data__noSymbolTable -32768
extern Data__Struct Data__struct[22];
extern Data__Const Data__constNil;
extern Data__Const Data__constUndef;
extern void Data__InitConst(Data__Const c, Data__Struct type);
extern void Data__InitObject(Data__Object obj, const unsigned char* name__ref, int name_0d, signed char mode, int pos);
extern void Data__InitStruct(Data__Struct str, signed char form, int pos);
extern void Data__InitRegion(Data__Region region, int pos);
extern Data__SymLocation Data__CreateSymLocation(Data__Addressable var, short int attrib);
extern void Data__TransferResultList(Data__Result prevRes, Data__Result *saved, unsigned char restore);
extern void Data__TransferOperandList(Data__Opnd prevOpnd, Data__Opnd *saved, unsigned char restore);
extern void Data__InitGuard(Data__Guard guard, Data__Usable cond, short int opcode, int pos);
extern Data__Guard Data__CreateGuard(Data__Usable cond, short int opcode, int pos);
extern Data__Merge Data__CreateMerge(short int opcode);
extern Data__Const Data__GetIntConst(int value, Data__Struct type);
extern Data__Const Data__GetRealConst(double value, Data__Struct type);
extern Data__Const Data__GetSetConst(unsigned int value, Data__Struct type);
extern Data__Const Data__GetStringConst(unsigned char* value, int value_0d, int len, Data__Struct type);
extern Data__Const Data__GetRangeConst(int from, int to, Data__Struct type);
extern Data__Const Data__ConvertString(Data__Const const_, signed char to);
extern int Data__CompareStrings(Data__Const c1, Data__Const c2);
extern void Data__FreeConsts(void);
extern void Data__SortRanges(Data__Guard caseGuard);
extern signed char Data__OperatorSubclass(Data__Struct type, signed char typeForm);
typedef void(* _TBP_Data__OpndDesc_SwapArguments)(Data__Opnd opnd1, Data__Opnd opnd2);
#define _TBN_Data__OpndDesc_SwapArguments 1
extern void Data__OpndDesc_SwapArguments(Data__Opnd opnd1, Data__Opnd opnd2);
typedef void(* _TBP_Data__InstructionDesc_Operand)(Data__Instruction instr, Data__Usable arg);
#define _TBN_Data__InstructionDesc_Operand 5
extern void Data__InstructionDesc_Operand(Data__Instruction instr, Data__Usable arg);
typedef void(* _TBP_Data__InstructionDesc_UniqueOperand)(Data__Instruction instr, Data__Usable arg, Data__Location loc);
#define _TBN_Data__InstructionDesc_UniqueOperand 6
extern void Data__InstructionDesc_UniqueOperand(Data__Instruction instr, Data__Usable arg, Data__Location loc);
typedef void(* _TBP_Data__OpndDesc_DeleteOperand)(Data__Opnd opnd);
#define _TBN_Data__OpndDesc_DeleteOperand 2
extern void Data__OpndDesc_DeleteOperand(Data__Opnd opnd);
typedef void(* _TBP_Data__OpndDesc_ReplaceOperand)(Data__Opnd opnd, Data__Usable arg);
#define _TBN_Data__OpndDesc_ReplaceOperand 3
extern void Data__OpndDesc_ReplaceOperand(Data__Opnd opnd, Data__Usable arg);
typedef void(* _TBP_Data__UsableDesc_ReplaceUses)(Data__Usable of, Data__Usable with);
#define _TBN_Data__UsableDesc_ReplaceUses 1
extern void Data__UsableDesc_ReplaceUses(Data__Usable of, Data__Usable with);
typedef Data__Result(* _TBP_Data__InstructionDesc_AppendResult)(Data__Instruction instr, Data__Location location, Data__Struct type);
#define _TBN_Data__InstructionDesc_AppendResult 7
extern Data__Result Data__InstructionDesc_AppendResult(Data__Instruction instr, Data__Location location, Data__Struct type);
typedef void(* _TBP_Data__ResultDesc_DeleteResult)(Data__Result res);
#define _TBN_Data__ResultDesc_DeleteResult 2
extern void Data__ResultDesc_DeleteResult(Data__Result res);
typedef void(* _TBP_Data__RegionDesc_Insert)(Data__Region region, Data__Instruction instr);
#define _TBN_Data__RegionDesc_Insert 27
extern void Data__RegionDesc_Insert(Data__Region region, Data__Instruction instr);
typedef void(* _TBP_Data__RegionDesc_ReverseInstr)(Data__Region region);
#define _TBN_Data__RegionDesc_ReverseInstr 28
extern void Data__RegionDesc_ReverseInstr(Data__Region region);
typedef Data__GlobalRegion(* _TBP_Data__NodeDesc_Greg)(Data__Node n);
#define _TBN_Data__NodeDesc_Greg 0
extern Data__GlobalRegion Data__NodeDesc_Greg(Data__Node n);
typedef void(* _TBP_Data__InstructionDesc_Delete)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_Delete 8
extern void Data__InstructionDesc_Delete(Data__Instruction instr);
typedef void(* _TBP_Data__RegionDesc_MoveInstruction)(Data__Region to, Data__Instruction instr);
#define _TBN_Data__RegionDesc_MoveInstruction 29
extern void Data__RegionDesc_MoveInstruction(Data__Region to, Data__Instruction instr);
typedef void(* _TBP_Data__RegionDesc_MoveInstructions)(Data__Region to, Data__Region from);
#define _TBN_Data__RegionDesc_MoveInstructions 30
extern void Data__RegionDesc_MoveInstructions(Data__Region to, Data__Region from);
typedef void(* _TBP_Data__InstructionDesc_MoveResultList)(Data__Instruction toInstr, Data__Result prevResult);
#define _TBN_Data__InstructionDesc_MoveResultList 9
extern void Data__InstructionDesc_MoveResultList(Data__Instruction toInstr, Data__Result prevResult);
typedef void(* _TBP_Data__ResultDesc_MoveResultToEnd)(Data__Result res);
#define _TBN_Data__ResultDesc_MoveResultToEnd 3
extern void Data__ResultDesc_MoveResultToEnd(Data__Result res);
typedef void(* _TBP_Data__OpndDesc_MoveOperandToEnd)(Data__Opnd opnd);
#define _TBN_Data__OpndDesc_MoveOperandToEnd 4
extern void Data__OpndDesc_MoveOperandToEnd(Data__Opnd opnd);
typedef Data__Instruction(* _TBP_Data__RegionDesc_CreateInstruction)(Data__Region region, short int opcode, Data__Struct type, int pos);
#define _TBN_Data__RegionDesc_CreateInstruction 31
extern Data__Instruction Data__RegionDesc_CreateInstruction(Data__Region region, short int opcode, Data__Struct type, int pos);
typedef Data__Gate(* _TBP_Data__MergeDesc_CreateGate)(Data__Merge merge, short int opcode, Data__Object var, Data__Struct type);
#define _TBN_Data__MergeDesc_CreateGate 43
extern Data__Gate Data__MergeDesc_CreateGate(Data__Merge merge, short int opcode, Data__Object var, Data__Struct type);
typedef short int(* _TBP_Data__StructDesc_OpenDimensions)(Data__Struct type);
#define _TBN_Data__StructDesc_OpenDimensions 2
extern short int Data__StructDesc_OpenDimensions(Data__Struct type);
typedef short int(* _TBP_Data__StructDesc_Dimensions)(Data__Struct type);
#define _TBN_Data__StructDesc_Dimensions 3
extern short int Data__StructDesc_Dimensions(Data__Struct type);
typedef Data__Result(* _TBP_Data__InstructionDesc_GetResult)(Data__Instruction instr, Data__Addressable var, short int attrib);
#define _TBN_Data__InstructionDesc_GetResult 10
extern Data__Result Data__InstructionDesc_GetResult(Data__Instruction instr, Data__Addressable var, short int attrib);
typedef Data__Result(* _TBP_Data__InstructionDesc_LastResult)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_LastResult 11
extern Data__Result Data__InstructionDesc_LastResult(Data__Instruction instr);
typedef Data__Opnd(* _TBP_Data__InstructionDesc_GetOperand)(Data__Instruction instr, Data__Addressable var, short int attrib);
#define _TBN_Data__InstructionDesc_GetOperand 12
extern Data__Opnd Data__InstructionDesc_GetOperand(Data__Instruction instr, Data__Addressable var, short int attrib);
typedef Data__Opnd(* _TBP_Data__InstructionDesc_LastOperand)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_LastOperand 13
extern Data__Opnd Data__InstructionDesc_LastOperand(Data__Instruction instr);
typedef void(* _TBP_Data__InstructionDesc_SetOpndSymLoc)(Data__Instruction instr, Data__Addressable obj);
#define _TBN_Data__InstructionDesc_SetOpndSymLoc 14
extern void Data__InstructionDesc_SetOpndSymLoc(Data__Instruction instr, Data__Addressable obj);
typedef Data__Struct(* _TBP_Data__OpndDesc_OpndType)(Data__Opnd opnd);
#define _TBN_Data__OpndDesc_OpndType 5
extern Data__Struct Data__OpndDesc_OpndType(Data__Opnd opnd);
typedef short int(* _TBP_Data__InstructionDesc_ArgumentIndex)(Data__Instruction instr, Data__Usable arg);
#define _TBN_Data__InstructionDesc_ArgumentIndex 15
extern short int Data__InstructionDesc_ArgumentIndex(Data__Instruction instr, Data__Usable arg);
typedef short int(* _TBP_Data__OpndDesc_OperandIndex)(Data__Opnd opnd);
#define _TBN_Data__OpndDesc_OperandIndex 6
extern short int Data__OpndDesc_OperandIndex(Data__Opnd opnd);
typedef Data__Opnd(* _TBP_Data__InstructionDesc_NthOperand)(Data__Instruction instr, short int nth);
#define _TBN_Data__InstructionDesc_NthOperand 16
extern Data__Opnd Data__InstructionDesc_NthOperand(Data__Instruction instr, short int nth);
typedef Data__Usable(* _TBP_Data__InstructionDesc_NthArgument)(Data__Instruction instr, short int nth);
#define _TBN_Data__InstructionDesc_NthArgument 17
extern Data__Usable Data__InstructionDesc_NthArgument(Data__Instruction instr, short int nth);
typedef Data__Result(* _TBP_Data__InstructionDesc_NthResult)(Data__Instruction instr, short int nth);
#define _TBN_Data__InstructionDesc_NthResult 18
extern Data__Result Data__InstructionDesc_NthResult(Data__Instruction instr, short int nth);
typedef short int(* _TBP_Data__ResultDesc_ResultIndex)(Data__Result result);
#define _TBN_Data__ResultDesc_ResultIndex 4
extern short int Data__ResultDesc_ResultIndex(Data__Result result);
typedef short int(* _TBP_Data__InstructionDesc_NumOfOperands)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_NumOfOperands 19
extern short int Data__InstructionDesc_NumOfOperands(Data__Instruction instr);
typedef short int(* _TBP_Data__InstructionDesc_NumOfResults)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_NumOfResults 20
extern short int Data__InstructionDesc_NumOfResults(Data__Instruction instr);
typedef Data__Instruction(* _TBP_Data__RegionDesc_EnterInstr)(Data__Region region);
#define _TBN_Data__RegionDesc_EnterInstr 32
extern Data__Instruction Data__RegionDesc_EnterInstr(Data__Region region);
typedef Data__Instruction(* _TBP_Data__RegionDesc_ExitInstr)(Data__Region region);
#define _TBN_Data__RegionDesc_ExitInstr 33
extern Data__Instruction Data__RegionDesc_ExitInstr(Data__Region region);
typedef void(* _TBP_Data__InstructionDesc_MoveBehind)(Data__Instruction toMove, Data__Instruction prevInstr);
#define _TBN_Data__InstructionDesc_MoveBehind 21
extern void Data__InstructionDesc_MoveBehind(Data__Instruction toMove, Data__Instruction prevInstr);
typedef void(* _TBP_Data__InstructionDesc_MoveInFront)(Data__Instruction toMove, Data__Instruction nextInstr);
#define _TBN_Data__InstructionDesc_MoveInFront 22
extern void Data__InstructionDesc_MoveInFront(Data__Instruction toMove, Data__Instruction nextInstr);
typedef void(* _TBP_Data__RegionDesc_ClearInfo)(Data__Region region, int m);
#define _TBN_Data__RegionDesc_ClearInfo 34
extern void Data__RegionDesc_ClearInfo(Data__Region region, int m);
typedef void(* _TBP_Data__RegionDesc_ClearInstrInfo)(Data__Region region, int m);
#define _TBN_Data__RegionDesc_ClearInstrInfo 35
extern void Data__RegionDesc_ClearInstrInfo(Data__Region region, int m);
typedef void(* _TBP_Data__RegionDesc_ClearRegionInfo)(Data__Region region, int m);
#define _TBN_Data__RegionDesc_ClearRegionInfo 36
extern void Data__RegionDesc_ClearRegionInfo(Data__Region region, int m);
typedef Data__Object(* _TBP_Data__ObjectDesc_Module)(Data__Object obj);
#define _TBN_Data__ObjectDesc_Module 2
extern Data__Object Data__ObjectDesc_Module(Data__Object obj);
typedef void(* _TBP_Data__GlobalRegionDesc_NumberDominanceTree)(Data__GlobalRegion greg);
#define _TBN_Data__GlobalRegionDesc_NumberDominanceTree 43
extern void Data__GlobalRegionDesc_NumberDominanceTree(Data__GlobalRegion greg);
typedef unsigned char(* _TBP_Data__RegionDesc_Dominates)(Data__Region x, Data__Region y);
#define _TBN_Data__RegionDesc_Dominates 37
extern unsigned char Data__RegionDesc_Dominates(Data__Region x, Data__Region y);
typedef unsigned char(* _TBP_Data__RegionDesc_DominatesNR)(Data__Region x, Data__Region y);
#define _TBN_Data__RegionDesc_DominatesNR 38
extern unsigned char Data__RegionDesc_DominatesNR(Data__Region x, Data__Region y);
typedef short int(* _TBP_Data__InstructionDesc_Class)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_Class 23
extern short int Data__InstructionDesc_Class(Data__Instruction instr);
typedef short int(* _TBP_Data__InstructionDesc_Subclass)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_Subclass 24
extern short int Data__InstructionDesc_Subclass(Data__Instruction instr);
typedef unsigned char(* _TBP_Data__OpndDesc_ValueOperand)(Data__Opnd opnd);
#define _TBN_Data__OpndDesc_ValueOperand 7
extern unsigned char Data__OpndDesc_ValueOperand(Data__Opnd opnd);
typedef unsigned char(* _TBP_Data__OpndDesc_PassThroughOperand)(Data__Opnd opnd);
#define _TBN_Data__OpndDesc_PassThroughOperand 8
extern unsigned char Data__OpndDesc_PassThroughOperand(Data__Opnd opnd);
typedef Data__Merge(* _TBP_Data__RegionDesc_RegionMerge)(Data__Region r);
#define _TBN_Data__RegionDesc_RegionMerge 39
extern Data__Merge Data__RegionDesc_RegionMerge(Data__Region r);
typedef unsigned char(* _TBP_Data__InstructionDesc_MayTrap)(Data__Instruction instr);
#define _TBN_Data__InstructionDesc_MayTrap 25
extern unsigned char Data__InstructionDesc_MayTrap(Data__Instruction instr);
typedef Data__Instruction(* _TBP_Data__RegionDesc_CreateAdrInstr)(Data__Region region, Data__Usable arg, int pos);
#define _TBN_Data__RegionDesc_CreateAdrInstr 40
extern Data__Instruction Data__RegionDesc_CreateAdrInstr(Data__Region region, Data__Usable arg, int pos);
typedef Data__Instruction(* _TBP_Data__RegionDesc_CreateDyadicOp)(Data__Region region, short int opcode, Data__Struct type, Data__Usable opnd1, Data__Usable opnd2, int pos);
#define _TBN_Data__RegionDesc_CreateDyadicOp 41
extern Data__Instruction Data__RegionDesc_CreateDyadicOp(Data__Region region, short int opcode, Data__Struct type, Data__Usable opnd1, Data__Usable opnd2, int pos);
typedef Data__Instruction(* _TBP_Data__RegionDesc_CreateTypeCast)(Data__Region region, Data__Usable value, Data__Struct toType);
#define _TBN_Data__RegionDesc_CreateTypeCast 42
extern Data__Instruction Data__RegionDesc_CreateTypeCast(Data__Region region, Data__Usable value, Data__Struct toType);
typedef Data__Object(* _TBP_Data__InstructionDesc_GetReceiver)(Data__Instruction call);
#define _TBN_Data__InstructionDesc_GetReceiver 26
extern Data__Object Data__InstructionDesc_GetReceiver(Data__Instruction call);
typedef Data__Object(* _TBP_Data__OpndDesc_GetFormalParam)(Data__Opnd opnd);
#define _TBN_Data__OpndDesc_GetFormalParam 9
extern Data__Object Data__OpndDesc_GetFormalParam(Data__Opnd opnd);
extern struct _TD Data__InfoDesc_td;
extern struct _TD Data__NodeDesc_td;
extern struct _TD Data__UsableDesc_td;
extern struct _TD Data__LocationDesc_td;
extern struct _TD Data__SymLocationDesc_td;
extern struct _TD Data__OpndDesc_td;
extern struct _TD Data__ConstDesc_td;
extern struct _TD Data__ResultDesc_td;
extern struct _TD Data__AddressableDesc_td;
extern struct _TD Data__ObjectDesc_td;
extern struct _TD Data__StructDesc_td;
extern struct _TD Data__InstructionDesc_td;
extern struct _TD Data__GateDesc_td;
extern struct _TD Data__RegionDesc_td;
extern struct _TD Data__GuardDesc_td;
extern struct _TD Data__MergeDesc_td;
extern struct _TD Data__GlobalRegionDesc_td;
extern void Data_init(void);

#endif
