/* file generated by oo2c -- do not edit */
#ifndef _MODULE_Filenames_
#define _MODULE_Filenames_

extern void Filenames__GetPath(const unsigned char* full__ref, int full_0d, unsigned char* path, int path_0d, unsigned char* file, int file_0d);
extern void Filenames__GetExt(const unsigned char* full__ref, int full_0d, unsigned char* file, int file_0d, unsigned char* ext, int ext_0d);
extern void Filenames__GetFile(const unsigned char* full__ref, int full_0d, unsigned char* file, int file_0d);
extern void Filenames__AddExt(unsigned char* full, int full_0d, const unsigned char* file__ref, int file_0d, const unsigned char* ext__ref, int ext_0d);
extern void Filenames__AddPath(unsigned char* full, int full_0d, const unsigned char* path__ref, int path_0d, const unsigned char* file__ref, int file_0d);
extern void Filenames__BuildFilename(unsigned char* full, int full_0d, const unsigned char* path__ref, int path_0d, const unsigned char* file__ref, int file_0d, const unsigned char* ext__ref, int ext_0d);
extern void Filenames__ExpandPath(unsigned char* full, int full_0d, const unsigned char* path__ref, int path_0d);
extern void Filenames_init(void);

#endif
