/* file generated by oo2c -- do not edit */
#ifndef _MODULE_GenDecl_
#define _MODULE_GenDecl_

#include "Data.h"
typedef Data__Object* GenDecl__ObjectList;
extern GenDecl__ObjectList GenDecl__objList;
extern int GenDecl__objCount;
#define GenDecl__function 1
#define GenDecl__prototype 2
#define GenDecl__external 3
#define GenDecl__static 4
#define GenDecl__typeExpression 5
#define GenDecl__formalParam 6
#define GenDecl__sideEffectParam 7
#define GenDecl__sideEffectReference 8
#define GenDecl__doNotMark 9
#define GenDecl__ignoreMark 10
#define GenDecl__ignoreUsedDecl 11
#define GenDecl__ignoreOtherModule 12
#define GenDecl__noSemicolon 15
typedef struct GenDecl__SideEffectInfo {
  Data__Opnd opnd;
  Data__Result result;
  Data__Instruction exit;
  Data__Instruction enter;
  Data__Object obj;
  short int attrib;
  unsigned char passPerReference;
  unsigned char continue_;
} GenDecl__SideEffectInfo;
extern GenDecl__ObjectList GenDecl__tbCallList;
extern void GenDecl__AssignNames(Data__Object block);
extern void GenDecl__EnumerateSideEffects(Data__Object proc, GenDecl__SideEffectInfo *einfo, _Type einfo__tag);
#include "TextRider.h"
extern void GenDecl__NewLine(TextRider__Writer w, short int off);
extern void GenDecl__Declaration(TextRider__Writer w, Data__Object obj, unsigned int dmode, short int off);
extern void GenDecl__TypeDeclaration(TextRider__Writer w, Data__Struct t, unsigned int dmode, short int off);
extern void GenDecl__VarDeclaration(TextRider__Writer w, const unsigned char* name__ref, int name_0d, Data__Struct t, unsigned int dmode, short int off);
#include "GenConst.h"
extern void GenDecl__Strings(TextRider__Writer w, GenConst__StringList list);
extern void GenDecl__BuildObjList(Data__Object block);
extern void GenDecl__TypeDescrName(TextRider__Writer w, Data__Struct t, unsigned char variable);
extern void GenDecl__WriteScalarType(TextRider__Writer w, Data__Struct type, unsigned char unsigned_, unsigned char pointer);
extern void GenDecl__WriteScalarCast(TextRider__Writer w, Data__Struct type, unsigned char unsigned_, unsigned char pointer, unsigned char const_);
extern void GenDecl__RegisterTBCall(Data__Object proc);
extern void GenDecl__PatchTBCalls(TextRider__Writer w);
extern void GenDecl__ModuleDescriptor(TextRider__Writer w, Data__Object mod);
extern void GenDecl__TypeDescriptor(TextRider__Writer w, Data__Object mod, Data__Struct t, Data__Struct link, unsigned char extern_);
extern void GenDecl__Init(void);
extern struct _TD GenDecl__SideEffectInfo_td;
extern void GenDecl_init(void);

#endif
