/* file generated by oo2c -- do not edit */
#ifndef _MODULE_GenInclude_
#define _MODULE_GenInclude_

#include "TextRider.h"
extern void GenInclude__IncludeFile(TextRider__Writer w, const unsigned char* name__ref, int name_0d, const unsigned char* suffix__ref, int suffix_0d);
#include "Data.h"
extern void GenInclude__Include(TextRider__Writer w, Data__Object module, const unsigned char* suffix__ref, int suffix_0d, unsigned char ignoreFlag);
extern void GenInclude__AddOptions(void(* appCom)(const unsigned char* opt__ref, int opt_0d));
extern void GenInclude_init(void);

#endif
