/* file generated by oo2c -- do not edit */
#include "IntArith.h"
#include "Opcode.h"
#include "StdTypes.h"

/* local definitions */

/* function prototypes */
signed char IntArith__Sgn(int i);

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const char name[9];
} _n0 = {9, NULL, {"IntArith"}};
static struct _MD IntArith_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL
  }
};

/* local strings */

