/* file generated by oo2c -- do not edit */
#include "IntConv.h"
#include "CharClass.h"
#include "Strings.h"

/* local definitions */
typedef signed char IntConv__ConvResults;
static ConvTypes__ScanState IntConv__W;
static ConvTypes__ScanState IntConv__S;
static ConvTypes__ScanState IntConv__SI;

/* function prototypes */

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const void* list[5];
} _p0 = {5, NULL, {
  (const void*)&IntConv__FormatInt,
  (const void*)&IntConv__IsIntConvException,
  (const void*)&IntConv__LengthInt,
  (const void*)&IntConv__ScanInt,
  (const void*)&IntConv__ValueInt,
}};
static const struct {
  int length;
  void* pad;
  const void* list[1];
} _p1 = {0, NULL, {NULL
}};
static const struct {
  int length;
  void* pad;
  const char name[8];
} _n0 = {8, NULL, {"IntConv"}};
static struct _MD IntConv_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL,
    _p0.list,
    _p1.list,
    -493975604
  }
};

/* local strings */

