/* file generated by oo2c -- do not edit */
#ifndef _MODULE_LongInts_
#define _MODULE_LongInts_

#define LongInts__B 32768
typedef short int LongInts__LongInt[170];
extern int LongInts__MinDigit(LongInts__LongInt w);
extern void LongInts__MultDigit(LongInts__LongInt w, int digit, int k);
extern void LongInts__AddDigit(LongInts__LongInt w, int k);
extern void LongInts__DivDigit(LongInts__LongInt w, int digit, int *r);
extern void LongInts__TenPower(LongInts__LongInt x, short int power);
extern void LongInts__BPower(LongInts__LongInt x, short int power);
extern void LongInts_init(void);

#endif
