/* file generated by oo2c -- do not edit */
#include "LongInts.h"

/* local definitions */

/* function prototypes */

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const void* list[6];
} _p0 = {6, NULL, {
  (const void*)&LongInts__AddDigit,
  (const void*)&LongInts__BPower,
  (const void*)&LongInts__DivDigit,
  (const void*)&LongInts__MinDigit,
  (const void*)&LongInts__MultDigit,
  (const void*)&LongInts__TenPower,
}};
static const struct {
  int length;
  void* pad;
  const void* list[1];
} _p1 = {0, NULL, {NULL
}};
static const struct {
  int length;
  void* pad;
  const char name[9];
} _n0 = {9, NULL, {"LongInts"}};
static struct _MD LongInts_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL,
    _p0.list,
    _p1.list,
    -1503746394
  }
};

/* local strings */

