/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "Msg.d"

static _ModId _mid;

void Msg__InitContext(Msg__Context context, const Msg__String id__ref, int id_0d) {
  register int i0, i1;
  Msg__String id;
  char* _old_top_vs = _top_vs;
  _push_value(int, id, id__ref, id_0d);
  i0 = Strings__Length((const unsigned char*)(int)id, id_0d);
  i0++;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i0 < 0) _invalid_length(i0, _P(5803));
    _mem = GC_malloc_atomic(i0*1+8);
    if (!_mem) _new_failed(_P(5766));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i0;
    i0 = (int)_var;
  }
  *(void**)(int)context = (void*)i0;
  i1 = (int)*(void**)(int)context;
  i0 = *(int*)(i1-8);
  _string_copy(i1, (int)id, i0);
  _top_vs = _old_top_vs;
}

void Msg__ContextDesc_GetTemplate(Msg__Context context, Msg__Msg msg, Msg__LString templ, int templ_0d) {
  register int i0, i1;
  unsigned short int buffer[16384];
  _string_copy2l((int)templ, (int)_c1, templ_0d);
  LongStrings__Append((const unsigned short int*)(int)_c0, 2, (unsigned short int*)(int)templ, templ_0d);
  LongStrings__Append((const unsigned short int*)(int)_c2, 22, (unsigned short int*)(int)templ, templ_0d);
  LongStrings__Append((const unsigned short int*)(int)_c0, 2, (unsigned short int*)(int)templ, templ_0d);
  i0 = (int)msg + 16;
  i0 = (int)*(void**)i0;
  i1 = i0 == 0;
  if (i1) goto l1;
l0:
  i1 = i0 + 4;
  i1 = (int)*(void**)i1;
  _string_copy2l((int)buffer, i1, 16384);
  LongStrings__Append((const unsigned short int*)(int)buffer, 16384, (unsigned short int*)(int)templ, templ_0d);
  LongStrings__Append((const unsigned short int*)(int)_c3, 5, (unsigned short int*)(int)templ, templ_0d);
  LongStrings__Append((const unsigned short int*)(int)buffer, 16384, (unsigned short int*)(int)templ, templ_0d);
  LongStrings__Append((const unsigned short int*)(int)_c4, 2, (unsigned short int*)(int)templ, templ_0d);
  LongStrings__Append((const unsigned short int*)(int)_c0, 2, (unsigned short int*)(int)templ, templ_0d);
  i0 = (int)*(void**)i0;
  i1 = i0 != 0;
  if (i1) goto l0;
l1:
  ;
}

void Msg__InitAttribute(Msg__Attribute attr, const Msg__String name__ref, int name_0d) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  *(void**)(int)attr = (void*)0;
  i0 = Strings__Length((const unsigned char*)(int)name, name_0d);
  i1 = i0 + 1;
  i0 = (int)attr + 4;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i1 < 0) _invalid_length(i1, _P(7722));
    _mem = GC_malloc_atomic(i1*1+8);
    if (!_mem) _new_failed(_P(7684));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i1;
    i1 = (int)_var;
  }
  *(void**)i0 = (void*)i1;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-8);
  _string_copy(i0, (int)name, i1);
  _top_vs = _old_top_vs;
}

void Msg__AttributeDesc_ReplacementText(Msg__Attribute attr, Msg__LString text, int text_0d) {
}

Msg__Msg Msg__New(Msg__Context context, int code) {
  register int i0, i1, i2;
  {
    char *_mem, *_var;
    _mem = GC_malloc(20+8);
    if (!_mem) _new_failed(_P(8449));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Msg__MsgDesc_td.td;
    i0 = (int)_var;
  }
  i1 = i0 + 4;
  *(void**)i1 = (void*)0;
  i2 = i0 + 8;
  *(void**)i0 = (void*)0;
  i1 = i0 + 12;
  *(int*)i2 = code;
  i2 = i0 + 16;
  *(void**)i1 = (void*)(int)context;
  *(void**)i2 = (void*)0;
  return (void*)i0;
}

void Msg__MsgDesc_SetAttribute_Insert(Msg__Attribute *aList, Msg__Attribute attr) {
  register int i0, i1, i2, i3;
  i2 = (int)*aList;
  i0 = i2 == 0;
  if (i0) goto l2;
  i1 = i2 + 4;
  i0 = (int)*(void**)i1;
  i1 = (int)attr + 4;
  i1 = (int)*(void**)i1;
  i3 = strcmp((const char*) i0, (const char*) i1) == 0;
  if (i3) goto l1;
  i1 = strcmp((const char*) i0, (const char*) i1) > 0;
  if (i1) goto l0;
  i1 = (int)*(void**)i2;
  Msg__MsgDesc_SetAttribute_Insert((Msg__Attribute *)i2, (Msg__Attribute)(int)attr);
  goto l3;
l0:
  *(void**)(int)attr = (void*)i2;
  *aList = (void*)(int)attr;
  goto l3;
l1:
  i2 = (int)*(void**)i2;
  *(void**)(int)attr = (void*)i2;
  *aList = (void*)(int)attr;
  goto l3;
l2:
  *aList = (void*)(int)attr;
l3:
  ;
}

void Msg__MsgDesc_SetAttribute(Msg__Msg msg, Msg__Attribute attr) {
  register int i0, i1;
  i0 = (int)msg + 16;
  i1 = (int)*(void**)i0;
  Msg__MsgDesc_SetAttribute_Insert((Msg__Attribute *)i0, (Msg__Attribute)(int)attr);
}

Msg__Attribute Msg__MsgDesc_GetAttribute(Msg__Msg msg, const Msg__String name, int name_0d) {
  register int i0, i1, i2, i3;
  i0 = (int)msg + 16;
  i2 = (int)*(void**)i0;
  i0 = i2 == 0;
  if (i0) goto l1;
  i1 = i2 + 4;
  i1 = (int)*(void**)i1;
  i0 = strcmp((const char*) (int)name, (const char*) i1) == 0;
  if (i0) goto l1;
  i3 = i2;
l0:
  i3 = (int)*(void**)i3;
  i1 = i3 == 0;
  if (i1) goto l2;
  i1 = i3 + 4;
  i1 = (int)*(void**)i1;
  i1 = strcmp((const char*) (int)name, (const char*) i1) != 0;
  if (i1) goto l0;
  goto l2;
l1:
  i3 = i2;
l2:
  return (void*)i3;
}

void Msg__MsgDesc_GetLText(Msg__Msg msg, Msg__LString text, int text_0d) {
  register int i0, i1, i2, i3, i4;
  unsigned short int attrName[131];
  unsigned char found;
  unsigned short int insert[16384];
  unsigned char num[48];
  short int pos;
  i2 = (int)msg + 12;
  i1 = (int)*(void**)i2;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[0];
  ((void(*)(Msg__Context, Msg__Msg, Msg__LString, int templ_0d))i0)((Msg__Context)i1, (Msg__Msg)(int)msg, (Msg__LString)(int)text, text_0d);
  i0 = (int)msg + 16;
  i1 = (int)*(void**)i0;
  i0 = i1 != 0;
  if (i0) goto l0;
  goto l6;
l0:
l1:
  i0 = i1 + 4;
  i0 = (int)*(void**)i0;
  _string_copy2l((int)attrName, i0, 131);
  LongStrings__Insert((const unsigned short int*)(int)_c5, 3, (short int)0, (unsigned short int*)(int)attrName, 131);
  LongStrings__Append((const unsigned short int*)(int)_c4, 2, (unsigned short int*)(int)attrName, 131);
  found = (unsigned char)i4;
  pos = (short int)i3;
  found = (unsigned char)i4;
  pos = (short int)i3;
  LongStrings__FindNext((const unsigned short int*)(int)attrName, 131, (const unsigned short int*)(int)text, text_0d, (short int)0, (unsigned char *)(int)&found, (short int *)(int)&pos);
  if (found) goto l2;
  i4 = 0;
  i3 = pos;
  goto l5;
l2:
  i3 = *(int*)(i1-4);
  i4 = (int)((_Type)i3)->tbprocs[0];
  i3 = pos;
l3:
  i0 = LongStrings__Length((const unsigned short int*)(int)attrName, 131);
  LongStrings__Delete((unsigned short int*)(int)text, text_0d, (short int)i3, (short int)i0);
  ((void(*)(Msg__Attribute, Msg__LString, int text_0d))i4)((Msg__Attribute)i1, (Msg__LString)(int)insert, 16384);
  LongStrings__Insert((const unsigned short int*)(int)insert, 16384, (short int)i3, (unsigned short int*)(int)text, text_0d);
  i0 = LongStrings__Length((const unsigned short int*)(int)insert, 16384);
  i0 += i3;
  found = (unsigned char)1;
  pos = (short int)i3;
  found = (unsigned char)1;
  pos = (short int)i3;
  LongStrings__FindNext((const unsigned short int*)(int)attrName, 131, (const unsigned short int*)(int)text, text_0d, (short int)i0, (unsigned char *)(int)&found, (short int *)(int)&pos);
  if (!(found)) goto l4;
  i3 = pos;
  goto l3;
l4:
  i4 = found;
  i3 = pos;
l5:
  i1 = (int)*(void**)i1;
  i0 = i1 != 0;
  if (i0) goto l1;
l6:
  found = (unsigned char)i4;
  pos = (short int)i3;
  found = (unsigned char)i4;
  pos = (short int)i3;
  LongStrings__FindNext((const unsigned short int*)(int)_c6, 15, (const unsigned short int*)(int)text, text_0d, (short int)0, (unsigned char *)(int)&found, (short int *)(int)&pos);
  if (!(found)) goto l7;
  LongStrings__Delete((unsigned short int*)(int)text, text_0d, (short int)pos, (short int)14);
  i2 = (int)*(void**)i2;
  i2 = (int)*(void**)i2;
  _string_copy2l((int)insert, i2, 16384);
  LongStrings__Insert((const unsigned short int*)(int)insert, 16384, (short int)pos, (unsigned short int*)(int)text, text_0d);
l7:
  LongStrings__FindNext((const unsigned short int*)(int)_c7, 12, (const unsigned short int*)(int)text, text_0d, (short int)0, (unsigned char *)(int)&found, (short int *)(int)&pos);
  if (!(found)) goto l8;
  i0 = (int)msg + 8;
  LongStrings__Delete((unsigned short int*)(int)text, text_0d, (short int)pos, (short int)11);
  i0 = *(int*)i0;
  IntStr__IntToStr((int)i0, (unsigned char*)(int)num, 48);
  _string_copy2l((int)insert, (int)num, 16384);
  LongStrings__Insert((const unsigned short int*)(int)insert, 16384, (short int)pos, (unsigned short int*)(int)text, text_0d);
l8:
  ;
}

void Msg__MsgDesc_GetText(Msg__Msg msg, Msg__String text, int text_0d) {
  register int i0, i1, i2, i3;
  unsigned short int buffer[65535];
  i0 = *(int*)((int)msg-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((void(*)(Msg__Msg, Msg__LString, int text_0d))i0)((Msg__Msg)(int)msg, (Msg__LString)(int)buffer, 65535);
  i1 = -1;
l0:
  i1++;
  i2 = (int)_ashl(i1, 1, (unsigned int));
  i2 = (int)buffer + i2;
  i0 = *(unsigned short int*)i2;
  i3 = (int)text + i1;
  i2 = i0 <= 255;
  if (i2) goto l1;
  *(unsigned char*)i3 = 63;
  goto l2;
l1:
  *(unsigned char*)i3 = i0;
l2:
  i2 = *(unsigned char*)i3;
  i2 = i2 != 0;
  if (i2) goto l0;
}

void Msg__InitMsgList(Msg__MsgList l) {
  register int i0;
  i0 = (int)l + 4;
  *(int*)(int)l = 0;
  *(void**)i0 = (void*)0;
  i0 = (int)l + 8;
  *(void**)i0 = (void*)0;
}

Msg__MsgList Msg__NewMsgList(void) {
  register int i0;
  {
    char *_mem, *_var;
    _mem = GC_malloc(12+8);
    if (!_mem) _new_failed(_P(12565));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Msg__MsgListDesc_td.td;
    i0 = (int)_var;
  }
  Msg__InitMsgList((Msg__MsgList)i0);
  return (void*)i0;
}

void Msg__MsgListDesc_Append(Msg__MsgList l, Msg__Msg msg) {
  register int i0, i1, i2;
  i1 = (int)l + 4;
  i0 = (int)*(void**)i1;
  i2 = i0 == 0;
  i0 = (int)l + 8;
  *(void**)(int)msg = (void*)0;
  if (i2) goto l0;
  i2 = (int)*(void**)i0;
  i1 = (int)msg + 4;
  *(void**)i1 = (void*)i2;
  *(void**)i2 = (void*)(int)msg;
  goto l1;
l0:
  i2 = (int)msg + 4;
  *(void**)i1 = (void*)(int)msg;
  *(void**)i2 = (void*)0;
l1:
  *(void**)i0 = (void*)(int)msg;
  i0 = *(int*)(int)l;
  i0++;
  *(int*)(int)l = i0;
}

void Msg__MsgListDesc_AppendList(Msg__MsgList l, Msg__MsgList source) {
  register int i0, i1, i2, i3, i4;
  i3 = *(int*)(int)source;
  i0 = i3 == 0;
  if (i0) goto l1;
  i0 = *(int*)(int)l;
  i2 = i0 == 0;
  if (i2) goto l0;
  i3 = i0 + i3;
  i0 = (int)l + 8;
  *(int*)(int)l = i3;
  i4 = (int)*(void**)i0;
  i3 = (int)source + 4;
  i1 = (int)*(void**)i3;
  *(void**)i4 = (void*)i1;
  i2 = (int)source + 8;
  i3 = i1 + 4;
  i2 = (int)*(void**)i2;
  *(void**)i3 = (void*)i4;
  *(void**)i0 = (void*)i2;
  Msg__InitMsgList((Msg__MsgList)(int)source);
  goto l1;
l0:
  (void)memcpy((void*) (int)l, (const void*) (int)source, 12);
l1:
  ;
}

Msg__IntAttribute Msg__NewIntAttrib(const Msg__String name__ref, int name_0d, int value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  {
    char *_mem, *_var;
    _mem = GC_malloc(12+8);
    if (!_mem) _new_failed(_P(13911));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Msg__IntAttributeDesc_td.td;
    i0 = (int)_var;
  }
  i1 = i0 + 8;
  Msg__InitAttribute((Msg__Attribute)i0, (const Msg__String)(int)name, name_0d);
  *(int*)i1 = value;
  _top_vs = _old_top_vs;
  return (void*)i0;
}

void Msg__MsgDesc_SetIntAttrib(Msg__Msg msg, const Msg__String name__ref, int name_0d, int value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  i0 = (int)Msg__NewIntAttrib((const Msg__String)(int)name, name_0d, (int)value);
  i1 = *(int*)((int)msg-4);
  i1 = (int)((_Type)i1)->tbprocs[0];
  ((void(*)(Msg__Msg, Msg__Attribute))i1)((Msg__Msg)(int)msg, (Msg__Attribute)i0);
  _top_vs = _old_top_vs;
}

void Msg__IntAttributeDesc_ReplacementText(Msg__IntAttribute attr, Msg__LString text, int text_0d) {
  register int i0;
  unsigned char num[48];
  i0 = (int)attr + 8;
  i0 = *(int*)i0;
  IntStr__IntToStr((int)i0, (unsigned char*)(int)num, 48);
  _string_copy2l((int)text, (int)num, text_0d);
}

Msg__StringAttribute Msg__NewStringAttrib(const Msg__String name__ref, int name_0d, Msg__StringPtr value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  {
    char *_mem, *_var;
    _mem = GC_malloc(12+8);
    if (!_mem) _new_failed(_P(14555));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Msg__StringAttributeDesc_td.td;
    i0 = (int)_var;
  }
  i1 = i0 + 8;
  Msg__InitAttribute((Msg__Attribute)i0, (const Msg__String)(int)name, name_0d);
  *(void**)i1 = (void*)(int)value;
  _top_vs = _old_top_vs;
  return (void*)i0;
}

void Msg__MsgDesc_SetStringAttrib(Msg__Msg msg, const Msg__String name__ref, int name_0d, Msg__StringPtr value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  i0 = (int)Msg__NewStringAttrib((const Msg__String)(int)name, name_0d, (Msg__StringPtr)(int)value);
  i1 = *(int*)((int)msg-4);
  i1 = (int)((_Type)i1)->tbprocs[0];
  ((void(*)(Msg__Msg, Msg__Attribute))i1)((Msg__Msg)(int)msg, (Msg__Attribute)i0);
  _top_vs = _old_top_vs;
}

void Msg__StringAttributeDesc_ReplacementText(Msg__StringAttribute attr, Msg__LString text, int text_0d) {
  register int i0;
  i0 = (int)attr + 8;
  i0 = (int)*(void**)i0;
  _string_copy2l((int)text, i0, text_0d);
}

Msg__LStringAttribute Msg__NewLStringAttrib(const Msg__String name__ref, int name_0d, Msg__LStringPtr value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  {
    char *_mem, *_var;
    _mem = GC_malloc(12+8);
    if (!_mem) _new_failed(_P(15162));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Msg__LStringAttributeDesc_td.td;
    i0 = (int)_var;
  }
  i1 = i0 + 8;
  Msg__InitAttribute((Msg__Attribute)i0, (const Msg__String)(int)name, name_0d);
  *(void**)i1 = (void*)(int)value;
  _top_vs = _old_top_vs;
  return (void*)i0;
}

void Msg__MsgDesc_SetLStringAttrib(Msg__Msg msg, const Msg__String name__ref, int name_0d, Msg__LStringPtr value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  i0 = (int)Msg__NewLStringAttrib((const Msg__String)(int)name, name_0d, (Msg__LStringPtr)(int)value);
  i1 = *(int*)((int)msg-4);
  i1 = (int)((_Type)i1)->tbprocs[0];
  ((void(*)(Msg__Msg, Msg__Attribute))i1)((Msg__Msg)(int)msg, (Msg__Attribute)i0);
  _top_vs = _old_top_vs;
}

void Msg__LStringAttributeDesc_ReplacementText(Msg__LStringAttribute attr, Msg__LString text, int text_0d) {
  register int i0;
  i0 = (int)attr + 8;
  i0 = (int)*(void**)i0;
  _string_copyl((int)text, i0, text_0d);
}

Msg__MsgAttribute Msg__NewMsgAttrib(const Msg__String name__ref, int name_0d, Msg__Msg value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  {
    char *_mem, *_var;
    _mem = GC_malloc(12+8);
    if (!_mem) _new_failed(_P(15756));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Msg__MsgAttributeDesc_td.td;
    i0 = (int)_var;
  }
  i1 = i0 + 8;
  Msg__InitAttribute((Msg__Attribute)i0, (const Msg__String)(int)name, name_0d);
  *(void**)i1 = (void*)(int)value;
  _top_vs = _old_top_vs;
  return (void*)i0;
}

void Msg__MsgDesc_SetMsgAttrib(Msg__Msg msg, const Msg__String name__ref, int name_0d, Msg__Msg value) {
  register int i0, i1;
  Msg__String name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  i0 = (int)Msg__NewMsgAttrib((const Msg__String)(int)name, name_0d, (Msg__Msg)(int)value);
  i1 = *(int*)((int)msg-4);
  i1 = (int)((_Type)i1)->tbprocs[0];
  ((void(*)(Msg__Msg, Msg__Attribute))i1)((Msg__Msg)(int)msg, (Msg__Attribute)i0);
  _top_vs = _old_top_vs;
}

void Msg__MsgAttributeDesc_ReplacementText(Msg__MsgAttribute attr, Msg__LString text, int text_0d) {
  register int i0, i1;
  i0 = (int)attr + 8;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[2];
  ((void(*)(Msg__Msg, Msg__LString, int text_0d))i1)((Msg__Msg)i0, (Msg__LString)(int)text, text_0d);
}

Msg__StringPtr Msg__GetStringPtr(const Msg__String str__ref, int str_0d) {
  register int i0, i1;
  Msg__String str;
  char* _old_top_vs = _top_vs;
  _push_value(int, str, str__ref, str_0d);
  i0 = Strings__Length((const unsigned char*)(int)str, str_0d);
  i0++;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i0 < 0) _invalid_length(i0, _P(16465));
    _mem = GC_malloc_atomic(i0*1+8);
    if (!_mem) _new_failed(_P(16437));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i0;
    i1 = (int)_var;
  }
  i0 = *(int*)(i1-8);
  _string_copy(i1, (int)str, i0);
  _top_vs = _old_top_vs;
  return (void*)i1;
}

Msg__LStringPtr Msg__GetLStringPtr(const Msg__LString str__ref, int str_0d) {
  register int i0, i1;
  Msg__LString str;
  char* _old_top_vs = _top_vs;
  _push_value(int, str, str__ref, str_0d*2);
  i0 = LongStrings__Length((const unsigned short int*)(int)str, str_0d);
  i0++;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i0 < 0) _invalid_length(i0, _P(16718));
    _mem = GC_malloc_atomic(i0*2+8);
    if (!_mem) _new_failed(_P(16686));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i0;
    i1 = (int)_var;
  }
  i0 = *(int*)(i1-8);
  _string_copyl(i1, (int)str, i0);
  _top_vs = _old_top_vs;
  return (void*)i1;
}

void Msg_init(void) {
  _mid = _register_module(&Msg_md.md, &Msg__MsgAttributeDesc_td.td);
}
