/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "Parameter.d"

static _ModId _mid;

void Parameter__Warning(const unsigned char* msg__ref, int msg_0d) {
  unsigned char* msg;
  char* _old_top_vs = _top_vs;
  _push_value(int, msg, msg__ref, msg_0d);
  Out__String((const unsigned char*)(int)_c0, 10);
  Out__String((const unsigned char*)(int)msg, msg_0d);
  Out__Ln();
  _top_vs = _old_top_vs;
}

void Parameter__FatalError(const unsigned char* msg__ref, int msg_0d) {
  unsigned char* msg;
  char* _old_top_vs = _top_vs;
  _push_value(int, msg, msg__ref, msg_0d);
  Out__String((const unsigned char*)(int)_c1, 8);
  Out__String((const unsigned char*)(int)msg, msg_0d);
  Out__Ln();
  _halt(1);
  _top_vs = _old_top_vs;
}

unsigned char Parameter__IsAlpha(unsigned char ch) {
  register int i0, i1;
  i0 = _cap((int)ch);
  i1 = i0 < 65;
  if (i1) goto l0;
  i1 = i0 <= 90;
  if (i1) goto l1;
l0:
  i0 = i0 == 95;
  if (i0) goto l1;
  i0 = 0;
  goto l2;
l1:
  i0 = 1;
l2:
  return (unsigned char)i0;
}

unsigned char Parameter__IsNum(unsigned char ch) {
  register int i0;
  i0 = (int)ch < 48;
  if (i0) goto l0;
  i0 = (int)ch <= 57;
  if (i0) goto l1;
l0:
  i0 = 0;
  goto l2;
l1:
  i0 = 1;
l2:
  return (unsigned char)i0;
}

void Parameter__StreamDesc_Remove(Parameter__Stream s) {
  register int i0;
  i0 = (int)*(void**)(int)s;
  Parameter__in = (void*)i0;
}

void Parameter__StreamDesc_NextChar(Parameter__Stream s) {
  register int i0;
  i0 = (int)s + 6;
  i0 = *(unsigned char*)i0;
  if (!(i0)) goto l1;
  i0 = (int)*(void**)(int)s;
  i0 = i0 == 0;
  if (i0) goto l0;
  i0 = *(int*)((int)s-4);
  i0 = (int)((_Type)i0)->tbprocs[0];
  ((void(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
l0:
  i0 = (int)s + 5;
  *(unsigned char*)i0 = 0;
l1:
  ;
}

void Parameter__StreamDesc_Install(Parameter__Stream s) {
  register int i0, i1;
  i0 = (int)Parameter__in;
  i1 = i0 != 0;
  *(void**)(int)s = (void*)i0;
  if (i1) goto l0;
  i0 = (int)s + 4;
  *(signed char*)i0 = 0;
  goto l1;
l0:
  i0 += 4;
  i1 = *(signed char*)i0;
  i0 = (int)s + 4;
  i1++;
  *(signed char*)i0 = i1;
  i0 = *(signed char*)i0;
  i0 = i0 < 8;
  if (i0) goto l1;
  Parameter__FatalError((const unsigned char*)(int)_c2, 36);
l1:
  i0 = (int)s + 6;
  *(unsigned char*)i0 = 0;
  i0 = (int)s + 7;
  *(unsigned char*)i0 = 0;
  Parameter__in = (void*)(int)s;
  i0 = (int)Parameter__in;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[1];
  ((void(*)(Parameter__Stream))i1)((Parameter__Stream)i0);
}

void Parameter__StreamDesc_Error(Parameter__Stream s, int pos, const unsigned char* msg, int msg_0d) {
  register int i0;
  i0 = (int)s + 7;
  *(unsigned char*)i0 = 1;
  i0 = (int)s + 6;
  *(unsigned char*)i0 = 1;
  i0 = (int)s + 5;
  *(unsigned char*)i0 = 0;
  Parameter__err = 1;
}

int Parameter__StreamDesc_CurrPos(Parameter__Stream s) {
}

void Parameter__StreamDesc_SkipWhitespace(Parameter__Stream s) {
  register int i0, i1, i2, i3, i4;
  i2 = (int)s + 6;
  i3 = (int)s + 5;
l0:
  i1 = *(unsigned char*)i2;
  if (i1) goto l2;
  i4 = *(unsigned char*)i3;
  i0 = i4 > 32;
  if (i0) goto l2;
  i4 = *(int*)((int)s-4);
  i4 = (int)((_Type)i4)->tbprocs[1];
l1:
  ((void(*)(Parameter__Stream))i4)((Parameter__Stream)(int)s);
  i1 = *(unsigned char*)i2;
  if (i1) goto l2;
  i1 = *(unsigned char*)i3;
  i1 = i1 <= 32;
  if (i1) goto l1;
l2:
  i1 = *(unsigned char*)i3;
  i1 = i1 != 35;
  if (i1) goto l4;
  i1 = *(unsigned char*)i2;
  if (i1) goto l4;
  i1 = *(int*)((int)s-4);
  i1 = (int)((_Type)i1)->tbprocs[1];
l3:
  ((void(*)(Parameter__Stream))i1)((Parameter__Stream)(int)s);
  i4 = *(unsigned char*)i2;
  if (i4) goto l4;
  i4 = *(unsigned char*)i3;
  i4 = i4 != 10;
  if (i4) goto l3;
l4:
  i1 = *(unsigned char*)i2;
  if (i1) goto l5;
  i1 = *(unsigned char*)i3;
  i4 = i1 <= 32;
  if (i4) goto l0;
  i1 = i1 == 35;
  if (i1) goto l0;
l5:
  i0 = (int)Parameter__in;
  i1 = (int)s == i0;
  if (i1) goto l6;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[5];
  ((void(*)(Parameter__Stream))i1)((Parameter__Stream)i0);
l6:
  ;
}

void Parameter__StreamDesc_ReadIdent(Parameter__Stream s, unsigned char* ident, int ident_0d) {
  register int i0, i1, i2, i3, i4, i5, i6, i7;
  i6 = *(int*)((int)s-4);
  i0 = (int)((_Type)i6)->tbprocs[5];
  i1 = (int)((_Type)i6)->tbprocs[4];
  i5 = (int)s + 8;
  ((void(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
  i0 = ((int(*)(Parameter__Stream))i1)((Parameter__Stream)(int)s);
  *(int*)i5 = i0;
  i0 = (int)s + 6;
  i0 = *(unsigned char*)i0;
  if (i0) goto l3;
  i1 = (int)s + 5;
  i4 = *(unsigned char*)i1;
  i2 = Parameter__IsAlpha((unsigned char)i4);
  if (!(i2)) goto l3;
  i7 = (int)((_Type)i6)->tbprocs[1];
  i4 = 0;
l0:
  i3 = ident_0d > i4;
  if (!(i3)) goto l1;
  i3 = *(unsigned char*)i1;
  i0 = (int)ident + i4;
  *(unsigned char*)i0 = i3;
l1:
  ((void(*)(Parameter__Stream))i7)((Parameter__Stream)(int)s);
  i0 = *(unsigned char*)i1;
  i3 = Parameter__IsAlpha((unsigned char)i0);
  i4++;
  if (i3) goto l0;
  i0 = Parameter__IsNum((unsigned char)i0);
  if (i0) goto l0;
  i3 = ident_0d > i4;
  if (i3) goto l2;
  i7 = (int)((_Type)i6)->tbprocs[3];
  i3 = ident_0d - 1;
  i5 = *(int*)i5;
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i7)((Parameter__Stream)(int)s, (int)i5, (const unsigned char*)(int)_c3, 20);
  i7 = (int)ident + i3;
  *(unsigned char*)i7 = 0;
  goto l4;
l2:
  i3 = (int)ident + i4;
  *(unsigned char*)i3 = 0;
  goto l4;
l3:
  i6 = (int)((_Type)i6)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i6)((Parameter__Stream)(int)s, (int)-2, (const unsigned char*)(int)_c4, 20);
l4:
  ;
}

void Parameter__StreamDesc_ReadInteger(Parameter__Stream s, unsigned char* num, int num_0d) {
  register int i0, i1, i2, i3, i4, i5, i6;
  i5 = *(int*)((int)s-4);
  i0 = (int)((_Type)i5)->tbprocs[5];
  i1 = (int)((_Type)i5)->tbprocs[4];
  i4 = (int)s + 8;
  ((void(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
  i0 = ((int(*)(Parameter__Stream))i1)((Parameter__Stream)(int)s);
  *(int*)i4 = i0;
  i0 = (int)s + 6;
  i0 = *(unsigned char*)i0;
  if (i0) goto l0;
  i0 = (int)s + 5;
  i3 = *(unsigned char*)i0;
  i2 = Parameter__IsNum((unsigned char)i3);
  if (i2) goto l1;
  i2 = i3 == 45;
  if (i2) goto l1;
  i3 = i3 == 43;
  if (i3) goto l1;
l0:
  i5 = (int)((_Type)i5)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i5)((Parameter__Stream)(int)s, (int)-2, (const unsigned char*)(int)_c6, 17);
  goto l5;
l1:
  i2 = (int)((_Type)i5)->tbprocs[1];
  i3 = 0;
l2:
  i1 = num_0d > i3;
  if (!(i1)) goto l3;
  i1 = *(unsigned char*)i0;
  i6 = (int)num + i3;
  *(unsigned char*)i6 = i1;
l3:
  i3++;
  ((void(*)(Parameter__Stream))i2)((Parameter__Stream)(int)s);
  i1 = *(unsigned char*)i0;
  i1 = Parameter__IsNum((unsigned char)i1);
  if (i1) goto l2;
  i1 = num_0d > i3;
  if (i1) goto l4;
  i2 = (int)((_Type)i5)->tbprocs[3];
  i1 = num_0d - 1;
  i4 = *(int*)i4;
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i2)((Parameter__Stream)(int)s, (int)i4, (const unsigned char*)(int)_c5, 17);
  i2 = (int)num + i1;
  *(unsigned char*)i2 = 0;
  goto l5;
l4:
  i1 = (int)num + i3;
  *(unsigned char*)i1 = 0;
l5:
  ;
}

void Parameter__StreamDesc_ReadString(Parameter__Stream s, unsigned char* str, int str_0d) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  i6 = *(int*)((int)s-4);
  i5 = (int)s + 5;
  i1 = (int)((_Type)i6)->tbprocs[5];
  i7 = (int)s + 8;
  i0 = (int)((_Type)i6)->tbprocs[4];
  ((void(*)(Parameter__Stream))i1)((Parameter__Stream)(int)s);
  i0 = ((int(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
  *(int*)i7 = i0;
  i4 = *(unsigned char*)i5;
  i0 = i4 == 39;
  if (i0) goto l0;
  i0 = i4 != 34;
  if (i0) goto l7;
l0:
  i0 = (int)((_Type)i6)->tbprocs[1];
  ((void(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
  i1 = *(unsigned char*)i5;
  i3 = i1 < 32;
  if (i3) goto l3;
  i2 = i1 == i4;
  if (i2) goto l3;
  i8 = 0;
l1:
  i3 = str_0d > i8;
  if (!(i3)) goto l2;
  i3 = *(unsigned char*)i5;
  i1 = (int)str + i8;
  *(unsigned char*)i1 = i3;
l2:
  ((void(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
  i3 = *(unsigned char*)i5;
  i8++;
  i1 = i3 < 32;
  if (i1) goto l4;
  i3 = i3 != i4;
  if (i3) goto l1;
  goto l4;
l3:
  i8 = 0;
l4:
  i3 = *(unsigned char*)i5;
  i3 = i3 < 32;
  if (i3) goto l6;
  i3 = str_0d <= i8;
  ((void(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
  if (i3) goto l5;
  i3 = (int)str + i8;
  *(unsigned char*)i3 = 0;
  goto l8;
l5:
  i8 = (int)((_Type)i6)->tbprocs[3];
  i3 = str_0d - 1;
  i0 = *(int*)i7;
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i8)((Parameter__Stream)(int)s, (int)i0, (const unsigned char*)(int)_c8, 16);
  i0 = (int)str + i3;
  *(unsigned char*)i0 = 0;
  goto l8;
l6:
  i6 = (int)((_Type)i6)->tbprocs[3];
  i7 = *(int*)i7;
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i6)((Parameter__Stream)(int)s, (int)i7, (const unsigned char*)(int)_c9, 49);
  goto l8;
l7:
  i0 = (int)((_Type)i6)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i0)((Parameter__Stream)(int)s, (int)-2, (const unsigned char*)(int)_c7, 16);
l8:
  ;
}

unsigned char Parameter__StreamDesc_ReadName_IsSep(unsigned char* Parameter__StreamDesc_ReadName_sep, int Parameter__StreamDesc_ReadName_sep_0d, Parameter__Stream *Parameter__StreamDesc_ReadName_s) {
  register int i0, i1, i2, i3, i4;
  i3 = *(unsigned char*)(int)Parameter__StreamDesc_ReadName_sep;
  i0 = i3 == 0;
  if (i0) goto l1;
  i2 = (int)*Parameter__StreamDesc_ReadName_s;
  i2 += 5;
  i2 = *(unsigned char*)i2;
  i1 = i2 == i3;
  if (i1) goto l1;
  i4 = 0;
l0:
  i4++;
  i3 = (int)Parameter__StreamDesc_ReadName_sep + i4;
  i0 = *(unsigned char*)i3;
  i3 = i0 == 0;
  if (i3) goto l2;
  i0 = i2 != i0;
  if (i0) goto l0;
  goto l2;
l1:
  i4 = 0;
l2:
  i0 = (int)Parameter__StreamDesc_ReadName_sep + i4;
  i0 = *(unsigned char*)i0;
  i0 = i0 != 0;
  return (unsigned char)i0;
}

void Parameter__StreamDesc_ReadName(Parameter__Stream s, const unsigned char* sep__ref, int sep_0d, unsigned char* name, int name_0d) {
  register int i0, i1, i2, i3, i4, i5, i6;
  unsigned char* sep;
  char* _old_top_vs = _top_vs;
  _push_value(int, sep, sep__ref, sep_0d);
  i5 = *(int*)((int)s-4);
  i1 = (int)((_Type)i5)->tbprocs[5];
  i0 = (int)s + 6;
  ((void(*)(Parameter__Stream))i1)((Parameter__Stream)(int)s);
  i0 = *(unsigned char*)i0;
  if (i0) goto l4;
  i6 = Parameter__StreamDesc_ReadName_IsSep(sep, sep_0d, (Parameter__Stream *)&s);
  if (i6) goto l4;
  i0 = (int)((_Type)i5)->tbprocs[4];
  i0 = ((int(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
  i1 = (int)s + 8;
  *(int*)i1 = i0;
  i2 = (int)s + 5;
  i1 = (int)((_Type)i5)->tbprocs[1];
  i3 = 0;
l0:
  i4 = name_0d > i3;
  if (!(i4)) goto l1;
  i4 = *(unsigned char*)i2;
  i0 = (int)name + i3;
  *(unsigned char*)i0 = i4;
l1:
  i3++;
  ((void(*)(Parameter__Stream))i1)((Parameter__Stream)(int)s);
  i4 = Parameter__StreamDesc_ReadName_IsSep(sep, sep_0d, (Parameter__Stream *)&s);
  if (i4) goto l2;
  i0 = *(unsigned char*)i2;
  i4 = i0 <= 32;
  if (i4) goto l2;
  i0 = i0 != 35;
  if (i0) goto l0;
l2:
  i0 = name_0d > i3;
  if (i0) goto l3;
  i1 = (int)((_Type)i5)->tbprocs[3];
  i0 = name_0d - 1;
  i2 = (int)name + i0;
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i1)((Parameter__Stream)(int)s, (int)-2, (const unsigned char*)(int)_c10, 14);
  *(unsigned char*)i2 = 0;
  goto l5;
l3:
  i0 = (int)name + i3;
  *(unsigned char*)i0 = 0;
  goto l5;
l4:
  i5 = (int)((_Type)i5)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i5)((Parameter__Stream)(int)s, (int)-2, (const unsigned char*)(int)_c11, 14);
l5:
  _top_vs = _old_top_vs;
}

unsigned char Parameter__StreamDesc_LookingAtString(Parameter__Stream s, unsigned char* str, int str_0d) {
  register int i0, i1, i2;
  i1 = *(int*)((int)s-4);
  i2 = (int)((_Type)i1)->tbprocs[5];
  i0 = (int)s + 5;
  ((void(*)(Parameter__Stream))i2)((Parameter__Stream)(int)s);
  i0 = *(unsigned char*)i0;
  i2 = i0 == 39;
  if (i2) goto l0;
  i0 = i0 == 34;
  if (i0) goto l0;
  i0 = 0;
  goto l1;
l0:
  i1 = (int)((_Type)i1)->tbprocs[8];
  ((void(*)(Parameter__Stream, unsigned char*, int str_0d))i1)((Parameter__Stream)(int)s, (unsigned char*)(int)str, str_0d);
  i0 = 1;
l1:
  return (unsigned char)i0;
}

void Parameter__StreamDesc_Match(Parameter__Stream s, const unsigned char* sym__ref, int sym_0d) {
  register int i0, i1, i2, i3, i4, i5, i6;
  Parameter__Filename ident;
  unsigned char* sym;
  char* _old_top_vs = _top_vs;
  _push_value(int, sym, sym__ref, sym_0d);
  i0 = *(int*)((int)s-4);
  i5 = *(unsigned char*)(int)sym;
  i3 = (int)((_Type)i0)->tbprocs[5];
  i1 = (int)((_Type)i0)->tbprocs[4];
  i2 = Parameter__IsAlpha((unsigned char)i5);
  ((void(*)(Parameter__Stream))i3)((Parameter__Stream)(int)s);
  i1 = ((int(*)(Parameter__Stream))i1)((Parameter__Stream)(int)s);
  i3 = (int)s + 8;
  *(int*)i3 = i1;
  if (i2) goto l3;
  i6 = i5 == 0;
  if (i6) goto l1;
  i4 = (int)s + 5;
  i2 = *(unsigned char*)i4;
  i6 = i2 != i5;
  if (i6) goto l1;
  i5 = (int)((_Type)i0)->tbprocs[1];
  i1 = 0;
l0:
  i1++;
  i2 = (int)sym + i1;
  i2 = *(unsigned char*)i2;
  i3 = i2 == 0;
  ((void(*)(Parameter__Stream))i5)((Parameter__Stream)(int)s);
  if (i3) goto l2;
  i3 = *(unsigned char*)i4;
  i3 = i3 == i2;
  if (i3) goto l0;
  goto l2;
l1:
  i1 = 0;
l2:
  i6 = (int)sym + i1;
  i6 = *(unsigned char*)i6;
  i6 = i6 != 0;
  goto l6;
l3:
  i6 = (int)s + 6;
  i6 = *(unsigned char*)i6;
  if (i6) goto l4;
  i6 = (int)s + 5;
  i6 = *(unsigned char*)i6;
  i6 = Parameter__IsAlpha((unsigned char)i6);
  if (i6) goto l5;
l4:
  i6 = 1;
  goto l6;
l5:
  i6 = (int)((_Type)i0)->tbprocs[6];
  ((void(*)(Parameter__Stream, unsigned char*, int ident_0d))i6)((Parameter__Stream)(int)s, (unsigned char*)(int)ident, 256);
  i6 = strcmp((const char*) (int)sym, (const char*) (int)ident) != 0;
l6:
  if (!(i6)) goto l7;
  _string_copy((int)ident, (int)sym, 256);
  Strings__Append((const unsigned char*)(int)_c12, 10, (unsigned char*)(int)ident, 256);
  i0 = (int)((_Type)i0)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i0)((Parameter__Stream)(int)s, (int)-2, (const unsigned char*)(int)ident, 256);
l7:
  _top_vs = _old_top_vs;
}

Parameter__Section Parameter__GetSection(const unsigned char* name, int name_0d) {
  register int i0, i1, i2, i3;
  i2 = (int)Parameter__sections;
  i0 = i2 == 0;
  if (i0) goto l1;
  i1 = i2 + 4;
  i1 = (int)*(void**)i1;
  i0 = strcmp((const char*) (int)name, (const char*) i1) == 0;
  if (i0) goto l1;
  i3 = i2;
l0:
  i3 = (int)*(void**)i3;
  i1 = i3 == 0;
  if (i1) goto l2;
  i1 = i3 + 4;
  i1 = (int)*(void**)i1;
  i1 = strcmp((const char*) (int)name, (const char*) i1) != 0;
  if (i1) goto l0;
  goto l2;
l1:
  i3 = i2;
l2:
  return (void*)i3;
}

void Parameter__AddSection(const unsigned char* name__ref, int name_0d, Parameter__Section s) {
  register int i0, i1, i2;
  unsigned char* name;
  char* _old_top_vs = _top_vs;
  _push_value(int, name, name__ref, name_0d);
  *(void**)(int)s = (void*)0;
  i0 = Strings__Length((const unsigned char*)(int)name, name_0d);
  i1 = i0 + 1;
  i0 = (int)s + 4;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i1 < 0) _invalid_length(i1, _P(17216));
    _mem = GC_malloc_atomic(i1*1+8);
    if (!_mem) _new_failed(_P(17181));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i1;
    i1 = (int)_var;
  }
  *(void**)i0 = (void*)i1;
  i0 = (int)*(void**)i0;
  i1 = (int)Parameter__sections;
  i2 = *(int*)(i0-8);
  _string_copy(i0, (int)name, i2);
  i2 = (int)s + 8;
  i0 = i1 == 0;
  *(unsigned char*)i2 = 0;
  i2 = (int)s + 9;
  *(unsigned char*)i2 = 0;
  if (i0) goto l3;
  i2 = (int)*(void**)i1;
  i2 = i2 != 0;
  if (i2) goto l0;
  i0 = i1;
  goto l2;
l0:
  i0 = i1;
l1:
  i0 = (int)*(void**)i0;
  i2 = (int)*(void**)i0;
  i2 = i2 != 0;
  if (i2) goto l1;
l2:
  *(void**)i0 = (void*)(int)s;
  goto l4;
l3:
  Parameter__sections = (void*)(int)s;
l4:
  _top_vs = _old_top_vs;
}

void Parameter__SectionDesc_Parse(Parameter__Section section, unsigned char includeEnd) {
  register int i0, i1;
  if (!(includeEnd)) goto l0;
  i1 = (int)Parameter__in;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[11];
  ((void(*)(Parameter__Stream, const unsigned char*, int sym_0d))i0)((Parameter__Stream)i1, (const unsigned char*)(int)_c13, 4);
l0:
  ;
}

void Parameter__SectionDesc_Write(Parameter__Section section) {
}

short int Parameter__ParseInteger(unsigned char* str, int str_0d, short int *pos) {
  register int i0, i1, i2;
  signed char format;
  int num;
  unsigned char numStr[16];
  i0 = *pos;
  i0++;
  *pos = i0;
  i0 = *pos;
  i1 = (int)str + i0;
  i1 = *(unsigned char*)i1;
  i1 = Parameter__IsNum((unsigned char)i1);
  if (i1) goto l0;
  i1 = i0;
  goto l2;
l0:
  i1 = i0;
l1:
  i1++;
  i2 = (int)str + i1;
  i2 = *(unsigned char*)i2;
  i2 = Parameter__IsNum((unsigned char)i2);
  if (i2) goto l1;
l2:
  i2 = i1 != i0;
  if (i2) goto l3;
  i2 = -1;
  goto l6;
l3:
  i2 = i1 - i0;
  Strings__Extract((const unsigned char*)(int)str, str_0d, (short int)i0, (short int)i2, (unsigned char*)(int)numStr, 16);
  IntStr__StrToInt((const unsigned char*)(int)numStr, 16, (int *)(int)&num, (signed char *)(int)&format);
  i0 = format != 0;
  if (i0) goto l4;
  i0 = num < 32767;
  if (i0) goto l5;
l4:
  i2 = -1;
  goto l6;
l5:
  *pos = i1;
  i2 = num;
l6:
  return (short int)i2;
}

void Parameter__SectionDesc_CmdLineOption(Parameter__Section s, const unsigned char* cmdNames__ref, int cmdNames_0d, const unsigned char* cmdValue__ref, int cmdValue_0d) {
  register int i0, i1, i2, i3;
  short int i;
  unsigned char* cmdNames;
  unsigned char* cmdValue;
  char* _old_top_vs = _top_vs;
  _push_value(int, cmdNames, cmdNames__ref, cmdNames_0d);
  _push_value(int, cmdValue, cmdValue__ref, cmdValue_0d);
  {
    char *_mem, *_var;
    _mem = GC_malloc(20+8);
    if (!_mem) _new_failed(_P(19812));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Parameter__CmdLineOptionDesc_td.td;
    i2 = (int)_var;
  }
  i1 = i2 + 16;
  i0 = i2 + 4;
  *(void**)i0 = (void*)(int)s;
  i0 = *(unsigned char*)(int)cmdValue;
  i0 = i0 == 0;
  *(short int*)i1 = 0;
  if (i0) goto l4;
  i0 = 0;
l0:
  i3 = (int)cmdValue + i0;
  i3 = *(unsigned char*)i3;
  i3 = i3 == 36;
  if (i3) goto l1;
  i3 = i0 + 1;
  i0 = i3;
  goto l3;
l1:
  i = (short int)i0;
  i = (short int)i0;
  i0 = Parameter__ParseInteger((unsigned char*)(int)cmdValue, cmdValue_0d, (short int *)(int)&i);
  i3 = *(short int*)i1;
  i3 = i0 <= i3;
  if (i3) goto l2;
  *(short int*)i1 = i0;
l2:
  i0 = i;
l3:
  i3 = (int)cmdValue + i0;
  i3 = *(unsigned char*)i3;
  i3 = i3 != 0;
  if (i3) goto l0;
l4:
  i0 = Strings__Length((const unsigned char*)(int)cmdNames, cmdNames_0d);
  i1 = i2 + 8;
  i0++;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i0 < 0) _invalid_length(i0, _P(20282));
    _mem = GC_malloc_atomic(i0*1+8);
    if (!_mem) _new_failed(_P(20237));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i0;
    i0 = (int)_var;
  }
  *(void**)i1 = (void*)i0;
  i0 = (int)*(void**)i1;
  i1 = *(int*)(i0-8);
  _string_copy(i0, (int)cmdNames, i1);
  i1 = Strings__Length((const unsigned char*)(int)cmdValue, cmdValue_0d);
  i0 = i2 + 12;
  i1++;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i1 < 0) _invalid_length(i1, _P(20373));
    _mem = GC_malloc_atomic(i1*1+8);
    if (!_mem) _new_failed(_P(20328));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i1;
    i1 = (int)_var;
  }
  *(void**)i0 = (void*)i1;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-8);
  _string_copy(i0, (int)cmdValue, i1);
  i0 = (int)Parameter__cmdList;
  *(void**)i2 = (void*)i0;
  Parameter__cmdList = (void*)i2;
  _top_vs = _old_top_vs;
}

void Parameter__SkipSection(void) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  unsigned char ident[4];
  i8 = (int)ident + 3;
l0:
  i7 = (int)Parameter__in;
  i6 = *(int*)(i7-4);
  i6 = (int)((_Type)i6)->tbprocs[5];
  ((void(*)(Parameter__Stream))i6)((Parameter__Stream)i7);
  i2 = (int)Parameter__in;
  i7 = i2 + 6;
  i7 = *(unsigned char*)i7;
  if (i7) goto l10;
  i3 = i2 + 5;
  i7 = *(unsigned char*)i3;
  i3 = i7 == 34;
  if (i3) goto l7;
  i3 = i7 == 39;
  if (i3) goto l7;
  i4 = Parameter__IsAlpha((unsigned char)i7);
  if (i4) goto l3;
  i5 = i7 <= 32;
  if (i5) goto l2;
  i4 = i7 == 35;
  if (i4) goto l2;
l1:
  i0 = (int)Parameter__in;
  i5 = *(int*)(i0-4);
  i5 = (int)((_Type)i5)->tbprocs[1];
  ((void(*)(Parameter__Stream))i5)((Parameter__Stream)i0);
  i0 = (int)Parameter__in;
  i0 += 5;
  i0 = *(unsigned char*)i0;
  i5 = i0 <= 32;
  if (i5) goto l2;
  i5 = Parameter__IsAlpha((unsigned char)i0);
  if (i5) goto l2;
  i5 = i0 == 35;
  if (i5) goto l2;
  i5 = i0 == 39;
  if (i5) goto l2;
  i0 = i0 != 34;
  if (i0) goto l1;
l2:
  i1 = 0;
  goto l11;
l3:
  i0 = 0;
l4:
  i1 = (int)Parameter__in;
  i5 = i0 >= 4;
  i6 = *(int*)(i1-4);
  i4 = (int)((_Type)i6)->tbprocs[1];
  if (i5) goto l5;
  i5 = i1 + 5;
  i6 = (int)ident + i0;
  i5 = *(unsigned char*)i5;
  *(unsigned char*)i6 = i5;
l5:
  ((void(*)(Parameter__Stream))i4)((Parameter__Stream)i1);
  i5 = (int)Parameter__in;
  i5 += 5;
  i6 = *(unsigned char*)i5;
  i5 = Parameter__IsAlpha((unsigned char)i6);
  i0++;
  if (i5) goto l4;
  i6 = Parameter__IsNum((unsigned char)i6);
  if (i6) goto l4;
  i1 = i0 == 3;
  if (i1) goto l6;
  i1 = 0;
  goto l11;
l6:
  *(unsigned char*)i8 = 0;
  i1 = strcmp((const char*) (int)ident, (const char*) (int)_c13) == 0;
  goto l11;
l7:
  i4 = *(int*)(i2-4);
  i4 = (int)((_Type)i4)->tbprocs[1];
  ((void(*)(Parameter__Stream))i4)((Parameter__Stream)i2);
  i0 = (int)Parameter__in;
  i4 = i0 + 6;
  i4 = *(unsigned char*)i4;
  if (i4) goto l9;
  i0 += 5;
  i4 = *(unsigned char*)i0;
  i0 = i4 == i7;
  if (i0) goto l9;
  i0 = i4 < 32;
  if (i0) goto l9;
l8:
  i3 = (int)Parameter__in;
  i4 = *(int*)(i3-4);
  i4 = (int)((_Type)i4)->tbprocs[1];
  ((void(*)(Parameter__Stream))i4)((Parameter__Stream)i3);
  i4 = (int)Parameter__in;
  i3 = i4 + 6;
  i3 = *(unsigned char*)i3;
  if (i3) goto l9;
  i4 += 5;
  i4 = *(unsigned char*)i4;
  i3 = i4 == i7;
  if (i3) goto l9;
  i4 = i4 >= 32;
  if (i4) goto l8;
l9:
  i4 = (int)Parameter__in;
  i0 = *(int*)(i4-4);
  i0 = (int)((_Type)i0)->tbprocs[1];
  ((void(*)(Parameter__Stream))i0)((Parameter__Stream)i4);
  i1 = 0;
  goto l11;
l10:
  i7 = *(int*)(i2-4);
  i7 = (int)((_Type)i7)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i7)((Parameter__Stream)i2, (int)-1, (const unsigned char*)(int)_c14, 13);
  i1 = 1;
l11:
  if (!(i1)) goto l0;
}

void Parameter__FileStreamDesc_Install(Parameter__FileStream s) {
  register int i0, i1;
  i0 = (int)s + 268;
  i0 = (int)*(void**)i0;
  i1 = (int)BinaryRider__ConnectReader((Channel__Channel)i0);
  i0 = (int)s + 272;
  *(void**)i0 = (void*)i1;
  Parameter__StreamDesc_Install((Parameter__Stream)(int)s);
}

void Parameter__FileStreamDesc_Remove(Parameter__FileStream s) {
  register int i0, i1;
  i0 = (int)s + 268;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[5];
  ((void(*)(Files__File))i1)((Files__File)i0);
  Parameter__StreamDesc_Remove((Parameter__Stream)(int)s);
}

void Parameter__FileStreamDesc_NextChar(Parameter__FileStream s) {
  register int i0, i1, i2, i3, i4, i5;
  i4 = (int)s + 6;
  i0 = *(unsigned char*)i4;
  if (i0) goto l4;
  i0 = (int)s + 272;
  i3 = (int)*(void**)i0;
  i2 = (int)s + 5;
  i5 = *(int*)(i3-4);
  i1 = *(unsigned char*)i2;
  i5 = (int)((_Type)i5)->tbprocs[7];
  ((void(*)(BinaryRider__Reader, unsigned char *))i5)((BinaryRider__Reader)i3, (unsigned char *)i2);
  i3 = (int)*(void**)i0;
  i2 = (int)*(void**)i3;
  i3 = i2 == 0;
  if (i3) goto l0;
  i2 += 8;
  i2 = *(int*)i2;
  i2 = i2 == 5;
  if (i2) goto l1;
l0:
  i3 = 0;
  goto l2;
l1:
  i3 = 1;
l2:
  *(unsigned char*)i4 = i3;
  i3 = *(unsigned char*)i4;
  if (i3) goto l3;
  i0 = (int)*(void**)i0;
  i0 = (int)*(void**)i0;
  i0 = i0 == 0;
  if (i0) goto l3;
  i0 = *(int*)((int)s-4);
  i0 = (int)((_Type)i0)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i0)((Parameter__Stream)(int)s, (int)-1, (const unsigned char*)(int)_c15, 11);
l3:
  Parameter__StreamDesc_NextChar((Parameter__Stream)(int)s);
l4:
  ;
}

void Parameter__FileStreamDesc_Error(Parameter__FileStream s, int pos, const unsigned char* msg__ref, int msg_0d) {
  register int i0, i1;
  unsigned char* msg;
  char* _old_top_vs = _top_vs;
  _push_value(int, msg, msg__ref, msg_0d);
  i0 = pos == -1;
  if (i0) goto l1;
  i0 = pos == -2;
  if (i0) goto l0;
  i0 = pos;
  goto l2;
l0:
  i0 = (int)s + 8;
  i0 = *(int*)i0;
  goto l2;
l1:
  i0 = *(int*)((int)s-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  i0 = ((int(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
l2:
  Parameter__StreamDesc_Error((Parameter__Stream)(int)s, (int)i0, (const unsigned char*)(int)msg, msg_0d);
  i1 = (int)s + 12;
  Out__String((const unsigned char*)(int)_c16, 10);
  Out__String((const unsigned char*)i1, 256);
  Out__String((const unsigned char*)(int)_c17, 9);
  Out__LongInt((int)i0, (int)0);
  Out__Char((unsigned char)58);
  Out__Ln();
  Out__String((const unsigned char*)(int)msg, msg_0d);
  Out__Ln();
  _halt(1);
  _top_vs = _old_top_vs;
}

int Parameter__FileStreamDesc_CurrPos(Parameter__FileStream s) {
  register int i0, i1;
  i0 = (int)s + 272;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[0];
  i0 = ((int(*)(BinaryRider__Reader))i1)((BinaryRider__Reader)i0);
  i0--;
  return (int)i0;
}

void Parameter__GetIndexedArg(short int index, unsigned char* arg, int arg_0d) {
  register int i0, i1, i2, i3;
  i0 = (int)Parameter__argReader;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[3];
  i2 = index <= 0;
  ((void(*)(TextRider__Reader, int))i1)((TextRider__Reader)i0, (int)0);
  if (i2) goto l1;
  i2 = index;
l0:
  i0 = (int)Parameter__argReader;
  i1 = *(int*)(i0-4);
  i2--;
  i1 = (int)((_Type)i1)->tbprocs[8];
  i3 = i2 > 0;
  ((void(*)(TextRider__Reader))i1)((TextRider__Reader)i0);
  if (i3) goto l0;
l1:
  i0 = (int)Parameter__argReader;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[10];
  ((void(*)(TextRider__Reader, unsigned char*, int s_0d))i1)((TextRider__Reader)i0, (unsigned char*)(int)arg, arg_0d);
}

short int Parameter__ParseConfigFile_ConfigFileOption(const unsigned char* configOveride__ref, int configOveride_0d) {
  register int i0, i1, i2, i3;
  Parameter__Filename argName;
  unsigned char* configOveride;
  char* _old_top_vs = _top_vs;
  _push_value(int, configOveride, configOveride__ref, configOveride_0d);
  i0 = strcmp((const char*) (int)configOveride, (const char*) (int)_c18) != 0;
  if (i0) goto l0;
  i2 = 0;
  goto l9;
l0:
  i1 = (int)ProgramArgs__args;
  i1 = ProgramArgs__ChannelDesc_ArgNumber((ProgramArgs__Channel)i1);
  i1 = i1 >= 1;
  if (i1) goto l1;
  i2 = 0;
  goto l9;
l1:
  i0 = 1;
l2:
  Parameter__GetIndexedArg((short int)i0, (unsigned char*)(int)argName, 256);
  i1 = strcmp((const char*) (int)argName, (const char*) (int)_c19) == 0;
  if (i1) goto l7;
  i3 = strcmp((const char*) (int)configOveride, (const char*) (int)argName) == 0;
  if (i3) goto l3;
  i1 = i0 + 1;
  i2 = 0;
  goto l6;
l3:
  i2 = (int)ProgramArgs__args;
  i2 = ProgramArgs__ChannelDesc_ArgNumber((ProgramArgs__Channel)i2);
  i2 = i2 > i0;
  if (i2) goto l4;
  (void)memcpy((void*) (int)argName, (const void*) (int)_c20, 25);
  Strings__Append((const unsigned char*)(int)configOveride, configOveride_0d, (unsigned char*)(int)argName, 256);
  Parameter__FatalError((const unsigned char*)(int)argName, 256);
  goto l5;
l4:
  i3 = i0 + 1;
l5:
  i1 = i0;
l6:
  i0 = i1;
  goto l8;
l7:
  i3 = -1;
  i2 = 1;
l8:
  if (i2) goto l9;
  i1 = (int)ProgramArgs__args;
  i1 = ProgramArgs__ChannelDesc_ArgNumber((ProgramArgs__Channel)i1);
  i1 = i1 >= i0;
  if (i1) goto l2;
l9:
  if (i2) goto l10;
  i3 = -1;
l10:
  _top_vs = _old_top_vs;
  return (short int)i3;
}

void Parameter__ParseConfigFile(const unsigned char* configFile__ref, int configFile_0d, const unsigned char* envVar__ref, int envVar_0d, const unsigned char* configOveride__ref, int configOveride_0d, unsigned char enableInclude, unsigned char skipUnknownSection, unsigned char* fileParsed, int fileParsed_0d) {
  register int i0, i1, i2, i3, i4;
  unsigned char ident[32];
  Msg__Msg res;
  Parameter__Filename str;
  unsigned char* configFile;
  unsigned char* envVar;
  unsigned char* configOveride;
  char* _old_top_vs = _top_vs;
  _push_value(int, configFile, configFile__ref, configFile_0d);
  _push_value(int, envVar, envVar__ref, envVar_0d);
  _push_value(int, configOveride, configOveride__ref, configOveride_0d);
  {
    char *_mem, *_var;
    _mem = GC_malloc(276+8);
    if (!_mem) _new_failed(_P(27417));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Parameter__FileStreamDesc_td.td;
    i2 = (int)_var;
  }
  i3 = i2 + 12;
  i0 = strcmp((const char*) (int)envVar, (const char*) (int)_c18) == 0;
  if (i0) goto l0;
  i0 = Rts_GetEnv((unsigned char*)i3, (const unsigned char*)(int)envVar);
  if (i0) goto l1;
l0:
  _string_copy(i3, (int)configFile, 256);
l1:
  i0 = Parameter__ParseConfigFile_ConfigFileOption((const unsigned char*)(int)configOveride, configOveride_0d);
  i1 = i0 >= 0;
  if (i1) goto l2;
  Parameter__skipArg = -1;
  goto l3;
l2:
  i1 = i0 - 1;
  Parameter__GetIndexedArg((short int)i0, (unsigned char*)i3, 256);
  Parameter__skipArg = i1;
l3:
  if (!(enableInclude)) goto l4;
  i1 = (int)Parameter__include;
  Parameter__AddSection((const unsigned char*)(int)_c21, 8, (Parameter__Section)i1);
  i1 = (int)Parameter__include;
  i0 = i1 + 9;
  *(unsigned char*)i0 = 1;
l4:
  _string_copy((int)fileParsed, i3, fileParsed_0d);
  i0 = strcmp((const char*) i3, (const char*) (int)_c18) == 0;
  i1 = ! skipUnknownSection;
  if (i0) goto l15;
  Filenames__ExpandPath((unsigned char*)i3, 256, (const unsigned char*)i3, 256);
  i0 = i2 + 268;
  i4 = (int)Files__Old((const unsigned char*)i3, 256, (unsigned int)0x1U, (Msg__Msg *)(int)&res);
  *(void**)i0 = (void*)i4;
  i4 = (int)*(void**)i0;
  i4 = i4 == 0;
  if (i4) goto l14;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((void(*)(Parameter__FileStream))i0)((Parameter__FileStream)i2);
  i0 = (int)Parameter__in;
  i3 = *(int*)(i0-4);
  i3 = (int)((_Type)i3)->tbprocs[5];
  ((void(*)(Parameter__Stream))i3)((Parameter__Stream)i0);
  i0 = (int)Parameter__in;
  i0 += 6;
  i0 = *(unsigned char*)i0;
  if (i0) goto l12;
l5:
  i0 = (int)Parameter__in;
  i4 = *(int*)(i0-4);
  i4 = (int)((_Type)i4)->tbprocs[6];
  ((void(*)(Parameter__Stream, unsigned char*, int ident_0d))i4)((Parameter__Stream)i0, (unsigned char*)(int)ident, 32);
  i4 = (int)Parameter__in;
  i0 = i4 + 7;
  i0 = *(unsigned char*)i0;
  if (i0) goto l9;
  i3 = (int)Parameter__GetSection((const unsigned char*)(int)ident, 32);
  i0 = i3 == 0;
  if (i0) goto l6;
  i0 = i3 + 8;
  i4 = *(int*)(i3-4);
  *(unsigned char*)i0 = 1;
  i4 = (int)((_Type)i4)->tbprocs[0];
  ((void(*)(Parameter__Section, unsigned char))i4)((Parameter__Section)i3, (unsigned char)1);
  i3 = 0;
  goto l10;
l6:
  if (skipUnknownSection) goto l7;
  (void)memcpy((void*) (int)str, (const void*) (int)_c22, 17);
  Strings__Append((const unsigned char*)(int)ident, 32, (unsigned char*)(int)str, 256);
  i4 = (int)Parameter__in;
  i3 = *(int*)(i4-4);
  i3 = (int)((_Type)i3)->tbprocs[3];
  ((void(*)(Parameter__Stream, int, const unsigned char*, int msg_0d))i3)((Parameter__Stream)i4, (int)-2, (const unsigned char*)(int)str, 256);
  _halt(1);
  goto l8;
l7:
  Parameter__SkipSection();
l8:
  i3 = i1;
  goto l10;
l9:
  i3 = 0;
l10:
  if (i3) goto l11;
  i0 = (int)Parameter__in;
  i4 = *(int*)(i0-4);
  i4 = (int)((_Type)i4)->tbprocs[5];
  ((void(*)(Parameter__Stream))i4)((Parameter__Stream)i0);
l11:
  if (i3) goto l13;
  i0 = (int)Parameter__in;
  i0 += 6;
  i0 = *(unsigned char*)i0;
  if (!(i0)) goto l5;
  goto l13;
l12:
  i3 = 0;
l13:
  if (i3) goto l15;
  i0 = (int)Parameter__in;
  i2 = i2 != i0;
  if (i2) goto l15;
  i2 = *(int*)(i0-4);
  i2 = (int)((_Type)i2)->tbprocs[0];
  ((void(*)(Parameter__Stream))i2)((Parameter__Stream)i0);
  goto l15;
l14:
  (void)memcpy((void*) (int)str, (const void*) (int)_c23, 24);
  Strings__Append((const unsigned char*)i3, 256, (unsigned char*)(int)str, 256);
  Parameter__Warning((const unsigned char*)(int)str, 256);
l15:
  _top_vs = _old_top_vs;
}

void Parameter__IncludeSectionDesc_Parse(Parameter__IncludeSection incl, unsigned char includeEnd) {
  register int i0, i1, i2, i3;
  unsigned char dummy[2];
  Msg__Msg res;
  {
    char *_mem, *_var;
    _mem = GC_malloc(276+8);
    if (!_mem) _new_failed(_P(30346));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Parameter__FileStreamDesc_td.td;
    i2 = (int)_var;
  }
  i1 = i2 + 12;
  i0 = (int)Parameter__in;
  i3 = *(int*)(i0-4);
  i3 = (int)((_Type)i3)->tbprocs[10];
  i0 = ((unsigned char(*)(Parameter__Stream, unsigned char*, int str_0d))i3)((Parameter__Stream)i0, (unsigned char*)i1, 256);
  if (i0) goto l0;
  i3 = (int)Parameter__in;
  i0 = *(int*)(i3-4);
  i0 = (int)((_Type)i0)->tbprocs[9];
  ((void(*)(Parameter__Stream, const unsigned char*, int sep_0d, unsigned char*, int name_0d))i0)((Parameter__Stream)i3, (const unsigned char*)(int)_c18, 1, (unsigned char*)i1, 256);
l0:
  Parameter__SectionDesc_Parse((Parameter__Section)(int)incl, (unsigned char)includeEnd);
  if (includeEnd) goto l1;
  Parameter__ParseConfigFile((const unsigned char*)i1, 256, (const unsigned char*)(int)_c18, 1, (const unsigned char*)(int)_c18, 1, (unsigned char)0, (unsigned char)0, (unsigned char*)(int)dummy, 2);
  goto l2;
l1:
  Filenames__ExpandPath((unsigned char*)i1, 256, (const unsigned char*)i1, 256);
  i0 = i2 + 268;
  i1 = (int)Files__Old((const unsigned char*)i1, 256, (unsigned int)0x1U, (Msg__Msg *)(int)&res);
  *(void**)i0 = (void*)i1;
  i0 = (int)*(void**)i0;
  i0 = i0 == 0;
  if (i0) goto l2;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[2];
  ((void(*)(Parameter__FileStream))i0)((Parameter__FileStream)i2);
l2:
  ;
}

void Parameter__WriteConfig(void) {
  register int i0, i1, i2;
  i1 = (int)Parameter__sections;
  i0 = i1 == 0;
  if (i0) goto l2;
l0:
  i2 = i1 + 9;
  i2 = *(unsigned char*)i2;
  if (i2) goto l1;
  i0 = i1 + 4;
  i0 = (int)*(void**)i0;
  i2 = *(int*)(i0-8);
  Out__String((const unsigned char*)i0, i2);
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[1];
  Out__Ln();
  ((void(*)(Parameter__Section))i0)((Parameter__Section)i1);
  Out__String((const unsigned char*)(int)_c13, 4);
  Out__Ln();
l1:
  i1 = (int)*(void**)i1;
  i2 = i1 != 0;
  if (i2) goto l0;
l2:
  ;
}

void Parameter__StringStreamDesc_Install(Parameter__StringStream s) {
  register int i0;
  i0 = (int)s + 136;
  *(int*)i0 = 0;
  Parameter__StreamDesc_Install((Parameter__Stream)(int)s);
}

void Parameter__StringStreamDesc_NextChar(Parameter__StringStream s) {
  register int i0, i1, i2, i3;
  i2 = (int)s + 6;
  i0 = *(unsigned char*)i2;
  if (i0) goto l2;
  i0 = (int)s + 136;
  i1 = *(int*)i0;
  i3 = (int)s + 12;
  i3 = (int)*(void**)i3;
  i3 = i1 + i3;
  i1 = *(unsigned char*)i3;
  i3 = i1 == 0;
  if (i3) goto l0;
  i2 = (int)s + 5;
  *(unsigned char*)i2 = i1;
  i2 = *(int*)i0;
  i2++;
  *(int*)i0 = i2;
  goto l1;
l0:
  *(unsigned char*)i2 = 1;
l1:
  Parameter__StreamDesc_NextChar((Parameter__Stream)(int)s);
l2:
  ;
}

void Parameter__StringStreamDesc_Error(Parameter__StringStream s, int pos, const unsigned char* msg__ref, int msg_0d) {
  register int i0, i1, i2;
  unsigned char* msg;
  char* _old_top_vs = _top_vs;
  _push_value(int, msg, msg__ref, msg_0d);
  i0 = pos == -1;
  if (i0) goto l1;
  i0 = pos == -2;
  if (i0) goto l0;
  i0 = pos;
  goto l2;
l0:
  i0 = (int)s + 8;
  i0 = *(int*)i0;
  goto l2;
l1:
  i0 = *(int*)((int)s-4);
  i0 = (int)((_Type)i0)->tbprocs[4];
  i0 = ((int(*)(Parameter__Stream))i0)((Parameter__Stream)(int)s);
l2:
  i2 = (int)s + 16;
  Parameter__StreamDesc_Error((Parameter__Stream)(int)s, (int)i0, (const unsigned char*)(int)msg, msg_0d);
  i1 = strcmp((const char*) i2, (const char*) (int)_c18) == 0;
  if (i1) goto l3;
  Out__String((const unsigned char*)i2, 120);
  Out__Ln();
l3:
  i1 = (int)s + 12;
  i2 = (int)*(void**)i1;
  i1 = *(int*)(i2-8);
  Out__String((const unsigned char*)i2, i1);
  i2 = i0 - 1;
  i0 = i2 < 0;
  Out__Ln();
  if (i0) goto l5;
  i0 = 0;
l4:
  i0++;
  i1 = i0 <= i2;
  Out__Char((unsigned char)45);
  if (i1) goto l4;
l5:
  Out__String((const unsigned char*)(int)_c24, 4);
  Out__String((const unsigned char*)(int)msg, msg_0d);
  Out__Ln();
  _halt(1);
  _top_vs = _old_top_vs;
}

int Parameter__StringStreamDesc_CurrPos(Parameter__StringStream s) {
  register int i0;
  i0 = (int)s + 136;
  i0 = *(int*)i0;
  i0--;
  return (int)i0;
}

Parameter__CmdLineOption Parameter__ParseCmdLine_FindCmd(const unsigned char* cmdName__ref, int cmdName_0d) {
  register int i0, i1, i2, i3, i4, i5, i6, i7;
  unsigned char found;
  short int pos;
  unsigned char* cmdName;
  char* _old_top_vs = _top_vs;
  _push_value(int, cmdName, cmdName__ref, cmdName_0d);
  i0 = *(unsigned char*)(int)cmdName;
  i0 = i0 != 0;
  if (i0) goto l0;
  i2 = 0;
  goto l3;
l0:
  i1 = 0;
l1:
  i0 = (int)cmdName + i1;
  i0 = *(unsigned char*)i0;
  i2 = i0 == 44;
  if (i2) goto l2;
  i0 = i1 + 1;
  i1 = i0;
l2:
  if (i2) goto l3;
  i0 = (int)cmdName + i1;
  i0 = *(unsigned char*)i0;
  i0 = i0 != 0;
  if (i0) goto l1;
l3:
  if (i2) goto l17;
  i1 = Strings__Length((const unsigned char*)(int)cmdName, cmdName_0d);
  i2 = (int)Parameter__cmdList;
  i6 = i2 != 0;
  if (i6) goto l4;
  i0 = 0;
  goto l16;
l4:
l5:
  i6 = i2 + 8;
  i5 = (int)*(void**)i6;
  i0 = *(int*)(i5-8);
  found = (unsigned char)i4;
  pos = (short int)i3;
  found = (unsigned char)i4;
  pos = (short int)i3;
  Strings__FindNext((const unsigned char*)(int)cmdName, cmdName_0d, (const unsigned char*)i5, i0, (short int)0, (unsigned char *)(int)&found, (short int *)(int)&pos);
  if (found) goto l6;
  i3 = pos;
  i0 = 0;
  i4 = 0;
  goto l14;
l6:
  i3 = pos;
l7:
  i4 = i3 == 0;
  if (i4) goto l8;
  i4 = i3 - 1;
  i5 = (int)*(void**)i6;
  i5 = i4 + i5;
  i4 = *(unsigned char*)i5;
  i4 = i4 != 44;
  if (i4) goto l9;
l8:
  i4 = i1 + i3;
  i5 = (int)*(void**)i6;
  i5 = i4 + i5;
  i5 = *(unsigned char*)i5;
  i4 = i5 == 0;
  if (i4) goto l10;
  i5 = i5 == 44;
  if (i5) goto l10;
l9:
  i4 = i3 + 1;
  i3 = i4;
  i0 = 0;
  goto l11;
l10:
  i7 = i2;
  i0 = 1;
l11:
  if (i0) goto l12;
  i5 = (int)*(void**)i6;
  i4 = *(int*)(i5-8);
  found = (unsigned char)1;
  pos = (short int)i3;
  found = (unsigned char)1;
  pos = (short int)i3;
  Strings__FindNext((const unsigned char*)(int)cmdName, cmdName_0d, (const unsigned char*)i5, i4, (short int)i3, (unsigned char *)(int)&found, (short int *)(int)&pos);
  i3 = pos;
  i4 = found;
  goto l13;
l12:
  i4 = 1;
l13:
  if (i0) goto l14;
  if (i4) goto l7;
l14:
  if (i0) goto l15;
  i6 = (int)*(void**)i2;
  i2 = i6;
l15:
  if (i0) goto l16;
  i6 = i2 != 0;
  if (i6) goto l5;
l16:
  if (i0) goto l18;
  i7 = 0;
  goto l18;
l17:
  i7 = 0;
l18:
  _top_vs = _old_top_vs;
  return (void*)i7;
}

void Parameter__ParseCmdLine_EvalOption(unsigned char* optName, int optName_0d, Parameter__CmdLineOption cmd, short int *optIndex, Parameter__StringStream *Parameter__ParseCmdLine_strStream) {
  register int i0, i1, i2, i3, i4;
  short int i;
  unsigned char numStr[32];
  Parameter__LargeString param;
  Parameter__LargeString str;
  i3 = (int)cmd + 16;
  i2 = *(short int*)i3;
  i0 = *optIndex;
  i0 = i2 + i0;
  i1 = Parameter__numArgs;
  i0 = i1 < i0;
  if (i0) goto l8;
  i4 = (int)cmd + 12;
  i4 = (int)*(void**)i4;
  _string_copy((int)str, i4, 2048);
  i2 = i2 == 0;
  if (i2) goto l6;
  i1 = *(unsigned char*)(int)str;
  i1 = i1 == 0;
  if (i1) goto l5;
  i2 = 0;
l0:
  i1 = (int)str + i2;
  i1 = *(unsigned char*)i1;
  i1 = i1 == 36;
  if (i1) goto l1;
  i1 = i2 + 1;
  i2 = i1;
  goto l4;
l1:
  i = (short int)i2;
  i = (short int)i2;
  i1 = Parameter__ParseInteger((unsigned char*)(int)str, 2048, (short int *)(int)&i);
  i4 = i1 > 0;
  if (i4) goto l2;
  i4 = i;
  goto l3;
l2:
  i4 = i - i2;
  Strings__Delete((unsigned char*)(int)str, 2048, (short int)i2, (short int)i4);
  i4 = *optIndex;
  i1 += i4;
  Parameter__GetIndexedArg((short int)i1, (unsigned char*)(int)param, 2048);
  Strings__Insert((const unsigned char*)(int)param, 2048, (short int)i2, (unsigned char*)(int)str, 2048);
  i1 = Strings__Length((const unsigned char*)(int)param, 2048);
  i2 -= i;
  i1 -= i2;
  i4 = i + i1;
l3:
  i2 = i4;
l4:
  i1 = (int)str + i2;
  i1 = *(unsigned char*)i1;
  i1 = i1 != 0;
  if (i1) goto l0;
l5:
  i1 = *(short int*)i3;
  i4 = *optIndex;
  i1 += i4;
  *optIndex = i1;
l6:
  i2 = (int)*Parameter__ParseCmdLine_strStream;
  i0 = Strings__Length((const unsigned char*)(int)str, 2048);
  i1 = i2 + 12;
  i4 = (int)*(void**)i1;
  i4 = *(int*)(i4-8);
  i4 = i4 >= i0;
  if (i4) goto l7;
  i0 += 256;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i0 < 0) _invalid_length(i0, _P(38315));
    _mem = GC_malloc_atomic(i0*1+8);
    if (!_mem) _new_failed(_P(38295));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i0;
    i0 = (int)_var;
  }
  *(void**)i1 = (void*)i0;
l7:
  i0 = (int)*(void**)i1;
  i4 = *(int*)(i2-4);
  i1 = *(int*)(i0-8);
  _string_copy(i0, (int)str, i1);
  i1 = (int)((_Type)i4)->tbprocs[2];
  ((void(*)(Parameter__StringStream))i1)((Parameter__StringStream)i2);
  i1 = (int)cmd + 4;
  i1 = (int)*(void**)i1;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[0];
  i4 = (int)((_Type)i4)->tbprocs[0];
  ((void(*)(Parameter__Section, unsigned char))i0)((Parameter__Section)i1, (unsigned char)0);
  ((void(*)(Parameter__Stream))i4)((Parameter__Stream)i2);
  goto l11;
l8:
  (void)memcpy((void*) (int)str, (const void*) (int)_c25, 8);
  Strings__Append((const unsigned char*)(int)optName, optName_0d, (unsigned char*)(int)str, 2048);
  Strings__Append((const unsigned char*)(int)_c26, 10, (unsigned char*)(int)str, 2048);
  i0 = *(short int*)i3;
  i3 = i0 == 1;
  if (i3) goto l9;
  IntStr__IntToStr((int)i0, (unsigned char*)(int)numStr, 32);
  Strings__Append((const unsigned char*)(int)numStr, 32, (unsigned char*)(int)str, 2048);
  Strings__Append((const unsigned char*)(int)_c27, 12, (unsigned char*)(int)str, 2048);
  goto l10;
l9:
  Strings__Append((const unsigned char*)(int)_c28, 12, (unsigned char*)(int)str, 2048);
l10:
  Parameter__FatalError((const unsigned char*)(int)str, 2048);
l11:
  ;
}

short int Parameter__ParseCmdLine(unsigned char optionsStartWithDash, unsigned char multSingleChar, unsigned char enableDashDash) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10;
  Parameter__LargeString currArg;
  short int i;
  Parameter__LargeString msg;
  Parameter__StringStream strStream;
  {
    char *_mem, *_var;
    _mem = GC_malloc(140+8);
    if (!_mem) _new_failed(_P(38563));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Parameter__StringStreamDesc_td.td;
    i9 = (int)_var;
  }
  i0 = i9 + 16;
  i1 = i9 + 12;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    _mem = GC_malloc_atomic(256*1+8);
    if (!_mem) _new_failed(_P(38584));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = 256;
    i2 = (int)_var;
  }
  *(void**)i1 = (void*)i2;
  (void)memcpy((void*) i0, (const void*) (int)_c29, 44);
  i0 = (int)ProgramArgs__args;
  i0 = ProgramArgs__ChannelDesc_ArgNumber((ProgramArgs__Channel)i0);
  i1 = Parameter__skipArg;
  i1 = i1 == 1;
  if (i1) goto l0;
  i10 = 1;
  goto l1;
l0:
  i10 = 3;
l1:
  Parameter__numArgs = i0;
  Parameter__restArg = -2;
  i0 = Parameter__numArgs;
  i0 = i10 > i0;
  if (i0) goto l21;
  i8 = Parameter__restArg;
  i1 = i8 >= 0;
  if (i1) goto l21;
  i0 = (int)msg + 1;
  i8 = (int)currArg + 1;
l2:
  Parameter__GetIndexedArg((short int)i10, (unsigned char*)(int)currArg, 2048);
  i6 = (int)Parameter__ParseCmdLine_FindCmd((const unsigned char*)(int)currArg, 2048);
  i7 = i6 != 0;
  if (i7) goto l17;
  if (!(enableDashDash)) goto l3;
  i4 = strcmp((const char*) (int)currArg, (const char*) (int)_c19) == 0;
  if (i4) goto l15;
l3:
  if (!(multSingleChar)) goto l4;
  i4 = *(unsigned char*)(int)currArg;
  i4 = i4 != 45;
  if (i4) goto l4;
  i7 = *(unsigned char*)i8;
  i6 = i7 != 45;
  if (i6) goto l8;
l4:
  if (!(optionsStartWithDash)) goto l5;
  i7 = *(unsigned char*)(int)currArg;
  i7 = i7 == 45;
  if (i7) goto l6;
l5:
  Parameter__restArg = i10;
  goto l7;
l6:
  (void)memcpy((void*) (int)msg, (const void*) (int)_c30, 16);
  Strings__Append((const unsigned char*)(int)currArg, 2048, (unsigned char*)(int)msg, 2048);
  Parameter__FatalError((const unsigned char*)(int)msg, 2048);
l7:
  i3 = i9;
  i2 = i10;
  goto l16;
l8:
  (void)memcpy((void*) (int)msg, (const void*) (int)_c31, 3);
  i7 = i7 != 0;
  if (i7) goto l9;
  i2 = i10;
  i3 = i9;
  goto l16;
l9:
  i4 = 1;
  i3 = i9;
  i2 = i10;
l10:
  i7 = (int)currArg + i4;
  i7 = *(unsigned char*)i7;
  *(unsigned char*)i0 = i7;
  i7 = (int)Parameter__ParseCmdLine_FindCmd((const unsigned char*)(int)msg, 2048);
  i5 = i7 == 0;
  if (i5) goto l13;
  i6 = i7 + 16;
  i6 = *(short int*)i6;
  i6 = i6 != 0;
  if (i6) goto l11;
  strStream = (void*)i3;
  i = (short int)i2;
  strStream = (void*)i3;
  i = (short int)i2;
  Parameter__ParseCmdLine_EvalOption((unsigned char*)(int)msg, 2048, (Parameter__CmdLineOption)i7, (short int *)(int)&i, (Parameter__StringStream *)&strStream);
  i5 = (int)strStream;
  i6 = i;
  goto l12;
l11:
  Strings__Insert((const unsigned char*)(int)_c25, 8, (short int)0, (unsigned char*)(int)msg, 2048);
  Strings__Append((const unsigned char*)(int)_c32, 49, (unsigned char*)(int)msg, 2048);
  Parameter__FatalError((const unsigned char*)(int)msg, 2048);
  i5 = i3;
  i6 = i2;
l12:
  i2 = i6;
  i3 = i5;
  goto l14;
l13:
  Strings__Insert((const unsigned char*)(int)_c30, 16, (short int)0, (unsigned char*)(int)msg, 2048);
  Parameter__FatalError((const unsigned char*)(int)msg, 2048);
l14:
  i4++;
  i7 = (int)currArg + i4;
  i7 = *(unsigned char*)i7;
  i7 = i7 != 0;
  if (i7) goto l10;
  goto l16;
l15:
  i4 = i10 + 1;
  Parameter__restArg = i4;
  i2 = i10;
  i3 = i9;
l16:
  i9 = i3;
  goto l18;
l17:
  strStream = (void*)i9;
  i = (short int)i10;
  strStream = (void*)i9;
  i = (short int)i10;
  Parameter__ParseCmdLine_EvalOption((unsigned char*)(int)currArg, 2048, (Parameter__CmdLineOption)i6, (short int *)(int)&i, (Parameter__StringStream *)&strStream);
  i9 = (int)strStream;
  i2 = i;
l18:
  i7 = i2 + 1;
  i6 = Parameter__skipArg;
  i6 = i6 == i7;
  if (i6) goto l19;
  i10 = i7;
  goto l20;
l19:
  i10 = i7 + 2;
l20:
  i7 = Parameter__numArgs;
  i7 = i10 > i7;
  if (i7) goto l21;
  i7 = Parameter__restArg;
  i7 = i7 < 0;
  if (i7) goto l2;
l21:
  i2 = Parameter__restArg;
  i1 = Parameter__skipArg;
  i0 = i2 == i1;
  if (i0) goto l22;
  i1 = i1 <= i2;
  if (i1) goto l23;
  i1 = i2 < 0;
  if (i1) goto l23;
  Parameter__FatalError((const unsigned char*)(int)_c33, 55);
  goto l23;
l22:
  i2 += 2;
  Parameter__restArg = i2;
l23:
  i0 = Parameter__restArg;
  i2 = i0 < 0;
  i1 = Parameter__numArgs;
  if (i2) goto l24;
  i2 = i1 - i0;
  i2++;
  goto l25;
l24:
  i2 = 0;
l25:
  return (short int)i2;
}

void Parameter__GetArg(short int index, unsigned char* arg, int arg_0d) {
  register int i0;
  i0 = Parameter__restArg;
  i0 = index + i0;
  Parameter__GetIndexedArg((short int)i0, (unsigned char*)(int)arg, arg_0d);
}

void Parameter_init(void) {
  register int i0, i1, i2;
  _mid = _register_module(&Parameter_md.md, &Parameter__StringStreamDesc_td.td);
  {
    char *_mem, *_var;
    _mem = GC_malloc(12+8);
    if (!_mem) _new_failed(_P(41140));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Parameter__IncludeSectionDesc_td.td;
    i0 = (int)_var;
  }
  i2 = i0 + 8;
  i1 = i0 + 9;
  *(unsigned char*)i2 = 0;
  *(unsigned char*)i1 = 1;
  i1 = (int)ProgramArgs__args;
  i1 = (int)TextRider__ConnectReader((Channel__Channel)i1);
  Parameter__sections = (void*)0;
  Parameter__cmdList = (void*)0;
  Parameter__in = (void*)0;
  Parameter__include = (void*)i0;
  Parameter__argReader = (void*)i1;
}
