/* file generated by oo2c -- do not edit */
#ifndef _MODULE_Rts_
#define _MODULE_Rts_

#define Rts__pathSeperator 47
extern short int Rts_System(const unsigned char* command);
extern void Rts_GetUserHome(unsigned char* home, const unsigned char* user);
extern unsigned char Rts_GetEnv(unsigned char* var, const unsigned char* name);
extern void Rts_init(void);

#endif
