/* file generated by oo2c -- do not edit */
#ifndef _MODULE_StdChannels_
#define _MODULE_StdChannels_

#include "Channel.h"
extern Channel__Channel StdChannels__stdin;
extern Channel__Channel StdChannels__stdout;
extern Channel__Channel StdChannels__stderr;
#include "Msg.h"
typedef struct StdChannels__WriterDesc {
  Channel__Channel base;
  Msg__Msg res;
  int bytesWritten;
  unsigned char positionable;
  char _13pad, _14pad, _15pad;
} StdChannels__WriterDesc;
typedef struct StdChannels__WriterDesc* StdChannels__Writer;
typedef struct StdChannels__NullChannelDesc {
  Msg__Msg res;
  unsigned char readable;
  unsigned char writable;
  unsigned char open;
  char _7pad;
  StdChannels__Writer writer;
} StdChannels__NullChannelDesc;
extern struct StdChannels__NullChannelDesc* StdChannels__null;
typedef int(* _TBP_StdChannels__WriterDesc_Pos)(StdChannels__Writer w);
#define _TBN_StdChannels__WriterDesc_Pos 0
extern int StdChannels__WriterDesc_Pos(StdChannels__Writer w);
typedef void(* _TBP_StdChannels__WriterDesc_SetPos)(StdChannels__Writer w, int newPos);
#define _TBN_StdChannels__WriterDesc_SetPos 1
extern void StdChannels__WriterDesc_SetPos(StdChannels__Writer w, int newPos);
typedef void(* _TBP_StdChannels__WriterDesc_WriteByte)(StdChannels__Writer w, unsigned char x);
#define _TBN_StdChannels__WriterDesc_WriteByte 2
extern void StdChannels__WriterDesc_WriteByte(StdChannels__Writer w, unsigned char x);
typedef void(* _TBP_StdChannels__WriterDesc_WriteBytes)(StdChannels__Writer w, unsigned char* x, int x_0d, int start, int n);
#define _TBN_StdChannels__WriterDesc_WriteBytes 3
extern void StdChannels__WriterDesc_WriteBytes(StdChannels__Writer w, unsigned char* x, int x_0d, int start, int n);
typedef struct StdChannels__NullChannelDesc* StdChannels__NullChannel;
typedef int(* _TBP_StdChannels__NullChannelDesc_Length)(StdChannels__NullChannel ch);
#define _TBN_StdChannels__NullChannelDesc_Length 0
extern int StdChannels__NullChannelDesc_Length(StdChannels__NullChannel ch);
#include "Time.h"
typedef void(* _TBP_StdChannels__NullChannelDesc_GetModTime)(StdChannels__NullChannel ch, Time__TimeStamp *mtime, _Type mtime__tag);
#define _TBN_StdChannels__NullChannelDesc_GetModTime 1
extern void StdChannels__NullChannelDesc_GetModTime(StdChannels__NullChannel ch, Time__TimeStamp *mtime, _Type mtime__tag);
typedef Channel__Reader(* _TBP_StdChannels__NullChannelDesc_NewReader)(StdChannels__NullChannel ch);
#define _TBN_StdChannels__NullChannelDesc_NewReader 2
extern Channel__Reader StdChannels__NullChannelDesc_NewReader(StdChannels__NullChannel ch);
typedef Channel__Writer(* _TBP_StdChannels__NullChannelDesc_NewWriter)(StdChannels__NullChannel ch);
#define _TBN_StdChannels__NullChannelDesc_NewWriter 3
extern Channel__Writer StdChannels__NullChannelDesc_NewWriter(StdChannels__NullChannel ch);
typedef void(* _TBP_StdChannels__NullChannelDesc_Flush)(StdChannels__NullChannel ch);
#define _TBN_StdChannels__NullChannelDesc_Flush 4
extern void StdChannels__NullChannelDesc_Flush(StdChannels__NullChannel ch);
typedef void(* _TBP_StdChannels__NullChannelDesc_Close)(StdChannels__NullChannel ch);
#define _TBN_StdChannels__NullChannelDesc_Close 5
extern void StdChannels__NullChannelDesc_Close(StdChannels__NullChannel ch);
extern struct _TD StdChannels__NullChannelDesc_td;
extern struct _TD StdChannels__WriterDesc_td;
extern struct _TD StdChannels__ErrorContextDesc_td;
extern void StdChannels_init(void);

#endif
