/* file generated by oo2c -- do not edit */
#include "StdTypes.h"
#include "Error.h"
#include "Opcode.h"
#include "ParamPragmas.h"

/* local definitions */

/* function prototypes */

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const void* list[13];
} _p0 = {13, NULL, {
  (const void*)&StdTypes__BasicTypes,
  (const void*)&StdTypes__CharType,
  (const void*)&StdTypes__IntType,
  (const void*)&StdTypes__Max,
  (const void*)&StdTypes__Min,
  (const void*)&StdTypes__NotifyPragmaAssign,
  (const void*)&StdTypes__PassPerReference,
  (const void*)&StdTypes__StructAlloc,
  (const void*)&StdTypes__ValidChar,
  (const void*)&StdTypes__ValidInt,
  (const void*)&StdTypes__ValidReal,
  (const void*)&StdTypes__WholeMax,
  (const void*)&StdTypes__WholeMin,
}};
static const struct {
  int length;
  void* pad;
  const void* list[0];
} _p1 = {0, NULL, {
}};
static const struct {
  int length;
  void* pad;
  const char name[9];
} _n0 = {9, NULL, {"StdTypes"}};
static struct _MD StdTypes_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL,
    _p0.list,
    _p1.list,
    1620942442
  }
};

/* local strings */
static const unsigned char _c14[] = "void";
static const unsigned char _c13[] = "void*";
static const unsigned char _c12[] = "unsigned hugeint";
static const unsigned char _c11[] = "unsigned int";
static const unsigned char _c10[] = "double";
static const unsigned char _c9[] = "float";
static const unsigned char _c8[] = "hugeint";
static const unsigned char _c7[] = "int";
static const unsigned char _c6[] = "short int";
static const unsigned char _c5[] = "signed char";
static const unsigned char _c4[] = "unsigned short int";
static const unsigned char _c3[] = "unsigned char";
static const unsigned char _c2[] = "_undef_";
static const unsigned char _c1[] = "RealOverflowCheck";
static const unsigned char _c0[] = "OverflowCheck";

