/* file generated by oo2c -- do not edit */
#include "Strings2.h"
#include "Strings.h"

/* local definitions */

/* function prototypes */
unsigned char Strings2__Match_RecMatch(unsigned char* src, int src_0d, short int posSrc, unsigned char* pat, int pat_0d, short int posPat, short int *Strings2__Match_lenSource, short int *Strings2__Match_lenPattern);

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const void* list[4];
} _p0 = {4, NULL, {
  (const void*)&Strings2__AppendChar,
  (const void*)&Strings2__InsertChar,
  (const void*)&Strings2__Match,
  (const void*)&Strings2__PosChar,
}};
static const struct {
  int length;
  void* pad;
  const void* list[0];
} _p1 = {0, NULL, {
}};
static const struct {
  int length;
  void* pad;
  const char name[9];
} _n0 = {9, NULL, {"Strings2"}};
static struct _MD Strings2_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL,
    _p0.list,
    _p1.list,
    -397565723
  }
};

/* local strings */

