/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "SymbolFile.d"

static _ModId _mid;

Data__Object SymbolFile__FindImportedModule(const unsigned char* modName, int modName_0d) {
  register int i0, i1, i2, i3;
  i0 = strcmp((const char*) (int)modName, (const char*) (int)_c0) == 0;
  if (i0) goto l2;
  i0 = (int)SymbolTable__importedMods;
  i2 = i0 == 0;
  if (i2) goto l1;
  i1 = i0 + 20;
  i1 = (int)*(void**)i1;
  i2 = strcmp((const char*) (int)modName, (const char*) i1) == 0;
  if (i2) goto l1;
  i3 = i0;
l0:
  i3 += 36;
  i3 = (int)*(void**)i3;
  i1 = i3 == 0;
  if (i1) goto l3;
  i1 = i3 + 20;
  i1 = (int)*(void**)i1;
  i1 = strcmp((const char*) (int)modName, (const char*) i1) != 0;
  if (i1) goto l0;
  goto l3;
l1:
  i3 = i0;
  goto l3;
l2:
  i3 = (int)SymbolTable__system;
l3:
  return (void*)i3;
}

unsigned char SymbolFile__RemoveImportedModule_Remove(Data__Object *list, unsigned char* SymbolFile__RemoveImportedModule_modName) {
  register int i0, i1, i2;
  i1 = (int)*list;
  i0 = i1 == 0;
  if (i0) goto l1;
  i0 = i1 + 52;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i0 = (int)*(void**)i0;
  i0 = strcmp((const char*) i0, (const char*) (int)SymbolFile__RemoveImportedModule_modName) == 0;
  if (i0) goto l0;
  i0 = i1 + 36;
  i2 = (int)*(void**)i0;
  i2 = SymbolFile__RemoveImportedModule_Remove((Data__Object *)i0, SymbolFile__RemoveImportedModule_modName);
  goto l2;
l0:
  i1 += 36;
  i1 = (int)*(void**)i1;
  *list = (void*)i1;
  i2 = 1;
  goto l2;
l1:
  i2 = 0;
l2:
  return (unsigned char)i2;
}

void SymbolFile__RemoveImportedModule(const unsigned char* modName__ref, int modName_0d) {
  register int i0, i1, i2, i3;
  unsigned char* modName;
  char* _old_top_vs = _top_vs;
  _push_value(int, modName, modName__ref, modName_0d);
  i0 = (int)SymbolTable__importedMods;
  i0 = SymbolFile__RemoveImportedModule_Remove((Data__Object *)(int)(int)&SymbolTable__importedMods, modName);
  if (!(i0)) goto l2;
  i3 = (int)SymbolTable__importedMods;
  i2 = i3 == 0;
  if (i2) goto l2;
l0:
  i0 = i3 + 32;
  i2 = i3 + 36;
  i2 = (int)*(void**)i2;
  i1 = (int)*(void**)i0;
  i1 = SymbolFile__RemoveImportedModule_Remove((Data__Object *)i0, modName);
  if (!(i1)) goto l1;
  i3 += 52;
  i3 = (int)*(void**)i3;
  i3 += 20;
  i0 = (int)*(void**)i3;
  i3 = *(int*)(i0-8);
  SymbolFile__RemoveImportedModule((const unsigned char*)i0, i3);
l1:
  i0 = i2 != 0;
  if (!(i0)) goto l2;
  i3 = i2;
  goto l0;
l2:
  _top_vs = _old_top_vs;
}

short int SymbolFile__CreateModuleId(void) {
  register int i0, i1;
  i0 = (int)SymbolTable__importedMods;
  i1 = i0 == 0;
  if (i1) goto l0;
  i1 = i0 + 48;
  i1 = *(short int*)i1;
  i1++;
  goto l1;
l0:
  i1 = 1;
l1:
  return (short int)i1;
}

unsigned char SymbolFile__IntegrateSymbols_IntegrateTree_IntegrateList_ObjIsPtrBase(Data__Object obj) {
  register int i0, i1;
  i0 = (int)obj + 28;
  i0 = *(signed char*)i0;
  i0 = i0 != 2;
  if (i0) goto l0;
  i0 = (int)obj + 24;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i0 = *(signed char*)i0;
  i1 = i0 == 29;
  if (i1) goto l1;
  i1 = i0 == 30;
  if (i1) goto l1;
  i1 = i0 == 31;
  if (i1) goto l1;
  i0 = i0 == 27;
  if (i0) goto l1;
l0:
  i0 = 0;
  goto l2;
l1:
  i0 = 1;
l2:
  return (unsigned char)i0;
}

void SymbolFile__IntegrateSymbols_IntegrateTree_IntegrateList(Data__Object *list, short int *SymbolFile__IntegrateSymbols_mid, unsigned char *SymbolFile__IntegrateSymbols_stripData, Data__Object *SymbolFile__IntegrateSymbols_IntegrateTree_o) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  i7 = (int)*list;
  i0 = i7 == 0;
  if (i0) goto l12;
  i6 = 0;
l0:
  i0 = i7 + 24;
  i3 = i7 + 36;
  i8 = (int)*(void**)i0;
  i2 = (int)*(void**)i3;
  i1 = i8 == 0;
  if (i1) goto l3;
  i8 = SymbolTable__Unnamed((Data__Struct)i8);
  if (i8) goto l1;
  i8 = (int)*(void**)i0;
  i8 += 36;
  i8 = (int)*(void**)i8;
  i8 = i7 != i8;
  if (i8) goto l3;
l1:
  i0 = (int)*(void**)i0;
  i1 = i0 + 20;
  i8 = *(signed char*)i1;
  i1 = i8 == 31;
  if (i1) goto l2;
  i8 = i8 != 28;
  if (i8) goto l3;
l2:
  i8 = i0 + 28;
  i1 = (int)*(void**)i8;
  SymbolFile__IntegrateSymbols_IntegrateTree_IntegrateList((Data__Object *)i8, &*SymbolFile__IntegrateSymbols_mid, &*SymbolFile__IntegrateSymbols_stripData, (Data__Object *)&*SymbolFile__IntegrateSymbols_IntegrateTree_o);
l3:
  i8 = i7 + 12;
  i4 = *SymbolFile__IntegrateSymbols_stripData;
  i5 = *SymbolFile__IntegrateSymbols_mid;
  *(void**)i8 = (void*)0;
  i8 = i7 + 48;
  *(short int*)i8 = i5;
  if (!(i4)) goto l7;
  i1 = i7 + 64;
  i0 = *(unsigned int*)i1;
  i1 = (i0 & ((unsigned int)1 << 0)) != 0;
  if (i1) goto l7;
  i0 = (i0 & ((unsigned int)1 << 26)) != 0;
  if (!(i0)) goto l4;
  i0 = i7 + 52;
  i0 = (int)*(void**)i0;
  i0 = i0 == 0;
  if (i0) goto l7;
l4:
  i1 = i7 + 28;
  i1 = *(signed char*)i1;
  i1 = (0xA0U & ((unsigned int)1 << i1)) != 0;
  if (i1) goto l7;
  i0 = SymbolFile__IntegrateSymbols_IntegrateTree_IntegrateList_ObjIsPtrBase((Data__Object)i7);
  if (i0) goto l7;
  *SymbolFile__IntegrateSymbols_IntegrateTree_o = (void*)i7;
  i1 = i6 == 0;
  if (i1) goto l5;
  i8 = (int)*(void**)i3;
  i1 = i6 + 36;
  *(void**)i1 = (void*)i8;
  goto l6;
l5:
  i3 = (int)*(void**)i3;
  *list = (void*)i3;
l6:
  i1 = (int)*SymbolFile__IntegrateSymbols_IntegrateTree_o;
  i8 = i1 + 20;
  i3 = i1 + 32;
  *(void**)i8 = (void*)0;
  i8 = i1 + 36;
  *(void**)i3 = (void*)0;
  i3 = i1 + 40;
  *(void**)i8 = (void*)0;
  i8 = i1 + 44;
  *(void**)i3 = (void*)0;
  i3 = i1 + 52;
  *(void**)i8 = (void*)0;
  i8 = i1 + 56;
  *(void**)i3 = (void*)0;
  *(void**)i8 = (void*)0;
  goto l11;
l7:
  i0 = i7 + 28;
  i0 = *(signed char*)i0;
  i8 = (0xC0U & ((unsigned int)1 << i0)) != 0;
  if (i8) goto l8;
  i4 = i0 != 1;
  if (i4) goto l10;
  i4 = i7 + 52;
  i4 = (int)*(void**)i4;
  i5 = i4 + 48;
  *(unsigned char*)i5 = 1;
  goto l10;
l8:
  i0 = i0 == 7;
  if (!(i0)) goto l9;
  i8 = i7 + 52;
  i0 = (int)*(void**)i8;
  SymbolFile__IntegrateSymbols_IntegrateTree_IntegrateList((Data__Object *)i8, &*SymbolFile__IntegrateSymbols_mid, &*SymbolFile__IntegrateSymbols_stripData, (Data__Object *)&*SymbolFile__IntegrateSymbols_IntegrateTree_o);
l9:
  i4 = i7 + 44;
  i0 = (int)*(void**)i4;
  SymbolFile__IntegrateSymbols_IntegrateTree((Data__Object *)i4, &*SymbolFile__IntegrateSymbols_mid, &*SymbolFile__IntegrateSymbols_stripData);
l10:
  i6 = i7;
l11:
  i8 = i2 != 0;
  if (!(i8)) goto l12;
  i7 = i2;
  goto l0;
l12:
  ;
}

void SymbolFile__IntegrateSymbols_IntegrateTree(Data__Object *tree, short int *SymbolFile__IntegrateSymbols_mid, unsigned char *SymbolFile__IntegrateSymbols_stripData) {
  register int i0;
  Data__Object list;
  Data__Object o;
  i0 = (int)*tree;
  i0 = (int)SymbolTable__TransformIntoList((Data__Object)i0);
  list = (void*)i0;
  list = (void*)i0;
  SymbolFile__IntegrateSymbols_IntegrateTree_IntegrateList((Data__Object *)(int)&list, &*SymbolFile__IntegrateSymbols_mid, &*SymbolFile__IntegrateSymbols_stripData, (Data__Object *)&o);
  i0 = (int)SymbolTable__TransformIntoTree((Data__Object)(int)list);
  *tree = (void*)i0;
}

void SymbolFile__IntegrateSymbols(Data__Object mod, unsigned char stripData) {
  register int i0, i1, i2;
  short int mid;
  i0 = SymbolFile__CreateModuleId();
  i1 = (int)mod + 44;
  i2 = (int)mod + 48;
  *(short int*)i2 = i0;
  i2 = (int)*(void**)i1;
  mid = (short int)i0;
  mid = (short int)i0;
  SymbolFile__IntegrateSymbols_IntegrateTree((Data__Object *)i1, &mid, &stripData);
  i0 = (int)mod + 36;
  i1 = (int)SymbolTable__importedMods;
  *(void**)i0 = (void*)i1;
  SymbolTable__importedMods = (void*)(int)mod;
}

void SymbolFile__WriteString(BinaryRider__Writer w, unsigned char* str, int str_0d) {
  register int i0, i1, i2;
  i2 = *(int*)((int)w-4);
  i0 = Strings__Length((const unsigned char*)(int)str, str_0d);
  i1 = (int)((_Type)i2)->tbprocs[13];
  i2 = (int)((_Type)i2)->tbprocs[3];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i1)((BinaryRider__Writer)(int)w, (int)i0);
  ((_TBP_BinaryRider__WriterDesc_WriteBytes)i2)((BinaryRider__Writer)(int)w, (unsigned char*)(int)str, str_0d, (int)0, (int)i0);
}

void SymbolFile__WriteStringConst(BinaryRider__Writer w, Data__Const const_) {
  register int i0, i1, i2, i3, i4;
  i0 = (int)const_ + 16;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i0 = *(signed char*)i0;
  i0 += -16;
  i1 = (int)_ashl(i0, 2, (unsigned int));
  i1 = (int)Data__struct + i1;
  i2 = (int)*(void**)i1;
  i0 = *(int*)((int)w-4);
  i1 = (int)const_ + 24;
  i4 = i2 + 48;
  i2 = (int)((_Type)i0)->tbprocs[13];
  i3 = *(int*)i1;
  i4 = *(int*)i4;
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i2)((BinaryRider__Writer)(int)w, (int)i3);
  i2 = (int)const_ + 20;
  i2 = (int)*(void**)i2;
  i1 = *(int*)i1;
  i1 *= i4;
  i0 = (int)((_Type)i0)->tbprocs[3];
  i3 = *(int*)(i2-8);
  ((_TBP_BinaryRider__WriterDesc_WriteBytes)i0)((BinaryRider__Writer)(int)w, (unsigned char*)i2, i3, (int)0, (int)i1);
}

Parameter__String SymbolFile__ReadString(BinaryRider__Reader r) {
  register int i0, i1, i2;
  int len;
  i1 = *(int*)((int)r-4);
  i0 = (int)((_Type)i1)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i0)((BinaryRider__Reader)(int)r, (int *)(int)&len);
  i0 = len + 1;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i0 < 0) _invalid_length(i0, _P(8034));
    _mem = GC_malloc_atomic(_not_zero(i0*1)+8);
    if (!_mem) _new_failed(_P(8023));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i0;
    i0 = (int)_var;
  }
  i1 = (int)((_Type)i1)->tbprocs[4];
  i2 = *(int*)(i0-8);
  ((_TBP_BinaryRider__ReaderDesc_ReadBytes)i1)((BinaryRider__Reader)(int)r, (unsigned char*)i0, i2, (int)0, (int)len);
  i1 = len + i0;
  *(unsigned char*)i1 = 0;
  return (void*)i0;
}

Data__Const SymbolFile__ReadStringConst(BinaryRider__Reader r, signed char form) {
  register int i0, i1, i2, i3;
  int len;
  i0 = form + -16;
  i1 = (int)_ashl(i0, 2, (unsigned int));
  i1 = (int)Data__struct + i1;
  i0 = (int)*(void**)i1;
  i3 = *(int*)((int)r-4);
  i1 = i0 + 48;
  i0 = (int)((_Type)i3)->tbprocs[14];
  i1 = *(int*)i1;
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i0)((BinaryRider__Reader)(int)r, (int *)(int)&len);
  i0 = len * i1;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i0 < 0) _invalid_length(i0, _P(8361));
    _mem = GC_malloc_atomic(_not_zero(i0*1)+8);
    if (!_mem) _new_failed(_P(8350));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i0;
    i1 = (int)_var;
  }
  i2 = *(int*)(i1-8);
  i3 = (int)((_Type)i3)->tbprocs[4];
  ((_TBP_BinaryRider__ReaderDesc_ReadBytes)i3)((BinaryRider__Reader)(int)r, (unsigned char*)i1, i2, (int)0, (int)i0);
  i0 = (int)_ashl(form, 2, (unsigned int));
  i0 = (int)Data__struct + i0;
  i0 = (int)*(void**)i0;
  i0 = (int)Data__GetStringConst((unsigned char*)i1, i2, (int)len, (Data__Struct)i0);
  return (void*)i0;
}

void SymbolFile__AppendToStructArray(Data__Struct t) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  i5 = SymbolFile__structLen;
  i7 = (int)SymbolFile__structArray;
  i6 = *(int*)(i7-8);
  i0 = i6 != i5;
  if (i0) goto l2;
  i1 = i6 - 1;
  i4 = i1 < 0;
  i6 += 64;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    if(i6 < 0) _invalid_length(i6, _P(8668));
    _mem = GC_malloc(_not_zero(i6*4)+8);
    if (!_mem) _new_failed(_P(8640));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = i6;
    i0 = (int)_var;
  }
  if (i4) goto l1;
  i4 = 0;
l0:
  i6 = (int)_ashl(i4, 2, (unsigned int));
  i6 = i7 + i6;
  i8 = (int)_ashl(i4, 2, (unsigned int));
  i8 = i0 + i8;
  i3 = i4 + 1;
  i2 = (int)*(void**)i6;
  i6 = i3 > i1;
  *(void**)i8 = (void*)i2;
  if (i6) goto l1;
  i4 = i3;
  goto l0;
l1:
  SymbolFile__structArray = (void*)i0;
l2:
  i0 = (int)SymbolFile__structArray;
  i1 = (int)_ashl(i5, 2, (unsigned int));
  i1 = i0 + i1;
  *(void**)i1 = (void*)(int)t;
  i1 = i5 + 1;
  SymbolFile__structLen = i1;
}

void SymbolFile__WriteFlags(BinaryRider__Writer w, unsigned int flags) {
  register int i0;
  i0 = *(int*)((int)w-4);
  i0 = (int)((_Type)i0)->tbprocs[13];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i0)((BinaryRider__Writer)(int)w, (int)flags);
}

void SymbolFile__Write_MarkExportedObjects_MarkObject_MarkStruct(Data__Struct t, Data__Object *SymbolFile__Write_mod) {
  register int i0, i1, i2, i3, i4;
  i0 = (int)t == 0;
  if (i0) goto l3;
  i0 = (int)t + 36;
  i3 = (int)t + 8;
  *(int*)i3 = -1;
  i1 = (int)*(void**)i0;
  i3 = i1 == 0;
  if (i3) goto l0;
  i2 = (int)*SymbolFile__Write_mod;
  i4 = SymbolTable__ImportedObject((Data__Object)i2, (Data__Object)i1);
  if (!(i4)) goto l0;
  i1 = (int)*(void**)i0;
  i1 += 40;
  i1 = (int)*(void**)i1;
  i3 = i1 + 64;
  i2 = *(unsigned int*)i3;
  i2 = i2 | ((unsigned int)1 << 27);
  *(unsigned int*)i3 = i2;
  goto l3;
l0:
  i3 = (int)t + 40;
  i2 = *(unsigned int*)i3;
  i1 = (i2 & ((unsigned int)1 << 31)) != 0;
  if (i1) goto l3;
  i2 = i2 | ((unsigned int)1 << 31);
  *(unsigned int*)i3 = i2;
  i2 = (int)t + 24;
  i2 = (int)*(void**)i2;
  SymbolFile__Write_MarkExportedObjects_MarkObject_MarkStruct((Data__Struct)i2, (Data__Object *)&*SymbolFile__Write_mod);
  i2 = (int)t + 28;
  i2 = (int)*(void**)i2;
  i3 = i2 == 0;
  if (i3) goto l2;
l1:
  i3 = i2 + 36;
  SymbolFile__Write_MarkExportedObjects_MarkObject((Data__Object)i2, (Data__Object *)&*SymbolFile__Write_mod);
  i2 = (int)*(void**)i3;
  i3 = i2 != 0;
  if (i3) goto l1;
l2:
  i2 = (int)*(void**)i0;
  SymbolFile__Write_MarkExportedObjects_MarkObject((Data__Object)i2, (Data__Object *)&*SymbolFile__Write_mod);
l3:
  ;
}

void SymbolFile__Write_MarkExportedObjects_MarkObject(Data__Object obj, Data__Object *SymbolFile__Write_mod) {
  register int i0, i1, i2;
  i0 = (int)obj == 0;
  if (i0) goto l1;
  i2 = (int)obj + 64;
  i0 = *(unsigned int*)i2;
  i1 = (i0 & ((unsigned int)1 << 27)) != 0;
  if (i1) goto l1;
  i0 = i0 | ((unsigned int)1 << 27);
  *(unsigned int*)i2 = i0;
  i2 = (int)obj + 28;
  i2 = *(signed char*)i2;
  i2 = i2 != 7;
  if (i2) goto l0;
  i2 = (int)obj + 52;
  i2 = (int)*(void**)i2;
  SymbolFile__Write_MarkExportedObjects_MarkObject((Data__Object)i2, (Data__Object *)&*SymbolFile__Write_mod);
l0:
  i2 = (int)obj + 24;
  i2 = (int)*(void**)i2;
  SymbolFile__Write_MarkExportedObjects_MarkObject_MarkStruct((Data__Struct)i2, (Data__Object *)&*SymbolFile__Write_mod);
l1:
  ;
}

void SymbolFile__Write_MarkExportedObjects(Data__Object root, Data__Object *SymbolFile__Write_mod) {
  register int i0;
  i0 = (int)root == 0;
  if (i0) goto l1;
  i0 = (int)root + 32;
  i0 = (int)*(void**)i0;
  SymbolFile__Write_MarkExportedObjects((Data__Object)i0, (Data__Object *)&*SymbolFile__Write_mod);
  i0 = (int)root + 64;
  i0 = *(unsigned int*)i0;
  i0 = (i0 & ((unsigned int)1 << 0)) != 0;
  if (!(i0)) goto l0;
  SymbolFile__Write_MarkExportedObjects_MarkObject((Data__Object)(int)root, (Data__Object *)&*SymbolFile__Write_mod);
l0:
  i0 = (int)root + 36;
  i0 = (int)*(void**)i0;
  SymbolFile__Write_MarkExportedObjects((Data__Object)i0, (Data__Object *)&*SymbolFile__Write_mod);
l1:
  ;
}

void SymbolFile__Write_WriteObject_WriteStruct_WriteObjList(Data__Object obj, BinaryRider__Writer *SymbolFile__Write_w) {
  register int i0, i1;
  i0 = (int)obj == 0;
  if (i0) goto l0;
  i0 = (int)obj + 36;
  SymbolFile__Write_WriteObject((Data__Object)(int)obj, (BinaryRider__Writer *)&*SymbolFile__Write_w);
  i0 = (int)*(void**)i0;
  SymbolFile__Write_WriteObject_WriteStruct_WriteObjList((Data__Object)i0, (BinaryRider__Writer *)&*SymbolFile__Write_w);
  goto l1;
l0:
  i1 = (int)*SymbolFile__Write_w;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[13];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i0)((BinaryRider__Writer)i1, (int)0);
l1:
  ;
}

void SymbolFile__Write_WriteObject_WriteStruct(Data__Struct t, BinaryRider__Writer *SymbolFile__Write_w, Data__Object *SymbolFile__Write_WriteObject_obj) {
  register int i0, i1, i2, i3, i4;
  i3 = (int)t + 8;
  i0 = *(int*)i3;
  i1 = i0 >= 0;
  if (i1) goto l8;
  i0 = (int)t + 20;
  i1 = *(signed char*)i0;
  i2 = i1 < 1;
  if (i2) goto l0;
  i4 = i1 <= 21;
  if (i4) goto l7;
l0:
  i1 = SymbolFile__structLen;
  *(int*)i3 = i1;
  i4 = (int)*SymbolFile__Write_WriteObject_obj;
  SymbolFile__AppendToStructArray((Data__Struct)(int)t);
  i1 = SymbolTable__LocalType((Data__Object)i4, (Data__Struct)(int)t);
  if (i1) goto l1;
  i4 = (int)t + 36;
  i3 = (int)*(void**)i4;
  i1 = (int)SymbolTable__Module((Data__Object)i3);
  i3 = (int)*SymbolFile__Write_w;
  i1 += 52;
  i1 = (int)*(void**)i1;
  i0 = *(int*)(i3-4);
  i1 += 28;
  i0 = (int)((_Type)i0)->tbprocs[13];
  i1 = *(int*)i1;
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i0)((BinaryRider__Writer)i3, (int)i1);
  i4 = (int)*(void**)i4;
  i4 += 20;
  i4 = (int)*(void**)i4;
  i1 = *(int*)(i4-8);
  SymbolFile__WriteString((BinaryRider__Writer)i3, (unsigned char*)i4, i1);
  goto l9;
l1:
  i1 = (int)*SymbolFile__Write_w;
  i3 = *(signed char*)i0;
  i2 = *(int*)(i1-4);
  i2 = (int)((_Type)i2)->tbprocs[13];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i2)((BinaryRider__Writer)i1, (int)i3);
  i3 = (int)t + 40;
  i2 = *(unsigned int*)i3;
  i2 &= 0xFFFU;
  SymbolFile__WriteFlags((BinaryRider__Writer)i1, (unsigned int)i2);
  i2 = (int)t + 44;
  i2 = *(unsigned int*)i2;
  i2 &= 0x3FU;
  SymbolFile__WriteFlags((BinaryRider__Writer)i1, (unsigned int)i2);
  i2 = *(signed char*)i0;
  i2 = i2 != 31;
  if (i2) goto l2;
  i2 = (int)t + 24;
  i2 = (int)*(void**)i2;
  i2 = i2 == 0;
  if (i2) goto l3;
l2:
  i2 = (int)t + 24;
  i2 = (int)*(void**)i2;
  SymbolFile__Write_WriteObject_WriteStruct((Data__Struct)i2, (BinaryRider__Writer *)&*SymbolFile__Write_w, (Data__Object *)&*SymbolFile__Write_WriteObject_obj);
  goto l4;
l3:
  i2 = (int)Data__struct + 84;
  i2 = (int)*(void**)i2;
  SymbolFile__Write_WriteObject_WriteStruct((Data__Struct)i2, (BinaryRider__Writer *)&*SymbolFile__Write_w, (Data__Object *)&*SymbolFile__Write_WriteObject_obj);
l4:
  i3 = *(unsigned int*)i3;
  i3 = (i3 & ((unsigned int)1 << 0)) != 0;
  if (!(i3)) goto l5;
  i3 = (int)*SymbolFile__Write_w;
  SystemFlags__WriteStructInfo((BinaryRider__Writer)i3, (Data__Struct)(int)t);
l5:
  i3 = *(signed char*)i0;
  if (i3<=26 || i3>=32) goto l9;
  if (i3==27 || i3==30) goto l9;
  if (!(i3==28 || i3==31)) goto l6;
  i3 = (int)t + 28;
  i3 = (int)*(void**)i3;
  SymbolFile__Write_WriteObject_WriteStruct_WriteObjList((Data__Object)i3, (BinaryRider__Writer *)&*SymbolFile__Write_w);
  goto l9;
l6:
  if (!(i3==29)) goto l9;
  i4 = (int)*SymbolFile__Write_w;
  i3 = *(int*)(i4-4);
  i1 = (int)t + 32;
  i3 = (int)((_Type)i3)->tbprocs[13];
  i1 = *(int*)i1;
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i3)((BinaryRider__Writer)i4, (int)i1);
  goto l9;
l7:
  i4 = (int)*SymbolFile__Write_w;
  i2 = *(int*)(i4-4);
  i2 = (int)((_Type)i2)->tbprocs[13];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i2)((BinaryRider__Writer)i4, (int)i1);
  goto l9;
l8:
  i2 = (int)*SymbolFile__Write_w;
  i1 = *(int*)(i2-4);
  i0 = - i0;
  i1 = (int)((_Type)i1)->tbprocs[13];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i1)((BinaryRider__Writer)i2, (int)i0);
l9:
  ;
}

void SymbolFile__Write_WriteObject(Data__Object obj, BinaryRider__Writer *SymbolFile__Write_w) {
  register int i0, i1, i2, i3;
  register double d0;
  i1 = (int)obj + 28;
  i2 = *(signed char*)i1;
  i0 = i2 != 2;
  if (i0) goto l0;
  i3 = (int)obj + 24;
  i3 = (int)*(void**)i3;
  i3 += 36;
  i3 = (int)*(void**)i3;
  i3 = (int)obj == i3;
  if (i3) goto l1;
l0:
  i0 = (int)*SymbolFile__Write_w;
  i3 = *(int*)(i0-4);
  i3 = (int)((_Type)i3)->tbprocs[13];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i3)((BinaryRider__Writer)i0, (int)i2);
  goto l2;
l1:
  i3 = (int)*SymbolFile__Write_w;
  i0 = *(int*)(i3-4);
  i0 = (int)((_Type)i0)->tbprocs[13];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i0)((BinaryRider__Writer)i3, (int)-2);
l2:
  i0 = *(signed char*)i1;
  i0 = i0 == 9;
  if (i0) goto l9;
  i2 = (int)*SymbolFile__Write_w;
  i1 = (int)obj + 20;
  i1 = (int)*(void**)i1;
  i0 = *(int*)(i1-8);
  SymbolFile__WriteString((BinaryRider__Writer)i2, (unsigned char*)i1, i0);
  i1 = (int)obj + 64;
  i1 = *(unsigned int*)i1;
  i1 &= 0x7FFU;
  SymbolFile__WriteFlags((BinaryRider__Writer)i2, (unsigned int)i1);
  i1 = (int)obj + 68;
  i1 = *(unsigned int*)i1;
  i1 &= 0x7FU;
  SymbolFile__WriteFlags((BinaryRider__Writer)i2, (unsigned int)i1);
  i1 = (int)obj + 24;
  i1 = (int)*(void**)i1;
  SymbolFile__Write_WriteObject_WriteStruct((Data__Struct)i1, (BinaryRider__Writer *)&*SymbolFile__Write_w, (Data__Object *)&obj);
  i1 = (int)obj + 64;
  i1 = *(unsigned int*)i1;
  i1 = (i1 & ((unsigned int)1 << 3)) != 0;
  if (!(i1)) goto l3;
  i1 = (int)*SymbolFile__Write_w;
  SystemFlags__WriteObjectInfo((BinaryRider__Writer)i1, (Data__Object)(int)obj);
l3:
  i1 = (int)obj + 28;
  i0 = *(signed char*)i1;
  i1 = i0 == 1;
  if (i1) goto l4;
  i0 = i0 != 7;
  if (i0) goto l9;
  i1 = (int)*SymbolFile__Write_w;
  i2 = *(int*)(i1-4);
  i0 = (int)obj + 60;
  i2 = (int)((_Type)i2)->tbprocs[13];
  i0 = *(int*)i0;
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i2)((BinaryRider__Writer)i1, (int)i0);
  i2 = (int)obj + 52;
  i2 = (int)*(void**)i2;
  SymbolFile__Write_WriteObject((Data__Object)i2, (BinaryRider__Writer *)&*SymbolFile__Write_w);
  goto l9;
l4:
  i0 = (int)obj + 24;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i0 = *(signed char*)i0;
  if (i0<=0 || (i0>=10 && i0<=11) || (i0>=16 && i0<=17) || i0>=21) goto l9;
  if (!((i0>=1 && i0<=7))) goto l5;
  i1 = (int)*SymbolFile__Write_w;
  i0 = (int)obj + 52;
  i0 = (int)*(void**)i0;
  i2 = *(int*)(i1-4);
  i0 += 24;
  i2 = (int)((_Type)i2)->tbprocs[13];
  i0 = *(int*)i0;
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i2)((BinaryRider__Writer)i1, (int)i0);
  goto l9;
l5:
  if (!((i0>=8 && i0<=9))) goto l6;
  i2 = (int)*SymbolFile__Write_w;
  i1 = (int)obj + 52;
  i0 = (int)*(void**)i1;
  i1 = *(int*)(i2-4);
  i0 += 40;
  i1 = (int)((_Type)i1)->tbprocs[15];
  d0 = *(double*)i0;
  ((_TBP_BinaryRider__WriterDesc_WriteLReal)i1)((BinaryRider__Writer)i2, (double)d0);
  goto l9;
l6:
  if (!((i0>=12 && i0<=15))) goto l7;
  i2 = (int)*SymbolFile__Write_w;
  i1 = (int)obj + 52;
  i1 = (int)*(void**)i1;
  i0 = *(int*)(i2-4);
  i1 += 32;
  i0 = (int)((_Type)i0)->tbprocs[16];
  i1 = *(unsigned int*)i1;
  ((_TBP_BinaryRider__WriterDesc_WriteSet)i0)((BinaryRider__Writer)i2, (unsigned int)i1);
  goto l9;
l7:
  if (!((i0>=18 && i0<=19))) goto l8;
  i1 = (int)obj + 52;
  i1 = (int)*(void**)i1;
  i0 = (int)*SymbolFile__Write_w;
  SymbolFile__WriteStringConst((BinaryRider__Writer)i0, (Data__Const)i1);
  goto l9;
l8:
  if (!(i0==20)) goto l9;
l9:
  ;
}

void SymbolFile__Write_WriteTree(Data__Object obj, BinaryRider__Writer *SymbolFile__Write_w) {
  register int i0;
  i0 = (int)obj == 0;
  if (i0) goto l1;
  i0 = (int)obj + 32;
  i0 = (int)*(void**)i0;
  SymbolFile__Write_WriteTree((Data__Object)i0, (BinaryRider__Writer *)&*SymbolFile__Write_w);
  i0 = (int)obj + 64;
  i0 = *(unsigned int*)i0;
  i0 = (i0 & ((unsigned int)1 << 27)) != 0;
  if (!(i0)) goto l0;
  i0 = (int)obj + 28;
  i0 = *(signed char*)i0;
  i0 = i0 == 8;
  if (i0) goto l0;
  SymbolFile__Write_WriteObject((Data__Object)(int)obj, (BinaryRider__Writer *)&*SymbolFile__Write_w);
l0:
  i0 = (int)obj + 36;
  i0 = (int)*(void**)i0;
  SymbolFile__Write_WriteTree((Data__Object)i0, (BinaryRider__Writer *)&*SymbolFile__Write_w);
l1:
  ;
}

Data__Object SymbolFile__Write_WriteUsedImports_GetModule(const unsigned char* lowerBound, int lowerBound_0d) {
  register int i0, i1, i2, i3;
  i2 = (int)SymbolTable__importedMods;
  i0 = i2 != 0;
  if (i0) goto l0;
  i3 = 0;
  goto l4;
l0:
  i3 = 0;
l1:
  i0 = i2 + 64;
  i0 = *(unsigned int*)i0;
  i0 = (i0 & ((unsigned int)1 << 27)) != 0;
  if (!(i0)) goto l3;
  i1 = i2 + 20;
  i1 = (int)*(void**)i1;
  i0 = strcmp((const char*) (int)lowerBound, (const char*) i1) >= 0;
  if (i0) goto l3;
  i0 = i3 == 0;
  if (i0) goto l2;
  i0 = i3 + 20;
  i0 = (int)*(void**)i0;
  i1 = strcmp((const char*) i1, (const char*) i0) >= 0;
  if (i1) goto l3;
l2:
  i3 = i2;
l3:
  i0 = i2 + 36;
  i2 = (int)*(void**)i0;
  i0 = i2 != 0;
  if (i0) goto l1;
l4:
  return (void*)i3;
}

void SymbolFile__Write_WriteUsedImports(int *SymbolFile__Write_importIndex, BinaryRider__Writer *SymbolFile__Write_w) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  i7 = (int)SymbolFile__Write_WriteUsedImports_GetModule((const unsigned char*)(int)_c1, 1);
  i0 = i7 == 0;
  if (i0) goto l1;
  i8 = (int)*SymbolFile__Write_w;
  i6 = *(int*)(i8-4);
  i0 = (int)((_Type)i6)->tbprocs[12];
l0:
  i1 = i7 + 52;
  i2 = (int)*(void**)i1;
  i3 = *SymbolFile__Write_importIndex;
  i4 = i7 + 20;
  i5 = (int)*(void**)i4;
  i6 = i2 + 28;
  *(int*)i6 = i3;
  i2 = i3 + 1;
  i3 = *(int*)(i5-8);
  *SymbolFile__Write_importIndex = i2;
  SymbolFile__WriteString((BinaryRider__Writer)i8, (unsigned char*)i5, i3);
  i1 = (int)*(void**)i1;
  i1 += 24;
  i1 = *(int*)i1;
  ((_TBP_BinaryRider__WriterDesc_WriteLInt)i0)((BinaryRider__Writer)i8, (int)i1);
  i2 = (int)*(void**)i4;
  i1 = *(int*)(i2-8);
  i7 = (int)SymbolFile__Write_WriteUsedImports_GetModule((const unsigned char*)i2, i1);
  i1 = i7 != 0;
  if (i1) goto l0;
l1:
  ;
}

void SymbolFile__Write_WriteOtherImports(Data__Object obj, BinaryRider__Writer *SymbolFile__Write_w) {
  register int i0, i1, i2, i3, i4, i5;
  i0 = (int)obj == 0;
  if (i0) goto l1;
  i4 = (int)obj + 32;
  i4 = (int)*(void**)i4;
  SymbolFile__Write_WriteOtherImports((Data__Object)i4, (BinaryRider__Writer *)&*SymbolFile__Write_w);
  i0 = (int)*SymbolFile__Write_w;
  i4 = (int)obj + 28;
  i4 = *(signed char*)i4;
  i4 = i4 != 8;
  if (i4) goto l0;
  i5 = (int)obj + 52;
  i5 = (int)*(void**)i5;
  i5 += 20;
  i1 = (int)*(void**)i5;
  i5 = *(int*)(i1-8);
  i2 = (int)SymbolFile__FindImportedModule((const unsigned char*)i1, i5);
  i3 = i2 + 64;
  i4 = *(unsigned int*)i3;
  i4 = (i4 & ((unsigned int)1 << 27)) != 0;
  if (i4) goto l0;
  SymbolFile__WriteString((BinaryRider__Writer)i0, (unsigned char*)i1, i5);
  i1 = i2 + 52;
  i1 = (int)*(void**)i1;
  i5 = *(int*)(i0-4);
  i1 += 24;
  i5 = (int)((_Type)i5)->tbprocs[12];
  i1 = *(int*)i1;
  ((_TBP_BinaryRider__WriterDesc_WriteLInt)i5)((BinaryRider__Writer)i0, (int)i1);
  i1 = *(unsigned int*)i3;
  i1 = i1 | ((unsigned int)1 << 27);
  *(unsigned int*)i3 = i1;
l0:
  i4 = (int)obj + 36;
  i4 = (int)*(void**)i4;
  SymbolFile__Write_WriteOtherImports((Data__Object)i4, (BinaryRider__Writer *)&*SymbolFile__Write_w);
l1:
  ;
}

void SymbolFile__Write_Fingerprint(Files__File f, int startPos, unsigned char* key, int key_0d) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  unsigned char byte;
  i7 = (int)BinaryRider__ConnectReader((Channel__Channel)(int)f);
  i2 = 0;
l0:
  i3 = i2 + 1;
  i1 = (int)key + i2;
  i0 = i3 > 3;
  *(unsigned char*)i1 = 0;
  if (i0) goto l1;
  i2 = i3;
  goto l0;
l1:
  i0 = *(int*)(i7-4);
  i8 = (int)((_Type)i0)->tbprocs[7];
  i0 = (int)((_Type)i0)->tbprocs[1];
  ((_TBP_BinaryRider__ReaderDesc_SetPos)i0)((BinaryRider__Reader)i7, (int)startPos);
  ((_TBP_BinaryRider__ReaderDesc_ReadChar)i8)((BinaryRider__Reader)i7, (unsigned char *)(int)&byte);
  i0 = (int)*(void**)i7;
  i0 = i0 != 0;
  if (i0) goto l5;
  i1 = (int)byte;
  i2 = 0;
  i0 = 0;
l2:
  i4 = i0 + 1;
  i3 = i4 == 4;
  if (i3) goto l3;
  i3 = i2;
  goto l4;
l3:
  i3 = i2 + 1;
  i3 &= 0x7U;
  i4 = 0;
l4:
  i5 = (int)key + i0;
  i6 = *(unsigned char*)i5;
  i2 = (unsigned char)_rot(i1, i2, 8, (unsigned char));
  i2 = i6 + i2;
  i2 &= 0xFFU;
  *(unsigned char*)i5 = i2;
  byte = (unsigned char)i1;
  byte = (unsigned char)i1;
  ((_TBP_BinaryRider__ReaderDesc_ReadChar)i8)((BinaryRider__Reader)i7, (unsigned char *)(int)&byte);
  i0 = (int)*(void**)i7;
  i0 = i0 != 0;
  if (i0) goto l5;
  i1 = (int)byte;
  i2 = i3;
  i0 = i4;
  goto l2;
l5:
  ;
}

unsigned char SymbolFile__Write_GetPreviousMagic(int *magic, Data__Object *SymbolFile__Write_mod) {
  register int i0, i1, i2, i3, i4, i5;
  Parameter__Filename fileName;
  Msg__Msg res;
  unsigned char symId[5];
  i0 = (int)*SymbolFile__Write_mod;
  i0 += 20;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-8);
  i0 = ParamPaths__FindPathExt((const unsigned char*)i0, i1, (const unsigned char*)(int)_c2, 4, (unsigned char)0, (unsigned char*)(int)fileName, 256);
  if (i0) goto l0;
  i4 = 0;
  goto l3;
l0:
  i0 = (int)Files__Old((const unsigned char*)(int)fileName, 256, (unsigned int)0x1U, (Msg__Msg *)(int)&res);
  i3 = i0 != 0;
  if (i3) goto l1;
  i4 = 0;
  goto l3;
l1:
  i2 = (int)BinaryRider__ConnectReader((Channel__Channel)i0);
  i3 = *(int*)(i2-4);
  (void)memcpy((void*) (int)symId, (const void*) (int)_c3, 5);
  i1 = (int)((_Type)i3)->tbprocs[4];
  ((_TBP_BinaryRider__ReaderDesc_ReadBytes)i1)((BinaryRider__Reader)i2, (unsigned char*)(int)symId, 5, (int)0, (int)4);
  i4 = strcmp((const char*) (int)symId, (const char*) (int)SymbolFile__symbolFileId) == 0;
  if (i4) goto l2;
  i1 = *(int*)(i0-4);
  i1 = (int)((_Type)i1)->tbprocs[5];
  ((_TBP_Files__FileDesc_Close)i1)((Files__File)i0);
  goto l3;
l2:
  i5 = (int)((_Type)i3)->tbprocs[13];
  i1 = *(int*)(i0-4);
  i3 = *magic;
  ((_TBP_BinaryRider__ReaderDesc_ReadLInt)i5)((BinaryRider__Reader)i2, (int *)(int)magic);
  i5 = (int)((_Type)i1)->tbprocs[5];
  ((_TBP_Files__FileDesc_Close)i5)((Files__File)i0);
  i5 = (int)*(void**)i2;
  i5 = i5 == 0;
l3:
  if (i4) goto l4;
  i5 = 0;
l4:
  return (unsigned char)i5;
}

void SymbolFile__Write_ClearImportedMods(Data__Object obj) {
  register int i0, i1;
  i0 = (int)obj == 0;
  if (i0) goto l0;
  i0 = (int)obj + 64;
  i1 = *(unsigned int*)i0;
  i1 = i1 & ~((unsigned int)1 << 27);
  *(unsigned int*)i0 = i1;
  i0 = (int)obj + 36;
  i0 = (int)*(void**)i0;
  SymbolFile__Write_ClearImportedMods((Data__Object)i0);
l0:
  ;
}

void SymbolFile__Write(Data__Object mod, unsigned char *newSymbolFile, unsigned char *symbolFileChanged) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8;
  Parameter__Filename fileName;
  int importIndex;
  int magicId;
  int magicOld;
  unsigned char msg[256];
  Msg__Msg res;
  BinaryRider__Writer w;
  i1 = SymbolFile__Write_GetPreviousMagic((int *)(int)&magicOld, (Data__Object *)&mod);
  i6 = (int)mod + 20;
  i0 = (int)*(void**)i6;
  i1 = ! i1;
  i2 = *(int*)(i0-8);
  *newSymbolFile = i1;
  ParamPaths__GeneratePathExt((const unsigned char*)i0, i2, (const unsigned char*)(int)_c2, 4, (unsigned char*)(int)fileName, 256);
  i7 = (int)Files__Tmp((const unsigned char*)(int)fileName, 256, (unsigned int)0x3U, (Msg__Msg *)(int)&res);
  i0 = i7 == 0;
  if (i0) goto l7;
  i5 = (int)BinaryRider__ConnectWriter((Channel__Channel)i7);
  i8 = *(int*)(i5-4);
  i4 = (int)((_Type)i8)->tbprocs[3];
  i8 = (int)((_Type)i8)->tbprocs[12];
  ((_TBP_BinaryRider__WriterDesc_WriteBytes)i4)((BinaryRider__Writer)i5, (unsigned char*)(int)SymbolFile__symbolFileId, 5, (int)0, (int)4);
  ((_TBP_BinaryRider__WriterDesc_WriteLInt)i8)((BinaryRider__Writer)i5, (int)0);
  i4 = (int)*(void**)i6;
  i6 = *(int*)(i4-8);
  SymbolFile__WriteString((BinaryRider__Writer)i5, (unsigned char*)i4, i6);
  i4 = (int)SymbolTable__importedMods;
  SymbolFile__Write_ClearImportedMods((Data__Object)i4);
  i4 = (int)mod + 44;
  i4 = (int)*(void**)i4;
  SymbolFile__Write_MarkExportedObjects((Data__Object)i4, (Data__Object *)&mod);
  importIndex = (int)32;
  w = (void*)i5;
  importIndex = (int)32;
  w = (void*)i5;
  SymbolFile__Write_WriteUsedImports(&importIndex, (BinaryRider__Writer *)&w);
  i3 = (int)mod + 44;
  SymbolFile__WriteString((BinaryRider__Writer)(int)w, (unsigned char*)(int)SymbolFile__emptyString, 2);
  i5 = (int)*(void**)i3;
  SymbolFile__Write_WriteOtherImports((Data__Object)i5, (BinaryRider__Writer *)&w);
  i5 = *(int*)((int)w-4);
  i6 = (int)((_Type)i5)->tbprocs[13];
  SymbolFile__WriteString((BinaryRider__Writer)(int)w, (unsigned char*)(int)SymbolFile__emptyString, 2);
  i4 = (int)mod + 64;
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i6)((BinaryRider__Writer)(int)w, (int)1);
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i6)((BinaryRider__Writer)(int)w, (int)4);
  i6 = *(unsigned int*)i4;
  i6 &= 0x7FFU;
  SymbolFile__WriteFlags((BinaryRider__Writer)(int)w, (unsigned int)i6);
  i6 = (int)mod + 68;
  i6 = *(unsigned int*)i6;
  i6 &= 0x7FU;
  SymbolFile__WriteFlags((BinaryRider__Writer)(int)w, (unsigned int)i6);
  i4 = *(unsigned int*)i4;
  i4 = (i4 & ((unsigned int)1 << 3)) != 0;
  if (!(i4)) goto l0;
  SystemFlags__WriteObjectInfo((BinaryRider__Writer)(int)w, (Data__Object)(int)mod);
l0:
  i5 = (int)((_Type)i5)->tbprocs[0];
  i5 = ((_TBP_BinaryRider__WriterDesc_Pos)i5)((BinaryRider__Writer)(int)w);
  i4 = (int)mod + 52;
  i8 = *(int*)(i7-4);
  i6 = (int)((_Type)i8)->tbprocs[7];
  i8 = (int)((_Type)i8)->tbprocs[5];
  SymbolFile__structLen = 0;
  i3 = (int)*(void**)i3;
  SymbolFile__Write_WriteTree((Data__Object)i3, (BinaryRider__Writer *)&w);
  i3 = *(int*)((int)w-4);
  i1 = (int)((_Type)i3)->tbprocs[13];
  i2 = (int)((_Type)i3)->tbprocs[1];
  ((_TBP_BinaryRider__WriterDesc_WriteNum)i1)((BinaryRider__Writer)(int)w, (int)0);
  SymbolFile__Write_Fingerprint((Files__File)i7, (int)i5, (unsigned char*)(int)&magicId, 4);
  i5 = (int)((_Type)i3)->tbprocs[12];
  ((_TBP_BinaryRider__WriterDesc_SetPos)i2)((BinaryRider__Writer)(int)w, (int)4);
  ((_TBP_BinaryRider__WriterDesc_WriteLInt)i5)((BinaryRider__Writer)(int)w, (int)magicId);
  i5 = (int)*(void**)i4;
  i4 = i5 + 24;
  *(int*)i4 = magicId;
  i5 = *newSymbolFile;
  if (i5) goto l1;
  i5 = magicId != magicOld;
  *symbolFileChanged = i5;
  goto l2;
l1:
  *symbolFileChanged = 0;
l2:
  i5 = (int)*(void**)(int)w;
  i4 = i5 == 0;
  if (i4) goto l3;
  i4 = *(int*)(i5-4);
  i4 = (int)((_Type)i4)->tbprocs[3];
  ((_TBP_Msg__MsgDesc_GetText)i4)((Msg__Msg)i5, (Msg__String)(int)msg, 256);
  Error__FileError((const unsigned char*)(int)_c4, 24, (const unsigned char*)(int)fileName, 256, (const unsigned char*)(int)msg, 256);
l3:
  ((_TBP_Files__FileDesc_Register)i6)((Files__File)i7);
  i5 = (int)*(void**)i7;
  i4 = i5 == 0;
  if (i4) goto l4;
  i4 = *(int*)(i5-4);
  i4 = (int)((_Type)i4)->tbprocs[3];
  ((_TBP_Msg__MsgDesc_GetText)i4)((Msg__Msg)i5, (Msg__String)(int)msg, 256);
  Error__FileError((const unsigned char*)(int)_c5, 28, (const unsigned char*)(int)fileName, 256, (const unsigned char*)(int)msg, 256);
l4:
  ((_TBP_Files__FileDesc_Close)i8)((Files__File)i7);
  i4 = (int)*(void**)i7;
  i5 = i4 == 0;
  if (i5) goto l5;
  i5 = *(int*)(i4-4);
  i5 = (int)((_Type)i5)->tbprocs[3];
  ((_TBP_Msg__MsgDesc_GetText)i5)((Msg__Msg)i4, (Msg__String)(int)msg, 256);
  Error__FileError((const unsigned char*)(int)_c6, 24, (const unsigned char*)(int)fileName, 256, (const unsigned char*)(int)msg, 256);
l5:
  i5 = SymbolFile__structLen;
  i1 = i5 - 1;
  i5 = i1 < 0;
  if (i5) goto l8;
  i5 = 0;
l6:
  i4 = (int)SymbolFile__structArray;
  i6 = (int)_ashl(i5, 2, (unsigned int));
  i6 = i4 + i6;
  i0 = (int)*(void**)i6;
  i8 = i0 + 40;
  i3 = i0 + 8;
  *(int*)i3 = -1;
  i2 = *(unsigned int*)i8;
  i3 = i5 + 1;
  i2 = i2 & ~((unsigned int)1 << 31);
  i7 = i3 > i1;
  *(unsigned int*)i8 = i2;
  *(void**)i6 = (void*)0;
  if (i7) goto l8;
  i5 = i3;
  goto l6;
l7:
  i0 = *(int*)((int)res-4);
  i0 = (int)((_Type)i0)->tbprocs[3];
  ((_TBP_Msg__MsgDesc_GetText)i0)((Msg__Msg)(int)res, (Msg__String)(int)msg, 256);
  Error__FileError((const unsigned char*)(int)_c7, 36, (const unsigned char*)(int)fileName, 256, (const unsigned char*)(int)msg, 256);
l8:
  ;
}

void SymbolFile__ReadFlags(BinaryRider__Reader r, unsigned int *flags) {
  register int i0;
  int i;
  i0 = *(int*)((int)r-4);
  i0 = (int)((_Type)i0)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i0)((BinaryRider__Reader)(int)r, (int *)(int)&i);
  *flags = i;
}

void SymbolFile__Read_Abort(Parameter__Filename SymbolFile__Read_fileName, BinaryRider__Reader *SymbolFile__Read_r) {
  register int i0, i1;
  unsigned char msg[256];
  unsigned char num[32];
  (void)memcpy((void*) (int)msg, (const void*) (int)_c8, 13);
  Strings__Append((const unsigned char*)(int)SymbolFile__Read_fileName, 256, (unsigned char*)(int)msg, 256);
  i0 = (int)*SymbolFile__Read_r;
  i1 = *(int*)(i0-4);
  Strings__Append((const unsigned char*)(int)_c9, 30, (unsigned char*)(int)msg, 256);
  i1 = (int)((_Type)i1)->tbprocs[0];
  i0 = ((_TBP_BinaryRider__ReaderDesc_Pos)i1)((BinaryRider__Reader)i0);
  IntStr__IntToStr((int)i0, (unsigned char*)(int)num, 32);
  Strings__Append((const unsigned char*)(int)num, 32, (unsigned char*)(int)msg, 256);
  Parameter__FatalError((const unsigned char*)(int)msg, 256);
}

void SymbolFile__Read_ReadObject_ReadStruct_ReadObjList(Data__Object *obj, unsigned char parameter, BinaryRider__Reader *SymbolFile__Read_r, Data__Struct *SymbolFile__Read_ReadObject_ReadStruct_t, Parameter__Filename SymbolFile__Read_fileName, Data__Object *SymbolFile__Read_mod, struct SymbolFile__Read_ModuleListDesc* *SymbolFile__Read_modList) {
  register int i0, i1, i2, i3;
  int mode;
  i2 = (int)*SymbolFile__Read_r;
  i0 = *(int*)(i2-4);
  i0 = (int)((_Type)i0)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i0)((BinaryRider__Reader)i2, (int *)(int)&mode);
  i0 = mode == 0;
  if (i0) goto l1;
  i2 = (int)SymbolFile__Read_ReadObject((int)mode, (BinaryRider__Reader *)&*SymbolFile__Read_r, SymbolFile__Read_fileName, (Data__Object *)&*SymbolFile__Read_mod, (struct SymbolFile__Read_ModuleListDesc* *)&*SymbolFile__Read_modList);
  *obj = (void*)i2;
  i2 = (int)*obj;
  i1 = (int)*SymbolFile__Read_ReadObject_ReadStruct_t;
  i3 = i2 + 40;
  *(void**)i3 = (void*)i1;
  if (!(parameter)) goto l0;
  i3 = (int)*obj;
  i0 = i3 + 64;
  i2 = *(unsigned int*)i0;
  i2 = i2 | ((unsigned int)1 << 26);
  *(unsigned int*)i0 = i2;
l0:
  i3 = (int)*obj;
  i0 = i3 + 36;
  i2 = (int)*(void**)i0;
  SymbolFile__Read_ReadObject_ReadStruct_ReadObjList((Data__Object *)i0, (unsigned char)parameter, (BinaryRider__Reader *)&*SymbolFile__Read_r, (Data__Struct *)&*SymbolFile__Read_ReadObject_ReadStruct_t, SymbolFile__Read_fileName, (Data__Object *)&*SymbolFile__Read_mod, (struct SymbolFile__Read_ModuleListDesc* *)&*SymbolFile__Read_modList);
  goto l2;
l1:
  *obj = (void*)0;
l2:
  ;
}

Data__Struct SymbolFile__Read_ReadObject_ReadStruct(BinaryRider__Reader *SymbolFile__Read_r, struct SymbolFile__Read_ModuleListDesc* *SymbolFile__Read_modList, Parameter__Filename SymbolFile__Read_fileName, Data__Object *SymbolFile__Read_mod) {
  register int i0, i1, i2, i3, i4, i5, i6;
  int form;
  Data__Struct t;
  i5 = (int)*SymbolFile__Read_r;
  i0 = *(int*)(i5-4);
  i0 = (int)((_Type)i0)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i0)((BinaryRider__Reader)i5, (int *)(int)&form);
  i0 = form <= 0;
  if (i0) goto l15;
  i4 = form <= 21;
  if (i4) goto l14;
  i0 = form > 31;
  if (i0) goto l6;
  i6 = (int)SymbolTable__NewStruct((signed char)form, (int)-1);
  i2 = i6 + 40;
  i4 = i6 + 44;
  SymbolFile__AppendToStructArray((Data__Struct)i6);
  i3 = *(unsigned int*)i2;
  SymbolFile__ReadFlags((BinaryRider__Reader)i5, (unsigned int *)i2);
  i0 = i6 + 24;
  i3 = *(unsigned int*)i4;
  SymbolFile__ReadFlags((BinaryRider__Reader)i5, (unsigned int *)i4);
  i4 = (int)SymbolFile__Read_ReadObject_ReadStruct((BinaryRider__Reader *)&*SymbolFile__Read_r, (struct SymbolFile__Read_ModuleListDesc* *)&*SymbolFile__Read_modList, SymbolFile__Read_fileName, (Data__Object *)&*SymbolFile__Read_mod);
  i1 = i6 + 20;
  *(void**)i0 = (void*)i4;
  i4 = *(signed char*)i1;
  i4 = i4 != 31;
  if (i4) goto l1;
  i3 = (int)*(void**)i0;
  i4 = i3 + 20;
  i4 = *(signed char*)i4;
  i4 = i4 == 21;
  if (i4) goto l0;
  i3 += 32;
  i0 = *(int*)i3;
  i3 = i6 + 32;
  i0++;
  *(int*)i3 = i0;
  goto l1;
l0:
  *(void**)i0 = (void*)0;
l1:
  i4 = *(unsigned int*)i2;
  i4 = (i4 & ((unsigned int)1 << 0)) != 0;
  if (!(i4)) goto l2;
  i4 = (int)*SymbolFile__Read_r;
  SystemFlags__ReadStructInfo((BinaryRider__Reader)i4, (Data__Struct)i6);
l2:
  i1 = *(signed char*)i1;
  if (!(i1<=26 || i1>=32)) goto l3;
  i4 = 1;
  goto l13;
l3:
  if (!(i1==27 || i1==30)) goto l4;
  i4 = 0;
  goto l13;
l4:
  if (!(i1==28 || i1==31)) goto l5;
  i2 = i6 + 28;
  i4 = i1 == 28;
  i3 = (int)*(void**)i2;
  t = (void*)i6;
  t = (void*)i6;
  SymbolFile__Read_ReadObject_ReadStruct_ReadObjList((Data__Object *)i2, (unsigned char)i4, (BinaryRider__Reader *)&*SymbolFile__Read_r, (Data__Struct *)&t, SymbolFile__Read_fileName, (Data__Object *)&*SymbolFile__Read_mod, (struct SymbolFile__Read_ModuleListDesc* *)&*SymbolFile__Read_modList);
  i4 = 0;
  i6 = (int)t;
  goto l13;
l5:
  if (!(i1==29)) goto l13;
  i2 = (int)*SymbolFile__Read_r;
  i3 = i6 + 32;
  i4 = *(int*)(i2-4);
  i1 = *(int*)i3;
  i4 = (int)((_Type)i4)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i4)((BinaryRider__Reader)i2, (int *)i3);
  i4 = 0;
  goto l13;
l6:
  i2 = (int)SymbolFile__ReadString((BinaryRider__Reader)i5);
  i1 = (int)*SymbolFile__Read_modList;
  i6 = form != 32;
  if (i6) goto l7;
  i0 = i1;
  goto l9;
l7:
  i6 = form;
  i0 = i1;
l8:
  i6--;
  i0 = (int)*(void**)i0;
  i3 = i6 != 32;
  if (i3) goto l8;
l9:
  i6 = i0 == 0;
  if (!(i6)) goto l10;
  SymbolFile__Read_Abort(SymbolFile__Read_fileName, (BinaryRider__Reader *)&*SymbolFile__Read_r);
l10:
  i6 = *(int*)(i2-8);
  i3 = i0 + 4;
  i3 = (int)*(void**)i3;
  i6 = (int)SymbolTable__FindDecl((Data__Addressable)i3, (const unsigned char*)i2, i6);
  i3 = i6 == 0;
  if (i3) goto l11;
  i3 = i6 + 28;
  i3 = *(signed char*)i3;
  i3 = i3 == 2;
  if (i3) goto l12;
l11:
  SymbolFile__Read_Abort(SymbolFile__Read_fileName, (BinaryRider__Reader *)&*SymbolFile__Read_r);
l12:
  i6 += 24;
  i6 = (int)*(void**)i6;
  SymbolFile__AppendToStructArray((Data__Struct)i6);
  i4 = 0;
l13:
  if (!(i4)) goto l16;
  goto l16;
l14:
  i6 = (int)_ashl(form, 2, (unsigned int));
  i6 = (int)Data__struct + i6;
  i6 = (int)*(void**)i6;
  goto l16;
l15:
  i6 = - form;
  i0 = (int)SymbolFile__structArray;
  i1 = (int)_ashl(i6, 2, (unsigned int));
  i1 = i0 + i1;
  i6 = (int)*(void**)i1;
l16:
  return (void*)i6;
}

Data__Object SymbolFile__Read_ReadObject(int mode, BinaryRider__Reader *SymbolFile__Read_r, Parameter__Filename SymbolFile__Read_fileName, Data__Object *SymbolFile__Read_mod, struct SymbolFile__Read_ModuleListDesc* *SymbolFile__Read_modList) {
  register int i0, i1, i2, i3, i4, i5, i6, i7;
  int valInt;
  double valReal;
  unsigned int valSet;
  i0 = mode == (-2147483647-1);
  if (i0) goto l0;
  i5 = mode;
  goto l1;
l0:
  i1 = (int)*SymbolFile__Read_r;
  i0 = *(int*)(i1-4);
  i0 = (int)((_Type)i0)->tbprocs[14];
  mode = (int)(-2147483647-1);
  mode = (int)(-2147483647-1);
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i0)((BinaryRider__Reader)i1, (int *)(int)&mode);
  i5 = mode;
l1:
  i0 = i5 == 9;
  if (i0) goto l16;
  i4 = i5 == -2;
  if (i4) goto l3;
  i4 = i5 < 0;
  if (i4) goto l2;
  i4 = i5 <= 7;
  if (i4) goto l3;
l2:
  SymbolFile__Read_Abort(SymbolFile__Read_fileName, (BinaryRider__Reader *)&*SymbolFile__Read_r);
l3:
  i3 = (int)*SymbolFile__Read_r;
  i4 = (int)SymbolFile__ReadString((BinaryRider__Reader)i3);
  i2 = (int)*SymbolFile__Read_mod;
  i7 = _abs(i5);
  i1 = *(int*)(i4-8);
  i7 = (int)SymbolTable__NewObject((const unsigned char*)i4, i1, (signed char)i7, (int)-1);
  i1 = i7 + 64;
  i6 = i2 + 48;
  i4 = i7 + 48;
  i6 = *(short int*)i6;
  *(short int*)i4 = i6;
  i4 = i7 + 24;
  i6 = i7 + 68;
  i0 = *(unsigned int*)i1;
  SymbolFile__ReadFlags((BinaryRider__Reader)i3, (unsigned int *)i1);
  i0 = *(unsigned int*)i6;
  SymbolFile__ReadFlags((BinaryRider__Reader)i3, (unsigned int *)i6);
  i3 = (int)SymbolFile__Read_ReadObject_ReadStruct((BinaryRider__Reader *)&*SymbolFile__Read_r, (struct SymbolFile__Read_ModuleListDesc* *)&*SymbolFile__Read_modList, SymbolFile__Read_fileName, (Data__Object *)&*SymbolFile__Read_mod);
  *(void**)i4 = (void*)i3;
  i3 = *(unsigned int*)i1;
  i3 = (i3 & ((unsigned int)1 << 3)) != 0;
  if (!(i3)) goto l4;
  i3 = (int)*SymbolFile__Read_r;
  SystemFlags__ReadObjectInfo((BinaryRider__Reader)i3, (Data__Object)i7);
l4:
  i3 = i5 == -2;
  if (i3) goto l13;
  i1 = i5 == 1;
  if (i1) goto l6;
  i6 = i5 != 7;
  if (i6) goto l5;
  i1 = (int)*SymbolFile__Read_r;
  i2 = i7 + 60;
  i3 = *(int*)(i1-4);
  i6 = *(int*)i2;
  i3 = (int)((_Type)i3)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i3)((BinaryRider__Reader)i1, (int *)i2);
  i2 = i7 + 52;
  i1 = (int)SymbolFile__Read_ReadObject((int)(-2147483647-1), (BinaryRider__Reader *)&*SymbolFile__Read_r, SymbolFile__Read_fileName, (Data__Object *)&*SymbolFile__Read_mod, (struct SymbolFile__Read_ModuleListDesc* *)&*SymbolFile__Read_modList);
  *(void**)i2 = (void*)i1;
l5:
  i6 = 0;
  goto l14;
l6:
  i2 = (int)*(void**)i4;
  i2 += 20;
  i6 = *(signed char*)i2;
  if (!(i6<=0 || (i6>=10 && i6<=11) || (i6>=16 && i6<=17) || i6>=21)) goto l7;
  i6 = 1;
  goto l12;
l7:
  if (!((i6>=1 && i6<=7))) goto l8;
  i2 = (int)*SymbolFile__Read_r;
  i6 = *(int*)(i2-4);
  i6 = (int)((_Type)i6)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i6)((BinaryRider__Reader)i2, (int *)(int)&valInt);
  i6 = (int)*(void**)i4;
  i6 += 20;
  i2 = *(signed char*)i6;
  i6 = (int)_ashl(i2, 2, (unsigned int));
  i6 = (int)Data__struct + i6;
  i6 = (int)*(void**)i6;
  i2 = i7 + 52;
  i6 = (int)Data__GetIntConst((int)valInt, (Data__Struct)i6);
  *(void**)i2 = (void*)i6;
  i6 = 0;
  goto l12;
l8:
  if (!((i6>=8 && i6<=9))) goto l9;
  i6 = (int)*SymbolFile__Read_r;
  i2 = *(int*)(i6-4);
  i2 = (int)((_Type)i2)->tbprocs[16];
  ((_TBP_BinaryRider__ReaderDesc_ReadLReal)i2)((BinaryRider__Reader)i6, (double *)(int)&valReal);
  i2 = (int)*(void**)i4;
  i2 += 20;
  i6 = *(signed char*)i2;
  i2 = (int)_ashl(i6, 2, (unsigned int));
  i2 = (int)Data__struct + i2;
  i2 = (int)*(void**)i2;
  i6 = i7 + 52;
  i2 = (int)Data__GetRealConst((double)valReal, (Data__Struct)i2);
  *(void**)i6 = (void*)i2;
  i6 = 0;
  goto l12;
l9:
  if (!((i6>=12 && i6<=15))) goto l10;
  i6 = (int)*SymbolFile__Read_r;
  i2 = *(int*)(i6-4);
  i2 = (int)((_Type)i2)->tbprocs[17];
  ((_TBP_BinaryRider__ReaderDesc_ReadSet)i2)((BinaryRider__Reader)i6, (unsigned int *)(int)&valSet);
  i2 = (int)*(void**)i4;
  i2 += 20;
  i6 = *(signed char*)i2;
  i2 = (int)_ashl(i6, 2, (unsigned int));
  i2 = (int)Data__struct + i2;
  i2 = (int)*(void**)i2;
  i6 = i7 + 52;
  i2 = (int)Data__GetSetConst((unsigned int)valSet, (Data__Struct)i2);
  *(void**)i6 = (void*)i2;
  i6 = 0;
  goto l12;
l10:
  if (!((i6>=18 && i6<=19))) goto l11;
  i2 = i7 + 52;
  i1 = (int)*SymbolFile__Read_r;
  i1 = (int)SymbolFile__ReadStringConst((BinaryRider__Reader)i1, (signed char)i6);
  *(void**)i2 = (void*)i1;
  i6 = 0;
  goto l12;
l11:
  if (!(i6==20)) goto l12;
  i2 = i7 + 52;
  i6 = (int)Data__constNil;
  *(void**)i2 = (void*)i6;
  i6 = 0;
l12:
  if (i6) goto l14;
  i2 = i7 + 52;
  i2 = (int)*(void**)i2;
  i1 = i2 + 48;
  *(unsigned char*)i1 = 1;
  goto l14;
l13:
  i4 = (int)*(void**)i4;
  i3 = i4 + 36;
  *(void**)i3 = (void*)i7;
  i6 = 0;
l14:
  if (i6) goto l17;
  i4 = i5 == 6;
  if (i4) goto l15;
  i5 = i5 != 7;
  if (i5) goto l17;
l15:
  SymbolTable__MakeFormalParsLocal((Data__Object)i7);
  goto l17;
l16:
  i7 = (int)SymbolTable__NewObject((const unsigned char*)(int)_c10, 4, (signed char)9, (int)-1);
  i0 = (int)Data__struct + 84;
  i2 = i7 + 64;
  i1 = i7 + 24;
  i0 = (int)*(void**)i0;
  *(void**)i1 = (void*)i0;
  i1 = *(unsigned int*)i2;
  i1 = i1 | ((unsigned int)1 << 26);
  *(unsigned int*)i2 = i1;
  i6 = 0;
l17:
  if (!(i6)) goto l18;
l18:
  return (void*)i7;
}

void SymbolFile__Read_ReadImportList(Data__Object *list, struct SymbolFile__Read_ModuleListDesc* *modList, BinaryRider__Reader *SymbolFile__Read_r, int *SymbolFile__Read_pos, unsigned char* SymbolFile__Read_moduleName, int SymbolFile__Read_moduleName_0d) {
  register int i0, i1, i2, i3, i4, i5, i6;
  int magic;
  i5 = (int)*SymbolFile__Read_r;
  i6 = (int)SymbolFile__ReadString((BinaryRider__Reader)i5);
  i0 = strcmp((const char*) i6, (const char*) (int)_c1) == 0;
  if (i0) goto l2;
  i4 = *(int*)(i5-4);
  i1 = *SymbolFile__Read_pos;
  i2 = *(int*)(i6-8);
  i4 = (int)((_Type)i4)->tbprocs[13];
  ((_TBP_BinaryRider__ReaderDesc_ReadLInt)i4)((BinaryRider__Reader)i5, (int *)(int)&magic);
  i4 = (int)SymbolFile__Read((const unsigned char*)i6, i2, (int)i1);
  *list = (void*)i4;
  i3 = (int)*list;
  i4 = i3 == 0;
  if (i4) goto l1;
  i3 += 52;
  i3 = (int)*(void**)i3;
  i3 += 24;
  i3 = *(int*)i3;
  i3 = magic == i3;
  if (i3) goto l0;
  Error__ErrIns2((int)i1, (short int)302, (const unsigned char*)(int)SymbolFile__Read_moduleName, SymbolFile__Read_moduleName_0d, (const unsigned char*)i6, i2);
l0:
  {
    char *_mem, *_var;
    _mem = GC_malloc(_not_zero(8)+8);
    if (!_mem) _new_failed(_P(28124));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &SymbolFile__Read_ModuleListDesc_td.td;
    i2 = (int)_var;
  }
  *modList = (void*)i2;
  i2 = (int)*modList;
  *(void**)i2 = (void*)0;
  i2 = (int)*modList;
  i6 = i2 + 4;
  i3 = (int)*list;
  *(void**)i6 = (void*)i3;
  i3 = (int)*modList;
  i4 = (int)*list;
  i0 = i4 + 36;
  i2 = (int)*(void**)i3;
  i6 = (int)*(void**)i0;
  SymbolFile__Read_ReadImportList((Data__Object *)i0, (struct SymbolFile__Read_ModuleListDesc* *)i3, (BinaryRider__Reader *)&*SymbolFile__Read_r, &*SymbolFile__Read_pos, SymbolFile__Read_moduleName, SymbolFile__Read_moduleName_0d);
  goto l5;
l1:
  SymbolFile__Read_ReadImportList((Data__Object *)(int)(int)list, (struct SymbolFile__Read_ModuleListDesc* *)(int)(int)modList, (BinaryRider__Reader *)&*SymbolFile__Read_r, &*SymbolFile__Read_pos, SymbolFile__Read_moduleName, SymbolFile__Read_moduleName_0d);
  goto l5;
l2:
l3:
  i2 = (int)SymbolFile__ReadString((BinaryRider__Reader)i5);
  i2 = strcmp((const char*) i2, (const char*) (int)_c1) == 0;
  if (i2) goto l4;
  i1 = *(int*)(i5-4);
  i1 = (int)((_Type)i1)->tbprocs[13];
  magic = (int)i0;
  magic = (int)i0;
  ((_TBP_BinaryRider__ReaderDesc_ReadLInt)i1)((BinaryRider__Reader)i5, (int *)(int)&magic);
  i0 = magic;
l4:
  if (!(i2)) goto l3;
  *list = (void*)0;
l5:
  ;
}

void SymbolFile__Read_StructAlloc(Data__Struct t) {
  register int i0, i1, i2;
  i0 = (int)t == 0;
  if (i0) goto l2;
  i0 = (int)t + 20;
  i1 = *(signed char*)i0;
  i2 = i1 == 21;
  if (i2) goto l2;
  i2 = (int)t + 48;
  i2 = *(int*)i2;
  i2 = i2 != (-2147483647-1);
  if (i2) goto l2;
  i1 = i1 == 27;
  if (i1) goto l1;
  i1 = (int)t + 24;
  i1 = (int)*(void**)i1;
  SymbolFile__Read_StructAlloc((Data__Struct)i1);
  i0 = *(signed char*)i0;
  i0 = i0 != 31;
  if (i0) goto l1;
  i1 = (int)t + 28;
  i1 = (int)*(void**)i1;
  i0 = i1 == 0;
  if (i0) goto l1;
l0:
  i0 = i1 + 24;
  i0 = (int)*(void**)i0;
  SymbolFile__Read_StructAlloc((Data__Struct)i0);
  i0 = i1 + 36;
  i1 = (int)*(void**)i0;
  i0 = i1 != 0;
  if (i0) goto l0;
l1:
  StdTypes__StructAlloc((Data__Struct)(int)t);
l2:
  ;
}

Data__Object SymbolFile__Read(const unsigned char* moduleName__ref, int moduleName_0d, int pos) {
  register int i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14;
  Files__File f;
  int fileFormat;
  Parameter__Filename fileName;
  int fileVersion;
  Data__Object mod;
  struct SymbolFile__Read_ModuleListDesc* modList;
  unsigned char msg[256];
  int objMode;
  BinaryRider__Reader r;
  Msg__Msg res;
  unsigned char symId[16];
  unsigned char* moduleName;
  char* _old_top_vs = _top_vs;
  _push_value(int, moduleName, moduleName__ref, moduleName_0d);
  i0 = pos;
  i12 = (int)SymbolFile__FindImportedModule((const unsigned char*)(int)moduleName, moduleName_0d);
  i1 = i12 == 0;
  if (i1) goto l0;
  i13 = i0;
  goto l22;
l0:
  i11 = ParamPaths__FindPathExt((const unsigned char*)(int)moduleName, moduleName_0d, (const unsigned char*)(int)_c2, 4, (unsigned char)0, (unsigned char*)(int)fileName, 256);
  if (i11) goto l1;
  goto l2;
l1:
  i1 = (int)Files__Old((const unsigned char*)(int)fileName, 256, (unsigned int)0x1U, (Msg__Msg *)(int)&res);
l2:
  if (!(i11)) goto l21;
  i11 = i1 == 0;
  if (i11) goto l21;
  i2 = (int)BinaryRider__ConnectReader((Channel__Channel)i1);
  i4 = *(int*)(i2-4);
  (void)memcpy((void*) (int)symId, (const void*) (int)_c3, 5);
  i13 = (int)((_Type)i4)->tbprocs[4];
  ((_TBP_BinaryRider__ReaderDesc_ReadBytes)i13)((BinaryRider__Reader)i2, (unsigned char*)(int)symId, 16, (int)0, (int)4);
  i13 = strcmp((const char*) (int)symId, (const char*) (int)SymbolFile__symbolFileId) != 0;
  i3 = *(int*)(i1-4);
  if (i13) goto l18;
  i12 = (int)SymbolTable__NewModule((const unsigned char*)(int)moduleName, moduleName_0d, (int)i0);
  i5 = i12 + 52;
  i5 = (int)*(void**)i5;
  i5 += 24;
  i4 = (int)((_Type)i4)->tbprocs[13];
  i6 = *(int*)i5;
  ((_TBP_BinaryRider__ReaderDesc_ReadLInt)i4)((BinaryRider__Reader)i2, (int *)i5);
  i4 = i12 + 20;
  i5 = (int)SymbolFile__ReadString((BinaryRider__Reader)i2);
  *(void**)i4 = (void*)i5;
  i4 = (int)*(void**)i4;
  i5 = strcmp((const char*) (int)moduleName, (const char*) i4) == 0;
  if (i5) goto l3;
  i5 = *(int*)(i4-8);
  Error__ErrIns2((int)i0, (short int)-401, (const unsigned char*)(int)moduleName, moduleName_0d, (const unsigned char*)i4, i5);
l3:
  i9 = i12 + 48;
  i5 = (int)SymbolTable__importedMods;
  i4 = SymbolFile__CreateModuleId();
  i8 = i12 + 50;
  *(short int*)i9 = i4;
  i4 = i12 + 32;
  i6 = i12 + 36;
  *(short int*)i8 = 0;
  *(void**)i6 = (void*)i5;
  SymbolTable__importedMods = (void*)i12;
  i5 = (int)*(void**)i4;
  r = (void*)i2;
  pos = (int)i0;
  modList = (void*)0;
  pos = (int)i0;
  r = (void*)i2;
  modList = (void*)0;
  SymbolFile__Read_ReadImportList((Data__Object *)i4, (struct SymbolFile__Read_ModuleListDesc* *)(int)&modList, (BinaryRider__Reader *)&r, &pos, moduleName, moduleName_0d);
  i14 = (int)r;
  i4 = *(int*)(i14-4);
  i10 = (int)((_Type)i4)->tbprocs[14];
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i10)((BinaryRider__Reader)i14, (int *)(int)&fileFormat);
  i4 = fileFormat != 1;
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i10)((BinaryRider__Reader)i14, (int *)(int)&fileVersion);
  if (i4) goto l14;
  i6 = fileVersion != 4;
  if (i6) goto l12;
  i4 = i12 + 64;
  i5 = i12 + 68;
  i6 = *(unsigned int*)i4;
  SymbolFile__ReadFlags((BinaryRider__Reader)i14, (unsigned int *)i4);
  i6 = *(unsigned int*)i5;
  SymbolFile__ReadFlags((BinaryRider__Reader)i14, (unsigned int *)i5);
  i4 = *(unsigned int*)i4;
  i4 = (i4 & ((unsigned int)1 << 3)) != 0;
  if (!(i4)) goto l4;
  SystemFlags__ReadObjectInfo((BinaryRider__Reader)i14, (Data__Object)i12);
l4:
  i4 = (int)*(void**)i14;
  i4 = i4 == 0;
  if (i4) goto l5;
  Error__ErrIns((int)pos, (short int)305, (const unsigned char*)(int)fileName, 256);
l5:
  i4 = i12 + 40;
  i5 = (int)SymbolTable__currScope;
  *(void**)i4 = (void*)i5;
  SymbolFile__structLen = 0;
  i8 = *(short int*)i8;
  i9 = *(short int*)i9;
  SymbolTable__OpenScope((Data__Object)i12, (short int)i9, (short int)i8);
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i10)((BinaryRider__Reader)i14, (int *)(int)&objMode);
  i8 = (int)*(void**)i14;
  i8 = i8 != 0;
  if (i8) goto l10;
  i8 = objMode == 0;
  if (i8) goto l10;
  i6 = objMode;
  i13 = i12;
  i10 = (int)modList;
  i7 = i14;
  i9 = 0;
l6:
  i5 = i9 == 0;
  if (i5) goto l7;
  r = (void*)i7;
  mod = (void*)i13;
  modList = (void*)i10;
  mod = (void*)i13;
  modList = (void*)i10;
  r = (void*)i7;
  i5 = (int)SymbolFile__Read_ReadObject((int)i6, (BinaryRider__Reader *)&r, fileName, (Data__Object *)&mod, (struct SymbolFile__Read_ModuleListDesc* *)&modList);
  i4 = i9 + 36;
  *(void**)i4 = (void*)i5;
  i4 = (int)*(void**)i4;
  i9 = i4;
  i7 = (int)r;
  i10 = (int)modList;
  i13 = (int)mod;
  goto l8;
l7:
  r = (void*)i7;
  mod = (void*)i13;
  modList = (void*)i10;
  mod = (void*)i13;
  modList = (void*)i10;
  r = (void*)i7;
  i9 = (int)SymbolFile__Read_ReadObject((int)i6, (BinaryRider__Reader *)&r, fileName, (Data__Object *)&mod, (struct SymbolFile__Read_ModuleListDesc* *)&modList);
  i10 = (int)mod + 44;
  *(void**)i10 = (void*)i9;
  i7 = (int)r;
  i10 = (int)modList;
  i13 = (int)mod;
l8:
  i5 = i9 + 32;
  *(void**)i5 = (void*)0;
  i5 = i9 + 36;
  *(void**)i5 = (void*)0;
  i5 = i9 + 40;
  *(void**)i5 = (void*)i13;
  i5 = i13 + 48;
  i4 = *(short int*)i5;
  i5 = i9 + 48;
  *(short int*)i5 = i4;
  i5 = i13 + 50;
  i4 = *(short int*)i5;
  i5 = i9 + 50;
  *(short int*)i5 = i4;
  i5 = (int)*(void**)i7;
  i5 = i5 == 0;
  if (i5) goto l9;
  Error__ErrIns((int)pos, (short int)305, (const unsigned char*)(int)fileName, 256);
l9:
  i5 = *(int*)(i7-4);
  i5 = (int)((_Type)i5)->tbprocs[14];
  objMode = (int)i6;
  objMode = (int)i6;
  ((_TBP_BinaryRider__ReaderDesc_ReadNum)i5)((BinaryRider__Reader)i7, (int *)(int)&objMode);
  i6 = (int)*(void**)i7;
  i6 = i6 != 0;
  if (i6) goto l11;
  i6 = objMode == 0;
  if (i6) goto l11;
  i6 = objMode;
  goto l6;
l10:
  i7 = i14;
  i13 = i12;
l11:
  i8 = (int)((_Type)i3)->tbprocs[0];
  i9 = *(int*)(i7-4);
  i8 = ((_TBP_PosixFileDescr__ChannelDesc_Length)i8)((PosixFileDescr__Channel)i1);
  i9 = (int)((_Type)i9)->tbprocs[0];
  i9 = ((_TBP_BinaryRider__ReaderDesc_Pos)i9)((BinaryRider__Reader)i7);
  i8 -= i9;
  i9 = i8 == 0;
  if (i9) goto l13;
  IntStr__IntToStr((int)i8, (unsigned char*)(int)symId, 16);
  Error__ErrIns2((int)pos, (short int)-402, (const unsigned char*)(int)symId, 16, (const unsigned char*)(int)fileName, 256);
  goto l13;
l12:
  IntStr__IntToStr((int)fileVersion, (unsigned char*)(int)symId, 16);
  Error__ErrIns((int)pos, (short int)308, (const unsigned char*)(int)symId, 16);
  i13 = i12;
  i7 = i14;
l13:
  i14 = i7;
  i12 = i13;
  goto l15;
l14:
  IntStr__IntToStr((int)fileFormat, (unsigned char*)(int)symId, 16);
  Error__ErrIns((int)pos, (short int)308, (const unsigned char*)(int)symId, 16);
l15:
  SymbolTable__CloseScope((unsigned char)0);
  SymbolTable__BalanceTree((Data__Object)i12);
  i4 = SymbolFile__structLen;
  i8 = i4 - 1;
  i4 = i8 < 0;
  if (i4) goto l17;
  i4 = 0;
l16:
  i6 = (int)SymbolFile__structArray;
  i5 = (int)_ashl(i4, 2, (unsigned int));
  i5 = i6 + i5;
  i5 = (int)*(void**)i5;
  SymbolFile__Read_StructAlloc((Data__Struct)i5);
  i5 = (int)SymbolFile__structArray;
  i6 = (int)_ashl(i4, 2, (unsigned int));
  i7 = i5 + i6;
  i6 = i4 + 1;
  i9 = i6 > i8;
  *(void**)i7 = (void*)0;
  if (i9) goto l17;
  i4 = i6;
  goto l16;
l17:
  i2 = i14;
  i13 = pos;
  goto l19;
l18:
  Error__ErrIns((int)i0, (short int)304, (const unsigned char*)(int)fileName, 256);
  i13 = i0;
  i12 = 0;
l19:
  i10 = (int)*(void**)i2;
  i9 = i10 == 0;
  if (i9) goto l20;
  i9 = *(int*)(i10-4);
  i9 = (int)((_Type)i9)->tbprocs[3];
  ((_TBP_Msg__MsgDesc_GetText)i9)((Msg__Msg)i10, (Msg__String)(int)msg, 256);
  Error__FileError((const unsigned char*)(int)_c11, 23, (const unsigned char*)(int)fileName, 256, (const unsigned char*)(int)msg, 256);
l20:
  i10 = (int)((_Type)i3)->tbprocs[5];
  ((_TBP_Files__FileDesc_Close)i10)((Files__File)i1);
  goto l22;
l21:
  Error__ErrIns((int)i0, (short int)303, (const unsigned char*)(int)moduleName, moduleName_0d);
  i12 = 0;
  i13 = i0;
l22:
  i0 = i12 != 0;
  if (i0) goto l23;
  i3 = 0;
  goto l24;
l23:
  {
    char *_mem, *_var;
    _mem = GC_malloc(_not_zero(76)+8);
    if (!_mem) _new_failed(_P(33456));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Data__ObjectDesc_td.td;
    i3 = (int)_var;
  }
  {
    char *_mem, *_var;
    _mem = GC_malloc(_not_zero(56)+8);
    if (!_mem) _new_failed(_P(33516));
    _var = _mem+8;
    ((_Type*)_var)[-1] = &Data__ConstDesc_td.td;
    i2 = (int)_var;
  }
  i1 = i3 + 52;
  i0 = i3 + 72;
  (void)memcpy((void*) i3, (const void*) i12, 76);
  *(int*)i0 = i13;
  i12 = (int)*(void**)i1;
  i0 = i3 + 20;
  (void)memcpy((void*) i2, (const void*) i12, 56);
  i12 = i2 + 20;
  *(void**)i1 = (void*)i2;
  i1 = (int)*(void**)i0;
  *(void**)i12 = (void*)i1;
l24:
  _top_vs = _old_top_vs;
  return (void*)i3;
}

void SymbolFile_init(void) {
  register int i0, i1;
  _mid = _register_module(&SymbolFile_md.md, &SymbolFile__Read_ModuleListDesc_td.td);
  {
    char *_mem, *_var;
    int* _dim_ptr;
    _mem = GC_malloc(_not_zero(124*4)+8);
    if (!_mem) _new_failed(_P(33698));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = 124;
    i0 = (int)_var;
  }
  SymbolFile__structArray = (void*)i0;
  i0 = (int)SymbolFile__symbolFileId + 1;
  *(unsigned char*)(int)SymbolFile__symbolFileId = 239;
  i1 = (int)SymbolFile__symbolFileId + 2;
  *(unsigned char*)i0 = 154;
  i0 = (int)SymbolFile__symbolFileId + 3;
  *(unsigned char*)i1 = 82;
  i1 = (int)SymbolFile__symbolFileId + 4;
  *(unsigned char*)i0 = 115;
  (void)memcpy((void*) (int)SymbolFile__emptyString, (const void*) (int)_c1, 1);
  *(unsigned char*)i1 = 0;
  {
    char *_mem, *_var;
    int* _dim_ptr;
    _mem = GC_malloc_atomic(_not_zero(2*1)+8);
    if (!_mem) _new_failed(_P(33939));
    _var = _mem+8;
    _dim_ptr = (void*)(_var-4);
    *(--_dim_ptr) = 2;
    i0 = (int)_var;
  }
  SymbolFile__emptyStringPtr = (void*)i0;
  i0 = (int)SymbolFile__emptyStringPtr;
  i1 = *(int*)(i0-8);
  _string_copy(i0, (int)_c1, i1);
}
