/* file generated by oo2c -- do not edit */
#ifndef _MODULE_SystemFlags_
#define _MODULE_SystemFlags_

#define SystemFlags__callConvC 0
#define SystemFlags__callConvPascal 1
#define SystemFlags__callConvFortran 2
#define SystemFlags__callConvModula2 3
extern unsigned char SystemFlags__noLibFileRead;
#include "Parameter.h"
#include "External.h"
#include "Data.h"
typedef struct SystemFlags__InfoDesc {
  Parameter__String name;
  short int callConv;
  char _6pad, _7pad;
  Parameter__String givenName;
  External__Ref link;
  External__Lib library;
} SystemFlags__InfoDesc;
typedef struct SystemFlags__InfoDesc* SystemFlags__Info;
extern void SystemFlags__CreateInfo(Data__Addressable adr);
extern void SystemFlags__ObjectModifiers(Data__Object obj, unsigned char parse);
extern void SystemFlags__StructModifiers(Data__Struct str, unsigned char parse);
#include "BinaryRider.h"
extern void SystemFlags__WriteObjectInfo(BinaryRider__Writer w, Data__Object obj);
extern void SystemFlags__ReadObjectInfo(BinaryRider__Reader r, Data__Object obj);
extern void SystemFlags__WriteStructInfo(BinaryRider__Writer w, Data__Struct struct_);
extern void SystemFlags__ReadStructInfo(BinaryRider__Reader r, Data__Struct struct_);
extern struct _TD SystemFlags__Modifier_td;
extern struct _TD SystemFlags__InfoDesc_td;
extern void SystemFlags_init(void);

#endif
