/* file generated by oo2c -- do not edit */
#include "SystemFlags.h"
#include "Error.h"
#include "Scanner.h"
#include "StdPragmas.h"
#include "StdTypes.h"
#include "Strings.h"
#include "SymbolTable.h"

/* local definitions */
typedef struct SystemFlags__Modifier {
  unsigned char name[20];
  unsigned int objId;
  signed char objFlag;
  char _25pad, _26pad, _27pad;
  unsigned int structId;
  signed char structFlag;
  char _33pad, _34pad, _35pad;
} SystemFlags__Modifier;
static SystemFlags__Modifier SystemFlags__mods[19];
static unsigned char SystemFlags__emptyString[2];
static signed char SystemFlags__mode;
static short int SystemFlags__callConv;
unsigned char SystemFlags__noLibFileRead;

/* function prototypes */
short int SystemFlags__StandardCallConv(void);
unsigned char SystemFlags__Ident(const unsigned char* str, int str_0d);
void SystemFlags__String(unsigned char* str, int str_0d);
Parameter__String SystemFlags__HeapString(void);
void SystemFlags__CheckIdent(const unsigned char* str__ref, int str_0d);
void SystemFlags__File(Parameter__String *file, Parameter__String *suffix);
void SystemFlags__SetFlag_Set(unsigned int *set, signed char index);
void SystemFlags__SetFlag(Data__Addressable adr);
short int SystemFlags__CallConv(void);
void SystemFlags__ModuleModifiers_LinkSection_AddOptionClause(External__NameList *prefix, External__NameList *suffix, Parameter__String *SystemFlags__ModuleModifiers_LinkSection_str);
void SystemFlags__ModuleModifiers_LinkSection(Data__Object *SystemFlags__ModuleModifiers_mod, External__Lib *SystemFlags__ModuleModifiers_lib);
void SystemFlags__ModuleModifiers_SetFlag(short int id, Data__Object *SystemFlags__ModuleModifiers_mod);
void SystemFlags__ModuleModifiers_ReadLibrary(External__Lib *lib);
void SystemFlags__ModuleModifiers_NormalModule(Data__Object *SystemFlags__ModuleModifiers_mod, External__Ref *SystemFlags__ModuleModifiers_ref);
void SystemFlags__ModuleModifiers(Data__Object mod, unsigned char parse);
unsigned char SystemFlags__ObjectModifiers_ValidForObject(Data__Object obj, unsigned int ids);
unsigned char SystemFlags__StructModifiers_HasRestParam(Data__Struct str);

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const void* list[7];
} _p0 = {7, NULL, {
  (const void*)&SystemFlags__CreateInfo,
  (const void*)&SystemFlags__ObjectModifiers,
  (const void*)&SystemFlags__ReadObjectInfo,
  (const void*)&SystemFlags__ReadStructInfo,
  (const void*)&SystemFlags__StructModifiers,
  (const void*)&SystemFlags__WriteObjectInfo,
  (const void*)&SystemFlags__WriteStructInfo,
}};
static const struct {
  int length;
  void* pad;
  const void* list[1];
} _p1 = {1, NULL, {
  (const void*)&SystemFlags__noLibFileRead,
}};
static const struct {
  int length;
  void* pad;
  const char name[12];
} _n0 = {12, NULL, {"SystemFlags"}};
static struct _MD SystemFlags_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL,
    _p0.list,
    _p1.list,
    -2131011669
  }
};

static const struct {
  int length;
  void* pad;
  const char name[9];
} _n1 = {9, NULL, {"Modifier"}};
static const struct {
  int length;
  void* pad;
  _Type btypes[1];
} SystemFlags__Modifier_tdb = {
  1, 
  NULL, 
  {
    &SystemFlags__Modifier_td.td
  }
};
static const struct {
  int length;
  void* pad;
  const void* tbprocs[1];
} _tb0 = {0, NULL, {
  NULL
}};
struct _TD SystemFlags__Modifier_td = {
  NULL,
  &Types__TypeDesc_td.td,
  {
    SystemFlags__Modifier_tdb.btypes,
    _tb0.tbprocs,
    (const unsigned char*)_n1.name,
    &SystemFlags_md.md,
    0, 
    '0', '1',
    sizeof(SystemFlags__Modifier),
    NULL
  }
};

static const struct {
  int length;
  void* pad;
  const char name[9];
} _n2 = {9, NULL, {"InfoDesc"}};
static const struct {
  int length;
  void* pad;
  _Type btypes[2];
} SystemFlags__InfoDesc_tdb = {
  2, 
  NULL, 
  {
    &Data__InfoDesc_td.td, 
    &SystemFlags__InfoDesc_td.td
  }
};
static const struct {
  int length;
  void* pad;
  const void* tbprocs[1];
} _tb1 = {0, NULL, {
  NULL
}};
struct _TD SystemFlags__InfoDesc_td = {
  NULL,
  &Types__TypeDesc_td.td,
  {
    SystemFlags__InfoDesc_tdb.btypes,
    _tb1.tbprocs,
    (const unsigned char*)_n2.name,
    &SystemFlags_md.md,
    1, 
    '0', '1',
    sizeof(SystemFlags__InfoDesc),
    &SystemFlags__Modifier_td.td
  }
};

/* local strings */
static const unsigned char _c35[] = "VOLATILE";
static const unsigned char _c34[] = "VTABLE";
static const unsigned char _c33[] = "NO_COPY";
static const unsigned char _c32[] = "ABSTRACT";
static const unsigned char _c31[] = "ALIGN8";
static const unsigned char _c30[] = "ALIGN4";
static const unsigned char _c29[] = "ALIGN2";
static const unsigned char _c28[] = "ALIGN1";
static const unsigned char _c27[] = "CSTRING";
static const unsigned char _c26[] = "UNION";
static const unsigned char _c25[] = "HAS_BODY";
static const unsigned char _c24[] = "NIL_COMPAT";
static const unsigned char _c23[] = "DISABLE_NEW";
static const unsigned char _c22[] = "STATIC_POINTER";
static const unsigned char _c21[] = "NO_TYPE_TAG";
static const unsigned char _c20[] = "NO_LENGTH_TAG";
static const unsigned char _c19[] = "NO_LENGTH_INFO";
static const unsigned char _c18[] = "NO_DESCRIPTOR";
static const unsigned char _c17[] = "NOT_EXTENSIBLE";
static const unsigned char _c16[] = "_vtbl";
static const unsigned char _c15[] = "PROC_ID";
static const unsigned char _c14[] = "LINK";
static const unsigned char _c13[] = "INIT_FCT";
static const unsigned char _c12[] = "CODE_FILE";
static const unsigned char _c11[] = "FOREIGN";
static const unsigned char _c10[] = "INTERFACE";
static const unsigned char _c9[] = "LIBRARY";
static const unsigned char _c8[] = "OOC_EXTENSIONS";
static const unsigned char _c7[] = "LIB";
static const unsigned char _c6[] = "OBJ";
static const unsigned char _c5[] = "FILE";
static const unsigned char _c4[] = "ADD_OPTION";
static const unsigned char _c3[] = "Pascal";
static const unsigned char _c2[] = "Win32";
static const unsigned char _c1[] = "C";
static const unsigned char _c0[] = "";

