/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "Time.d"

static _ModId _mid;

void Time__InitTimeStamp(Time__TimeStamp *t, _Type t__tag, int days, int msecs) {
  register int i0, i1, i2;
  i2 = (int)t + 4;
  _div(i0, msecs, 86400000, int);
  _mod(i1, msecs, 86400000, int);
  *(int*)i2 = i1;
  i0 = days + i0;
  *(int*)(int)t = i0;
}

void Time__GetTime(Time__TimeStamp *t, _Type t__tag) {
  register int i0, i1, i2;
  int sec;
  int usec;
  i0 = SysClock__GetTimeOfDay((int *)(int)&sec, (int *)(int)&usec);
  _mod(i0, sec, 86400, int);
  _div(i1, sec, 86400, int);
  i0 *= 1000;
  i2 = i1 + 40587;
  _div(i1, usec, 1000, int);
  i0 += i1;
  *(int*)(int)t = i2;
  i1 = (int)t + 4;
  *(int*)i1 = i0;
}

void Time__TimeStamp_Add(Time__TimeStamp *a, _Type a__tag, const Time__Interval *b) {
  register int i0, i1, i2;
  i0 = (int)b + 4;
  i1 = (int)a + 4;
  i0 = *(int*)i0;
  i2 = *(int*)i1;
  i0 = i2 + i0;
  *(int*)i1 = i0;
  i2 = *(int*)(int)b;
  i0 = *(int*)(int)a;
  i0 += i2;
  *(int*)(int)a = i0;
  i2 = *(int*)i1;
  i0 = i2 < 86400000;
  if (i0) goto l0;
  i2 -= 86400000;
  *(int*)i1 = i2;
  i1 = *(int*)(int)a;
  i1++;
  *(int*)(int)a = i1;
l0:
  ;
}

void Time__TimeStamp_Sub(Time__TimeStamp *a, _Type a__tag, const Time__Interval *b) {
  register int i0, i1, i2;
  i0 = (int)b + 4;
  i1 = (int)a + 4;
  i0 = *(int*)i0;
  i2 = *(int*)i1;
  i0 = i2 - i0;
  *(int*)i1 = i0;
  i2 = *(int*)(int)b;
  i0 = *(int*)(int)a;
  i0 -= i2;
  *(int*)(int)a = i0;
  i2 = *(int*)i1;
  i0 = i2 >= 0;
  if (i0) goto l0;
  i2 += 86400000;
  *(int*)i1 = i2;
  i1 = *(int*)(int)a;
  i1--;
  *(int*)(int)a = i1;
l0:
  ;
}

void Time__TimeStamp_Delta(Time__TimeStamp *a, _Type a__tag, const Time__TimeStamp *b, Time__Interval *c, _Type c__tag) {
  register int i0, i1, i2;
  i1 = (int)b + 4;
  i0 = (int)a + 4;
  i2 = *(int*)i1;
  i1 = (int)c + 4;
  i0 = *(int*)i0;
  i2 = i0 - i2;
  i0 = *(int*)(int)b;
  *(int*)i1 = i2;
  i2 = *(int*)(int)a;
  i0 = i2 - i0;
  *(int*)(int)c = i0;
  i2 = *(int*)i1;
  i0 = i2 >= 0;
  if (i0) goto l0;
  i2 += 86400000;
  *(int*)i1 = i2;
  i1 = *(int*)(int)c;
  i1--;
  *(int*)(int)c = i1;
l0:
  ;
}

signed char Time__TimeStamp_Cmp(Time__TimeStamp *a, _Type a__tag, const Time__TimeStamp *b) {
  register int i0, i1, i2;
  i0 = *(int*)(int)b;
  i1 = *(int*)(int)a;
  i2 = i1 > i0;
  if (i2) goto l3;
  i0 = i1 == i0;
  if (!(i0)) goto l0;
  i1 = (int)b + 4;
  i2 = (int)a + 4;
  i1 = *(int*)i1;
  i2 = *(int*)i2;
  i1 = i2 > i1;
  if (i1) goto l3;
l0:
  if (!(i0)) goto l1;
  i2 = (int)b + 4;
  i0 = (int)a + 4;
  i2 = *(int*)i2;
  i0 = *(int*)i0;
  i2 = i0 == i2;
  if (i2) goto l2;
l1:
  i2 = -1;
  goto l4;
l2:
  i2 = 0;
  goto l4;
l3:
  i2 = 1;
l4:
  return (signed char)i2;
}

void Time__InitInterval(Time__Interval *int_, _Type int___tag, int days, int msecs) {
  register int i0, i1;
  _div(i0, msecs, 86400000, int);
  i0 = days + i0;
  *(int*)(int)int_ = i0;
  i1 = (int)int_ + 4;
  _mod(i0, msecs, 86400000, int);
  *(int*)i1 = i0;
}

void Time__Interval_Add(Time__Interval *a, _Type a__tag, const Time__Interval *b__ref) {
  register int i0, i1, i2;
  Time__Interval b;
  (void)memcpy(&b, b__ref, 8);
  i0 = (int)&b + 4;
  i1 = (int)a + 4;
  i0 = *(int*)i0;
  i2 = *(int*)i1;
  i0 = i2 + i0;
  *(int*)i1 = i0;
  i2 = *(int*)(int)&b;
  i0 = *(int*)(int)a;
  i0 += i2;
  *(int*)(int)a = i0;
  i2 = *(int*)i1;
  i0 = i2 < 86400000;
  if (i0) goto l0;
  i2 -= 86400000;
  *(int*)i1 = i2;
  i1 = *(int*)(int)a;
  i1++;
  *(int*)(int)a = i1;
l0:
  ;
}

void Time__Interval_Sub(Time__Interval *a, _Type a__tag, const Time__Interval *b__ref) {
  register int i0, i1, i2;
  Time__Interval b;
  (void)memcpy(&b, b__ref, 8);
  i0 = (int)&b + 4;
  i1 = (int)a + 4;
  i0 = *(int*)i0;
  i2 = *(int*)i1;
  i0 = i2 - i0;
  *(int*)i1 = i0;
  i2 = *(int*)(int)&b;
  i0 = *(int*)(int)a;
  i0 -= i2;
  *(int*)(int)a = i0;
  i2 = *(int*)i1;
  i0 = i2 >= 0;
  if (i0) goto l0;
  i2 += 86400000;
  *(int*)i1 = i2;
  i1 = *(int*)(int)a;
  i1--;
  *(int*)(int)a = i1;
l0:
  ;
}

signed char Time__Interval_Cmp(Time__Interval *a, _Type a__tag, const Time__Interval *b) {
  register int i0, i1, i2;
  i0 = *(int*)(int)b;
  i1 = *(int*)(int)a;
  i2 = i1 > i0;
  if (i2) goto l3;
  i0 = i1 == i0;
  if (!(i0)) goto l0;
  i1 = (int)b + 4;
  i2 = (int)a + 4;
  i1 = *(int*)i1;
  i2 = *(int*)i2;
  i1 = i2 > i1;
  if (i1) goto l3;
l0:
  if (!(i0)) goto l1;
  i2 = (int)b + 4;
  i0 = (int)a + 4;
  i2 = *(int*)i2;
  i0 = *(int*)i0;
  i2 = i0 == i2;
  if (i2) goto l2;
l1:
  i2 = -1;
  goto l4;
l2:
  i2 = 0;
  goto l4;
l3:
  i2 = 1;
l4:
  return (signed char)i2;
}

void Time__Interval_Scale(Time__Interval *a, _Type a__tag, double b) {
  register int i0, i1;
  register float f0, f1;
  register double d0, d1;
  i0 = (int)a + 4;
  i1 = *(int*)i0;
  f0 = i1;
  i1 = *(int*)(int)a;
  f1 = f0 / 8.64000000E+7F;
  f0 = i1;
  f0 += f1;
  d0 = f0;
  d0 = b * d0;
  _entier(i1, d0);
  *(int*)(int)a = i1;
  i1 = *(int*)(int)a;
  d1 = i1;
  d0 -= d1;
  d0 *= 8.6400000000000000E+7;
  d0 += 5.0000000000000000E-1;
  _entier(i1, d0);
  *(int*)i0 = i1;
}

double Time__Interval_Fraction(Time__Interval *a, _Type a__tag, const Time__Interval *b) {
  register int i0, i1, i2;
  register float f0, f1, f2, f3;
  register double d0;
  i0 = (int)b + 4;
  i1 = (int)a + 4;
  i0 = *(int*)i0;
  i1 = *(int*)i1;
  i2 = *(int*)(int)b;
  f1 = i0;
  f2 = i1;
  i0 = *(int*)(int)a;
  f0 = i2;
  f1 /= 8.64000000E+7F;
  f3 = f2 / 8.64000000E+7F;
  f2 = i0;
  f0 += f1;
  f1 = f2 + f3;
  f0 = f1 / f0;
  d0 = f0;
  return (double)d0;
}

void Time_init(void) {
  _mid = _register_module(&Time_md.md, &Time__Interval_td.td);
}
