/* file generated by oo2c -- do not edit */
#include "WriteGSAvC.h"
#include "Allocate.h"
#include "Classify.h"
#include "ControlFlow.h"
#include "IntStr.h"
#include "Opcode.h"
#include "Out.h"
#include "Strings.h"
#include "WriteSymbols.h"

/* local definitions */
ParamOptions__BooleanOption WriteGSAvC__writeGSA;
static ParamOptions__BooleanOption WriteGSAvC__writeLoc;
ParamOptions__BooleanOption WriteGSAvC__writeQualNames;
static Data__Object WriteGSAvC__mod;

/* function prototypes */
void WriteGSAvC__Id(int off, int marker, int pos);
void WriteGSAvC__Name(Data__Addressable a, unsigned char* str, int str_0d);
void WriteGSAvC__Argument(Data__Info i, unsigned char* str, int str_0d);
void WriteGSAvC__Location(Data__Location loc, unsigned char* str, int str_0d);
void WriteGSAvC__Subclass(short int scode, unsigned char* str, int str_0d);
void WriteGSAvC__Opcode_Operator(short int opcode, unsigned char* str, int str_0d);
void WriteGSAvC__Opcode_AccessSubclass(short int opcode, unsigned char* str, int str_0d);
void WriteGSAvC__WrLocation(Data__Location loc);
void WriteGSAvC__WrSubclass(short int opc);
void WriteGSAvC__WrOperands(Data__Instruction instr);
void WriteGSAvC__WrResults(Data__Instruction instr);
void WriteGSAvC__WrFlags(Data__Instruction instr);
void WriteGSAvC__WrInstr(Data__Instruction instr, short int off);
void WriteGSAvC__SetMarkers_MarkInstr(Data__Instruction instr, int *WriteGSAvC__SetMarkers_counter);
void WriteGSAvC__SetMarkers(Data__Region greg);

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const char name[11];
} _n0 = {11, NULL, {"WriteGSAvC"}};
static struct _MD WriteGSAvC_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL
  }
};

/* local strings */
static const unsigned char _c153[] = "writeQualNamesC:=TRUE";
static const unsigned char _c152[] = "--cgsa-qnames";
static const unsigned char _c151[] = "writeQualNamesC";
static const unsigned char _c150[] = "writeLocC:=TRUE";
static const unsigned char _c149[] = "--cgsa-loc";
static const unsigned char _c148[] = "writeLocC";
static const unsigned char _c147[] = "writeGSAC:=TRUE";
static const unsigned char _c146[] = "--cgsa";
static const unsigned char _c145[] = "writeGSAC";
static const unsigned char _c144[] = "module body: ";
static const unsigned char _c143[] = "procedure ";
static const unsigned char _c142[] = " }";
static const unsigned char _c141[] = " longreal";
static const unsigned char _c140[] = " real";
static const unsigned char _c139[] = " huge";
static const unsigned char _c138[] = " int";
static const unsigned char _c137[] = " void";
static const unsigned char _c136[] = " noOutput";
static const unsigned char _c135[] = " poisonHeap";
static const unsigned char _c134[] = " guardFor";
static const unsigned char _c133[] = " uniqueResult";
static const unsigned char _c132[] = " stackCheck";
static const unsigned char _c131[] = " initialize";
static const unsigned char _c130[] = " checkDiv";
static const unsigned char _c129[] = " checkNil";
static const unsigned char _c128[] = " checkOverflow";
static const unsigned char _c127[] = " isDisabled";
static const unsigned char _c126[] = " notDead";
static const unsigned char _c125[] = "  {";
static const unsigned char _c124[] = " := ";
static const unsigned char _c123[] = "res.";
static const unsigned char _c122[] = "..";
static const unsigned char _c121[] = "<type ";
static const unsigned char _c120[] = "[XXX]";
static const unsigned char _c119[] = ", ";
static const unsigned char _c118[] = " ";
static const unsigned char _c117[] = "end-of-greg";
static const unsigned char _c116[] = "assign-gates";
static const unsigned char _c115[] = "branch-on-true";
static const unsigned char _c114[] = "branch-on-false";
static const unsigned char _c113[] = "jump";
static const unsigned char _c112[] = "trap-with";
static const unsigned char _c111[] = "trap-halt";
static const unsigned char _c110[] = "trap-assert";
static const unsigned char _c109[] = "trap-case";
static const unsigned char _c108[] = "trap-return";
static const unsigned char _c107[] = "merge-case:";
static const unsigned char _c106[] = "merge-loop:";
static const unsigned char _c105[] = "merge-cond:";
static const unsigned char _c104[] = "merge-if:";
static const unsigned char _c103[] = "if-member:";
static const unsigned char _c102[] = "greg:";
static const unsigned char _c101[] = "if-false:";
static const unsigned char _c100[] = "if-true:";
static const unsigned char _c99[] = "update-";
static const unsigned char _c98[] = "access-";
static const unsigned char _c97[] = "zero";
static const unsigned char _c96[] = "delete-store";
static const unsigned char _c95[] = "create-store";
static const unsigned char _c94[] = "move";
static const unsigned char _c93[] = "new-block";
static const unsigned char _c92[] = "new";
static const unsigned char _c91[] = "struct-copy";
static const unsigned char _c90[] = "string-copy";
static const unsigned char _c89[] = "type-cast";
static const unsigned char _c88[] = "bit";
static const unsigned char _c87[] = "type-assert";
static const unsigned char _c86[] = "type-guard";
static const unsigned char _c85[] = "type-test";
static const unsigned char _c84[] = "tb-proc-adr";
static const unsigned char _c83[] = "type-tag";
static const unsigned char _c82[] = "array-length";
static const unsigned char _c81[] = "call";
static const unsigned char _c80[] = "bound-range";
static const unsigned char _c79[] = "bound-index";
static const unsigned char _c78[] = "gate";
static const unsigned char _c77[] = "copy";
static const unsigned char _c76[] = "adr";
static const unsigned char _c75[] = "exit";
static const unsigned char _c74[] = "enter";
static const unsigned char _c73[] = "\077opc";
static const unsigned char _c72[] = "mem";
static const unsigned char _c71[] = "var-param";
static const unsigned char _c70[] = "nonlocal";
static const unsigned char _c69[] = "heap";
static const unsigned char _c68[] = "element";
static const unsigned char _c67[] = "field";
static const unsigned char _c66[] = "geq";
static const unsigned char _c65[] = "gtr";
static const unsigned char _c64[] = "leq";
static const unsigned char _c63[] = "lss";
static const unsigned char _c62[] = "neq";
static const unsigned char _c61[] = "eql";
static const unsigned char _c60[] = "rot";
static const unsigned char _c59[] = "lsh";
static const unsigned char _c58[] = "odd";
static const unsigned char _c57[] = "cap";
static const unsigned char _c56[] = "ash";
static const unsigned char _c55[] = "abs";
static const unsigned char _c54[] = "not";
static const unsigned char _c53[] = "bittest";
static const unsigned char _c52[] = "bitrange";
static const unsigned char _c51[] = "bitclear";
static const unsigned char _c50[] = "bitset";
static const unsigned char _c49[] = "compl";
static const unsigned char _c48[] = "diff";
static const unsigned char _c47[] = "union";
static const unsigned char _c46[] = "symdiff";
static const unsigned char _c45[] = "inter";
static const unsigned char _c44[] = "neg";
static const unsigned char _c43[] = "mod";
static const unsigned char _c42[] = "divi";
static const unsigned char _c41[] = "divr";
static const unsigned char _c40[] = "mult";
static const unsigned char _c39[] = "sub";
static const unsigned char _c38[] = "add";
static const unsigned char _c37[] = "conv";
static const unsigned char _c36[] = "trap";
static const unsigned char _c35[] = "merge";
static const unsigned char _c34[] = "guard";
static const unsigned char _c33[] = "update";
static const unsigned char _c32[] = "access";
static const unsigned char _c31[] = "special";
static const unsigned char _c30[] = "lstr";
static const unsigned char _c29[] = "str";
static const unsigned char _c28[] = "d";
static const unsigned char _c27[] = "r";
static const unsigned char _c26[] = "llu";
static const unsigned char _c25[] = "ll";
static const unsigned char _c24[] = "lu";
static const unsigned char _c23[] = "l";
static const unsigned char _c22[] = "iu";
static const unsigned char _c21[] = "i";
static const unsigned char _c20[] = "su";
static const unsigned char _c19[] = "s";
static const unsigned char _c18[] = "\077";
static const unsigned char _c17[] = "_";
static const unsigned char _c16[] = "";
static const unsigned char _c15[] = "/tag";
static const unsigned char _c14[] = "/adr";
static const unsigned char _c13[] = "/len";
static const unsigned char _c12[] = "\042";
static const unsigned char _c11[] = "*";
static const unsigned char _c10[] = "\077\077";
static const unsigned char _c9[] = ".0";
static const unsigned char _c8[] = "()";
static const unsigned char _c7[] = "<fpar>";
static const unsigned char _c6[] = "<field>";
static const unsigned char _c5[] = "<tb_proc>";
static const unsigned char _c4[] = ".";
static const unsigned char _c3[] = "<anon_struct>";
static const unsigned char _c2[] = ") ";
static const unsigned char _c1[] = "  ";
static const unsigned char _c0[] = "[XXX] ";

