/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
#include "WriteSymbols.d"

static _ModId _mid;

void WriteSymbols__Ln(short int off) {
  register int i0, i1;
  i0 = off < 1;
  Out__Ln();
  if (i0) goto l1;
  i1 = 1;
l0:
  i1++;
  Out__String((const unsigned char*)(int)_c0, 3);
  i0 = off >= i1;
  if (i0) goto l0;
l1:
  ;
}

unsigned char WriteSymbols__Const_Char_Cypher(int int_) {
  register int i0;
  i0 = int_ < 10;
  if (i0) goto l0;
  i0 = int_ - 10;
  i0 += 65;
  goto l1;
l0:
  i0 = int_ + 48;
l1:
  return (unsigned char)i0;
}

void WriteSymbols__Const_Char(int char_, unsigned char* WriteSymbols__Const_str, int WriteSymbols__Const_str_0d) {
  register int i0, i1, i2;
  i0 = char_ == 34;
  if (i0) goto l2;
  i1 = char_ < 32;
  if (i1) goto l0;
  i0 = char_ == 127;
  if (i0) goto l0;
  i1 = char_ > 255;
  if (i1) goto l0;
  _string_copy((int)WriteSymbols__Const_str, (int)_c1, WriteSymbols__Const_str_0d);
  i0 = (int)WriteSymbols__Const_str + 1;
  *(unsigned char*)i0 = char_;
  goto l3;
l0:
  _string_copy((int)WriteSymbols__Const_str, (int)_c2, WriteSymbols__Const_str_0d);
  i0 = *(unsigned char*)(int)WriteSymbols__Const_str;
  i0 = i0 != 48;
  if (i0) goto l3;
  i2 = (int)WriteSymbols__Const_str + 1;
  i1 = *(unsigned char*)i2;
  i1 = i1 >= 65;
  if (i1) goto l3;
l1:
  Strings__Delete((unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d, (short int)0, (short int)1);
  i0 = *(unsigned char*)(int)WriteSymbols__Const_str;
  i0 = i0 != 48;
  if (i0) goto l3;
  i0 = *(unsigned char*)i2;
  i0 = i0 < 65;
  if (i0) goto l1;
  goto l3;
l2:
  _string_copy((int)WriteSymbols__Const_str, (int)_c3, WriteSymbols__Const_str_0d);
  i0 = (int)WriteSymbols__Const_str + 1;
  *(unsigned char*)i0 = 34;
l3:
  ;
}

void WriteSymbols__Const_Real(double val, short int prec, unsigned char exp, unsigned char* WriteSymbols__Const_str, int WriteSymbols__Const_str_0d) {
  register int i0, i1, i2, i3;
  LRealStr__RealToFloat((double)val, (short int)prec, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
  i2 = *(unsigned char*)(int)WriteSymbols__Const_str;
  i0 = i2 == 0;
  if (i0) goto l1;
  i1 = i2 == 69;
  if (i1) goto l1;
  i3 = 0;
l0:
  i3++;
  i0 = (int)WriteSymbols__Const_str + i3;
  i2 = *(unsigned char*)i0;
  i0 = i2 == 0;
  if (i0) goto l2;
  i2 = i2 != 69;
  if (i2) goto l0;
  goto l2;
l1:
  i3 = 0;
l2:
  i0 = (int)WriteSymbols__Const_str + i3;
  i1 = *(unsigned char*)i0;
  i1 = i1 == 69;
  if (i1) goto l3;
  i0 = (int)exp != 68;
  if (i0) goto l4;
  Strings__Append((const unsigned char*)(int)_c4, 3, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
  goto l4;
l3:
  *(unsigned char*)i0 = (int)exp;
l4:
  ;
}

void WriteSymbols__Const_Set(unsigned int set, unsigned char* WriteSymbols__Const_str, int WriteSymbols__Const_str_0d) {
  register int i0, i1, i2, i3, i4;
  unsigned char num[32];
  _string_copy((int)WriteSymbols__Const_str, (int)_c5, WriteSymbols__Const_str_0d);
  i1 = 0;
  i2 = 0;
l0:
  i4 = (set & ((unsigned int)1 << i1)) != 0;
  if (i4) goto l1;
  i0 = i1;
  goto l9;
l1:
  if (!(i2)) goto l2;
  Strings__Append((const unsigned char*)(int)_c6, 3, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
l2:
  i4 = i1 + 2;
  IntStr__IntToStr((int)i1, (unsigned char*)(int)num, 32);
  i3 = i4 > 31;
  Strings__Append((const unsigned char*)(int)num, 32, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
  if (i3) goto l3;
  i3 = i1 + 1;
  i0 = (set & ((unsigned int)1 << i3)) != 0;
  if (!(i0)) goto l3;
  i0 = (set & ((unsigned int)1 << i4)) != 0;
  if (i0) goto l4;
l3:
  i0 = i1;
  goto l8;
l4:
  i3 = i3 <= 31;
  if (i3) goto l5;
  i0 = i1;
  goto l7;
l5:
  i0 = i1;
l6:
  i0++;
  i3 = i0 + 1;
  i4 = i3 > 31;
  if (i4) goto l7;
  i3 = (set & ((unsigned int)1 << i3)) != 0;
  if (i3) goto l6;
l7:
  Strings__Append((const unsigned char*)(int)_c7, 3, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
  IntStr__IntToStr((int)i0, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
  Strings__Append((const unsigned char*)(int)num, 32, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
l8:
  i2 = 1;
l9:
  i1 = i0 + 1;
  i4 = i1 <= 31;
  if (i4) goto l0;
  Strings__Append((const unsigned char*)(int)_c8, 2, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
}

void WriteSymbols__Const_String8(const unsigned char* s__ref, int s_0d, int len, unsigned char* WriteSymbols__Const_str, int WriteSymbols__Const_str_0d) {
  register int i0, i1, i2, i3;
  unsigned char* s;
  char* _old_top_vs = _top_vs;
  _push_value(int, s, s__ref, s_0d);
  i2 = *(unsigned char*)(int)s;
  i0 = i2 == 0;
  if (i0) goto l1;
  i1 = i2 == 34;
  if (i1) goto l1;
  i3 = 0;
l0:
  i3++;
  i0 = (int)s + i3;
  i2 = *(unsigned char*)i0;
  i0 = i2 == 0;
  if (i0) goto l2;
  i2 = i2 != 34;
  if (i2) goto l0;
  goto l2;
l1:
  i3 = 0;
l2:
  i0 = (int)s + i3;
  i0 = *(unsigned char*)i0;
  i0 = i0 != 0;
  if (i0) goto l3;
  i0 = 34;
  goto l4;
l3:
  i0 = 39;
l4:
  i1 = (int)WriteSymbols__Const_str + 1;
  *(unsigned char*)(int)WriteSymbols__Const_str = i0;
  *(unsigned char*)i1 = i0;
  i0 = (int)WriteSymbols__Const_str + 2;
  *(unsigned char*)i0 = 0;
  Strings__Insert((const unsigned char*)(int)s, s_0d, (short int)1, (unsigned char*)(int)WriteSymbols__Const_str, WriteSymbols__Const_str_0d);
  _top_vs = _old_top_vs;
}

void WriteSymbols__Const_String16(const unsigned char* s__ref, int s_0d, int len, unsigned char* WriteSymbols__Const_str, int WriteSymbols__Const_str_0d) {
  unsigned char* s;
  char* _old_top_vs = _top_vs;
  _push_value(int, s, s__ref, s_0d);
  _string_copy((int)WriteSymbols__Const_str, (int)_c9, WriteSymbols__Const_str_0d);
  _top_vs = _old_top_vs;
}

void WriteSymbols__Const(Data__Const const_, unsigned char* str, int str_0d) {
  register int i0, i1, i2;
  register double d0;
  i0 = (int)const_ + 16;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i0 = *(signed char*)i0;
  if (i0<=-1 || (i0>=10 && i0<=11) || (i0>=16 && i0<=17) || i0>=21) goto l10;
  if (!(i0==1)) goto l1;
  i0 = (int)const_ + 24;
  i0 = *(int*)i0;
  i0 = i0 == 0;
  if (i0) goto l0;
  _string_copy((int)str, (int)_c10, str_0d);
  goto l10;
l0:
  _string_copy((int)str, (int)_c11, str_0d);
  goto l10;
l1:
  if (!((i0>=2 && i0<=3))) goto l2;
  i0 = (int)const_ + 24;
  i0 = *(int*)i0;
  WriteSymbols__Const_Char((int)i0, str, str_0d);
  goto l10;
l2:
  if (!((i0>=4 && i0<=7))) goto l3;
  i0 = (int)const_ + 24;
  i0 = *(int*)i0;
  IntStr__IntToStr((int)i0, (unsigned char*)(int)str, str_0d);
  goto l10;
l3:
  if (!(i0==8)) goto l4;
  i0 = (int)const_ + 40;
  d0 = *(double*)i0;
  WriteSymbols__Const_Real((double)d0, (short int)7, (unsigned char)69, str, str_0d);
  goto l10;
l4:
  if (!(i0==9)) goto l5;
  i0 = (int)const_ + 40;
  d0 = *(double*)i0;
  WriteSymbols__Const_Real((double)d0, (short int)14, (unsigned char)68, str, str_0d);
  goto l10;
l5:
  if (!((i0>=12 && i0<=15))) goto l6;
  i0 = (int)const_ + 32;
  i0 = *(unsigned int*)i0;
  WriteSymbols__Const_Set((unsigned int)i0, str, str_0d);
  goto l10;
l6:
  if (!(i0==18)) goto l7;
  i1 = (int)const_ + 20;
  i1 = (int)*(void**)i1;
  i0 = (int)const_ + 24;
  i2 = *(int*)(i1-8);
  i0 = *(int*)i0;
  WriteSymbols__Const_String8((const unsigned char*)i1, i2, (int)i0, str, str_0d);
  goto l10;
l7:
  if (!(i0==19)) goto l8;
  i1 = (int)const_ + 20;
  i1 = (int)*(void**)i1;
  i2 = (int)const_ + 24;
  i0 = *(int*)(i1-8);
  i2 = *(int*)i2;
  WriteSymbols__Const_String16((const unsigned char*)i1, i0, (int)i2, str, str_0d);
  goto l10;
l8:
  if (!(i0==20)) goto l9;
  _string_copy((int)str, (int)_c12, str_0d);
  goto l10;
l9:
  if (!(i0==0)) goto l10;
  _string_copy((int)str, (int)_c13, str_0d);
l10:
  ;
}

void WriteSymbols__WriteConst(Data__Const const_) {
  unsigned char str[256];
  WriteSymbols__Const((Data__Const)(int)const_, (unsigned char*)(int)str, 256);
  Out__String((const unsigned char*)(int)str, 256);
}

void WriteSymbols__WriteTree_WriteObject_WriteStruct(Data__Struct t, unsigned char structure, short int off, short int *WriteSymbols__WriteTree_off) {
  register int i0, i1, i2, i3;
  i1 = (int)t + 36;
  i0 = (int)*(void**)i1;
  i2 = i0 == 0;
  if (i2) goto l0;
  if (!(structure)) goto l18;
l0:
  i2 = (int)t + 20;
  i2 = *(signed char*)i2;
  if (i2<=-1 || (i2>=1 && i2<=17) || (i2>=22 && i2<=26) || i2>=32) goto l20;
  if (!(i2==0)) goto l1;
  Out__String((const unsigned char*)(int)_c14, 15);
  goto l20;
l1:
  if (!(i2==18)) goto l2;
  Out__String((const unsigned char*)(int)_c15, 10);
  goto l20;
l2:
  if (!(i2==19)) goto l3;
  Out__String((const unsigned char*)(int)_c16, 11);
  goto l20;
l3:
  if (!(i2==20)) goto l4;
  Out__String((const unsigned char*)(int)_c17, 6);
  goto l20;
l4:
  if (!(i2==21)) goto l5;
  Out__String((const unsigned char*)(int)_c18, 10);
  goto l20;
l5:
  if (!(i2==27)) goto l6;
  Out__String((const unsigned char*)(int)_c19, 12);
  i2 = (int)t + 24;
  i2 = (int)*(void**)i2;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i2, (unsigned char)0, (short int)off, &*WriteSymbols__WriteTree_off);
  goto l20;
l6:
  if (!(i2==28)) goto l12;
  if (!(structure)) goto l7;
  Out__String((const unsigned char*)(int)_c20, 10);
l7:
  i2 = (int)t + 28;
  i1 = (int)*(void**)i2;
  i1 = i1 != 0;
  if (i1) goto l8;
  i1 = (int)t + 24;
  i1 = (int)*(void**)i1;
  i1 += 20;
  i1 = *(signed char*)i1;
  i1 = i1 == 21;
  if (i1) goto l20;
l8:
  Out__String((const unsigned char*)(int)_c21, 3);
  i0 = (int)*(void**)i2;
  i3 = i0 == 0;
  if (i3) goto l11;
l9:
  i1 = i0 + 36;
  i3 = (int)*(void**)i2;
  i3 = i0 == i3;
  if (i3) goto l10;
  Out__String((const unsigned char*)(int)_c22, 3);
l10:
  WriteSymbols__WriteTree_WriteObject((Data__Object)i0, &*WriteSymbols__WriteTree_off);
  i0 = (int)*(void**)i1;
  i1 = i0 != 0;
  if (i1) goto l9;
l11:
  i3 = (int)t + 24;
  Out__Char((unsigned char)41);
  i0 = (int)*(void**)i3;
  i0 += 20;
  i0 = *(signed char*)i0;
  i0 = i0 == 21;
  if (i0) goto l20;
  Out__String((const unsigned char*)(int)_c23, 3);
  i3 = (int)*(void**)i3;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i3, (unsigned char)0, (short int)off, &*WriteSymbols__WriteTree_off);
  goto l20;
l12:
  if (!(i2==29)) goto l13;
  Out__String((const unsigned char*)(int)_c24, 7);
  i2 = (int)t + 32;
  i2 = *(int*)i2;
  Out__LongInt((int)i2, (int)0);
  Out__String((const unsigned char*)(int)_c25, 5);
  i2 = (int)t + 24;
  i2 = (int)*(void**)i2;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i2, (unsigned char)0, (short int)off, &*WriteSymbols__WriteTree_off);
  goto l20;
l13:
  if (!(i2==30)) goto l14;
  Out__String((const unsigned char*)(int)_c26, 10);
  i2 = (int)t + 24;
  i2 = (int)*(void**)i2;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i2, (unsigned char)0, (short int)off, &*WriteSymbols__WriteTree_off);
  goto l20;
l14:
  if (!(i2==31)) goto l20;
  i2 = (int)t + 24;
  Out__String((const unsigned char*)(int)_c27, 7);
  i3 = (int)*(void**)i2;
  i3 = i3 == 0;
  if (i3) goto l15;
  WriteSymbols__Ln((short int)off);
  Out__Char((unsigned char)40);
  i2 = (int)*(void**)i2;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i2, (unsigned char)0, (short int)off, &*WriteSymbols__WriteTree_off);
  Out__Char((unsigned char)41);
l15:
  i2 = (int)t + 28;
  i2 = (int)*(void**)i2;
  i3 = i2 == 0;
  if (i3) goto l17;
l16:
  i3 = i2 + 36;
  WriteSymbols__Ln((short int)off);
  WriteSymbols__WriteTree_WriteObject((Data__Object)i2, &*WriteSymbols__WriteTree_off);
  i2 = (int)*(void**)i3;
  i3 = i2 != 0;
  if (i3) goto l16;
l17:
  i2 = off - 1;
  WriteSymbols__Ln((short int)i2);
  Out__String((const unsigned char*)(int)_c28, 4);
  goto l20;
l18:
  i0 = (int)SymbolTable__Module((Data__Object)i0);
  i2 = (int)SymbolTable__predef;
  i2 = i0 == i2;
  if (i2) goto l19;
  i0 += 52;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i2 = (int)*(void**)i0;
  i0 = *(int*)(i2-8);
  Out__String((const unsigned char*)i2, i0);
  Out__Char((unsigned char)46);
l19:
  i0 = (int)*(void**)i1;
  i0 += 20;
  i1 = (int)*(void**)i0;
  i0 = *(int*)(i1-8);
  Out__String((const unsigned char*)i1, i0);
l20:
  ;
}

void WriteSymbols__WriteTree_WriteObject_Name(Data__Object *WriteSymbols__WriteTree_WriteObject_obj) {
  register int i0, i1, i2, i3;
  i1 = (int)*WriteSymbols__WriteTree_WriteObject_obj;
  i0 = i1 + 20;
  i2 = (int)*(void**)i0;
  i0 = i2 == 0;
  if (i0) goto l0;
  i3 = strcmp((const char*) i2, (const char*) (int)_c29) == 0;
  if (i3) goto l0;
  i0 = *(int*)(i2-8);
  Out__String((const unsigned char*)i2, i0);
  goto l1;
l0:
  Out__String((const unsigned char*)(int)_c30, 10);
l1:
  i0 = i1 + 64;
  i0 = *(unsigned int*)i0;
  i1 = (i0 & ((unsigned int)1 << 0)) != 0;
  if (!(i1)) goto l3;
  i0 = (i0 & ((unsigned int)1 << 1)) != 0;
  if (i0) goto l2;
  Out__Char((unsigned char)42);
  goto l3;
l2:
  Out__Char((unsigned char)45);
l3:
  ;
}

void WriteSymbols__WriteTree_WriteObject(Data__Object obj, short int *WriteSymbols__WriteTree_off) {
  register int i0, i1, i2, i3;
  Out__String((const unsigned char*)(int)_c31, 6);
  i0 = (int)obj + 48;
  i0 = *(short int*)i0;
  Out__Int((short int)i0, (int)0);
  Out__String((const unsigned char*)(int)_c32, 6);
  i0 = (int)obj + 50;
  i0 = *(short int*)i0;
  Out__Int((short int)i0, (int)0);
  Out__String((const unsigned char*)(int)_c33, 3);
  i0 = (int)obj + 28;
  i0 = *(signed char*)i0;
  if (i0<=-1 || i0>=10) goto l9;
  if (!(i0==0)) goto l0;
  Out__String((const unsigned char*)(int)_c34, 15);
  goto l9;
l0:
  if (!(i0==1)) goto l1;
  Out__String((const unsigned char*)(int)_c35, 7);
  WriteSymbols__WriteTree_WriteObject_Name((Data__Object *)&obj);
  Out__String((const unsigned char*)(int)_c36, 4);
  i0 = (int)obj + 52;
  i0 = (int)*(void**)i0;
  WriteSymbols__WriteConst((Data__Const)i0);
  goto l9;
l1:
  if (!(i0==2)) goto l2;
  Out__String((const unsigned char*)(int)_c37, 6);
  WriteSymbols__WriteTree_WriteObject_Name((Data__Object *)&obj);
  Out__String((const unsigned char*)(int)_c36, 4);
  i2 = (int)obj + 24;
  i2 = (int)*(void**)i2;
  i1 = i2 + 36;
  i3 = *WriteSymbols__WriteTree_off;
  i0 = (int)*(void**)i1;
  i1 = i3 + 1;
  i0 = (int)obj == i0;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i2, (unsigned char)i0, (short int)i1, &*WriteSymbols__WriteTree_off);
  goto l9;
l2:
  if (!(i0==3)) goto l3;
  Out__String((const unsigned char*)(int)_c38, 5);
  WriteSymbols__WriteTree_WriteObject_Name((Data__Object *)&obj);
  i1 = *WriteSymbols__WriteTree_off;
  Out__String((const unsigned char*)(int)_c23, 3);
  i0 = (int)obj + 24;
  i2 = i1 + 1;
  i0 = (int)*(void**)i0;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i0, (unsigned char)0, (short int)i2, &*WriteSymbols__WriteTree_off);
  goto l9;
l3:
  if (!(i0==4)) goto l4;
  Out__String((const unsigned char*)(int)_c39, 8);
  WriteSymbols__WriteTree_WriteObject_Name((Data__Object *)&obj);
  i1 = *WriteSymbols__WriteTree_off;
  Out__String((const unsigned char*)(int)_c23, 3);
  i0 = (int)obj + 24;
  i2 = i1 + 1;
  i0 = (int)*(void**)i0;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i0, (unsigned char)0, (short int)i2, &*WriteSymbols__WriteTree_off);
  goto l9;
l4:
  if (!(i0==5)) goto l5;
  WriteSymbols__WriteTree_WriteObject_Name((Data__Object *)&obj);
  i2 = *WriteSymbols__WriteTree_off;
  Out__String((const unsigned char*)(int)_c23, 3);
  i0 = (int)obj + 24;
  i1 = i2 + 1;
  i0 = (int)*(void**)i0;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i0, (unsigned char)0, (short int)i1, &*WriteSymbols__WriteTree_off);
  goto l9;
l5:
  if (!((i0>=6 && i0<=7))) goto l7;
  i2 = (int)obj + 52;
  Out__String((const unsigned char*)(int)_c40, 11);
  i3 = (int)*(void**)i2;
  i3 = i3 == 0;
  if (i3) goto l6;
  Out__Char((unsigned char)40);
  i2 = (int)*(void**)i2;
  WriteSymbols__WriteTree_WriteObject((Data__Object)i2, &*WriteSymbols__WriteTree_off);
  Out__String((const unsigned char*)(int)_c41, 3);
l6:
  WriteSymbols__WriteTree_WriteObject_Name((Data__Object *)&obj);
  i2 = *WriteSymbols__WriteTree_off;
  i3 = (int)obj + 44;
  i0 = (int)obj + 24;
  i1 = i2 + 1;
  i0 = (int)*(void**)i0;
  WriteSymbols__WriteTree_WriteObject_WriteStruct((Data__Struct)i0, (unsigned char)0, (short int)i1, &*WriteSymbols__WriteTree_off);
  i2 = *WriteSymbols__WriteTree_off;
  i3 = (int)*(void**)i3;
  i2++;
  WriteSymbols__WriteTree((Data__Object)i3, (short int)i2);
  goto l9;
l7:
  if (!(i0==8)) goto l8;
  Out__String((const unsigned char*)(int)_c42, 8);
  i0 = (int)obj + 20;
  i0 = (int)*(void**)i0;
  i1 = *(int*)(i0-8);
  Out__String((const unsigned char*)i0, i1);
  Out__String((const unsigned char*)(int)_c43, 5);
  i0 = (int)obj + 52;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i1 = (int)*(void**)i0;
  i0 = *(int*)(i1-8);
  Out__String((const unsigned char*)i1, i0);
  goto l9;
l8:
  if (!(i0==9)) goto l9;
  Out__String((const unsigned char*)(int)_c44, 4);
l9:
  ;
}

void WriteSymbols__WriteTree(Data__Object obj, short int off) {
  register int i0, i1;
  i0 = (int)obj == 0;
  if (i0) goto l0;
  i1 = (int)obj + 32;
  i0 = (int)obj + 36;
  i1 = (int)*(void**)i1;
  WriteSymbols__WriteTree((Data__Object)i1, (short int)off);
  WriteSymbols__Ln((short int)off);
  WriteSymbols__Ln((short int)off);
  WriteSymbols__WriteTree_WriteObject((Data__Object)(int)obj, &off);
  i0 = (int)*(void**)i0;
  WriteSymbols__WriteTree((Data__Object)i0, (short int)off);
l0:
  ;
}

void WriteSymbols__WriteModule(Data__Object mod) {
  register int i0, i1, i2, i3, i4;
  i3 = (int)mod + 20;
  Out__String((const unsigned char*)(int)_c45, 8);
  i0 = (int)*(void**)i3;
  i1 = (int)mod + 52;
  i2 = *(int*)(i0-8);
  Out__String((const unsigned char*)i0, i2);
  i0 = (int)*(void**)i1;
  i0 = i0 == 0;
  if (i0) goto l0;
  Out__String((const unsigned char*)(int)_c46, 8);
  i2 = (int)*(void**)i1;
  i2 += 20;
  i0 = (int)*(void**)i2;
  i2 = *(int*)(i0-8);
  Out__String((const unsigned char*)i0, i2);
l0:
  Out__String((const unsigned char*)(int)_c47, 7);
  i0 = (int)mod + 48;
  i0 = *(short int*)i0;
  Out__Int((short int)i0, (int)0);
  Out__String((const unsigned char*)(int)_c32, 6);
  i0 = (int)mod + 50;
  i0 = *(short int*)i0;
  Out__Int((short int)i0, (int)0);
  Out__String((const unsigned char*)(int)_c48, 2);
  Out__Ln();
  Out__Ln();
  Out__String((const unsigned char*)(int)_c49, 13);
  i0 = (int)mod + 32;
  i2 = (int)*(void**)i0;
  i0 = i2 == 0;
  if (i0) goto l2;
l1:
  Out__Char((unsigned char)32);
  i0 = i2 + 52;
  i0 = (int)*(void**)i0;
  i0 += 20;
  i0 = (int)*(void**)i0;
  i4 = *(int*)(i0-8);
  Out__String((const unsigned char*)i0, i4);
  i0 = i2 + 36;
  i2 = (int)*(void**)i0;
  i0 = i2 != 0;
  if (i0) goto l1;
l2:
  Out__Ln();
  i0 = (int)mod + 44;
  Out__Ln();
  i0 = (int)*(void**)i0;
  WriteSymbols__WriteTree((Data__Object)i0, (short int)0);
  Out__Ln();
  Out__Ln();
  Out__String((const unsigned char*)(int)_c50, 5);
  i1 = (int)*(void**)i1;
  i0 = i1 == 0;
  if (i0) goto l3;
  i1 += 20;
  i1 = (int)*(void**)i1;
  i0 = *(int*)(i1-8);
  Out__String((const unsigned char*)i1, i0);
  goto l4;
l3:
  i3 = (int)*(void**)i3;
  i0 = *(int*)(i3-8);
  Out__String((const unsigned char*)i3, i0);
l4:
  Out__Char((unsigned char)46);
  Out__Ln();
}

void WriteSymbols_init(void) {
  _mid = _register_module(&WriteSymbols_md.md, NULL);
}
